<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Ben Houghton">
<meta name="dcterms.date" content="2026-09-10">

<title>DSAN 6600 Week 03: Backpropagation and PyTorch</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="week-3_files/libs/clipboard/clipboard.min.js"></script>
<script src="week-3_files/libs/quarto-html/quarto.js"></script>
<script src="week-3_files/libs/quarto-html/popper.min.js"></script>
<script src="week-3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="week-3_files/libs/quarto-html/anchor.min.js"></script>
<link href="week-3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="week-3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="week-3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="week-3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="week-3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link rel="icon" type="image/png" href="/icon.png">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#backpropagation-and-pytorch" id="toc-backpropagation-and-pytorch" class="nav-link active" data-scroll-target="#backpropagation-and-pytorch">Backpropagation and PyTorch</a>
  <ul class="collapse">
  <li><a href="#agenda" id="toc-agenda" class="nav-link" data-scroll-target="#agenda">Agenda</a></li>
  <li><a href="#lab-2-recap" id="toc-lab-2-recap" class="nav-link" data-scroll-target="#lab-2-recap">Lab 2 recap</a></li>
  <li><a href="#cost-of-one-gradient-step" id="toc-cost-of-one-gradient-step" class="nav-link" data-scroll-target="#cost-of-one-gradient-step">Cost of one gradient step</a></li>
  <li><a href="#limits-of-analytical-solutions" id="toc-limits-of-analytical-solutions" class="nav-link" data-scroll-target="#limits-of-analytical-solutions">Limits of analytical solutions</a></li>
  <li><a href="#three-ways-to-get-a-gradient" id="toc-three-ways-to-get-a-gradient" class="nav-link" data-scroll-target="#three-ways-to-get-a-gradient">Three ways to get a gradient</a></li>
  <li><a href="#automatic-differentiation" id="toc-automatic-differentiation" class="nav-link" data-scroll-target="#automatic-differentiation">Automatic differentiation</a></li>
  <li><a href="#backpropagation" id="toc-backpropagation" class="nav-link" data-scroll-target="#backpropagation">Backpropagation</a></li>
  <li><a href="#loss-and-cost" id="toc-loss-and-cost" class="nav-link" data-scroll-target="#loss-and-cost">Loss and cost</a></li>
  </ul></li>
  <li><a href="#the-chain-rule" id="toc-the-chain-rule" class="nav-link" data-scroll-target="#the-chain-rule">The chain rule</a>
  <ul class="collapse">
  <li><a href="#chain-rule-for-composite-functions" id="toc-chain-rule-for-composite-functions" class="nav-link" data-scroll-target="#chain-rule-for-composite-functions">Chain rule for composite functions</a></li>
  <li><a href="#multivariable-chain-rule" id="toc-multivariable-chain-rule" class="nav-link" data-scroll-target="#multivariable-chain-rule">Multivariable chain rule</a></li>
  <li><a href="#multivariable-chain-rule-worked" id="toc-multivariable-chain-rule-worked" class="nav-link" data-scroll-target="#multivariable-chain-rule-worked">Multivariable chain rule, worked</a></li>
  <li><a href="#chain-rule-along-a-network-path" id="toc-chain-rule-along-a-network-path" class="nav-link" data-scroll-target="#chain-rule-along-a-network-path">Chain rule along a network path</a></li>
  <li><a href="#generalized-chain-rule" id="toc-generalized-chain-rule" class="nav-link" data-scroll-target="#generalized-chain-rule">Generalized chain rule</a></li>
  <li><a href="#gradient-notation" id="toc-gradient-notation" class="nav-link" data-scroll-target="#gradient-notation">Gradient notation</a></li>
  <li><a href="#gradient-of-the-cost-with-respect-to-a-weight-matrix" id="toc-gradient-of-the-cost-with-respect-to-a-weight-matrix" class="nav-link" data-scroll-target="#gradient-of-the-cost-with-respect-to-a-weight-matrix">Gradient of the cost with respect to a weight matrix</a></li>
  </ul></li>
  <li><a href="#computational-graphs" id="toc-computational-graphs" class="nav-link" data-scroll-target="#computational-graphs">Computational graphs</a>
  <ul class="collapse">
  <li><a href="#computational-graphs-as-directed-acyclic-graphs" id="toc-computational-graphs-as-directed-acyclic-graphs" class="nav-link" data-scroll-target="#computational-graphs-as-directed-acyclic-graphs">Computational graphs as directed acyclic graphs</a></li>
  <li><a href="#graph-of-an-expression" id="toc-graph-of-an-expression" class="nav-link" data-scroll-target="#graph-of-an-expression">Graph of an expression</a></li>
  <li><a href="#forward-pass-on-a-graph" id="toc-forward-pass-on-a-graph" class="nav-link" data-scroll-target="#forward-pass-on-a-graph">Forward pass on a graph</a></li>
  <li><a href="#the-chain-rule-on-a-graph" id="toc-the-chain-rule-on-a-graph" class="nav-link" data-scroll-target="#the-chain-rule-on-a-graph">The chain rule on a graph</a></li>
  <li><a href="#local-derivatives-at-a-node" id="toc-local-derivatives-at-a-node" class="nav-link" data-scroll-target="#local-derivatives-at-a-node">Local derivatives at a node</a></li>
  <li><a href="#backward-pass-on-a-graph" id="toc-backward-pass-on-a-graph" class="nav-link" data-scroll-target="#backward-pass-on-a-graph">Backward pass on a graph</a></li>
  <li><a href="#gradients-sum-over-paths" id="toc-gradients-sum-over-paths" class="nav-link" data-scroll-target="#gradients-sum-over-paths">Gradients sum over paths</a></li>
  <li><a href="#a-sigmoid-expanded-into-primitive-nodes" id="toc-a-sigmoid-expanded-into-primitive-nodes" class="nav-link" data-scroll-target="#a-sigmoid-expanded-into-primitive-nodes">A sigmoid expanded into primitive nodes</a></li>
  <li><a href="#the-same-sigmoid-as-one-node" id="toc-the-same-sigmoid-as-one-node" class="nav-link" data-scroll-target="#the-same-sigmoid-as-one-node">The same sigmoid as one node</a></li>
  <li><a href="#execution-order-and-topological-sorting" id="toc-execution-order-and-topological-sorting" class="nav-link" data-scroll-target="#execution-order-and-topological-sorting">Execution order and topological sorting</a></li>
  <li><a href="#kahns-algorithm" id="toc-kahns-algorithm" class="nav-link" data-scroll-target="#kahns-algorithm">Kahn’s algorithm</a></li>
  <li><a href="#topological-sort-the-starting-queue" id="toc-topological-sort-the-starting-queue" class="nav-link" data-scroll-target="#topological-sort-the-starting-queue">Topological sort: the starting queue</a></li>
  <li><a href="#topological-sort-step-1" id="toc-topological-sort-step-1" class="nav-link" data-scroll-target="#topological-sort-step-1">Topological sort: step 1</a></li>
  <li><a href="#topological-sort-step-2" id="toc-topological-sort-step-2" class="nav-link" data-scroll-target="#topological-sort-step-2">Topological sort: step 2</a></li>
  <li><a href="#topological-sort-step-3" id="toc-topological-sort-step-3" class="nav-link" data-scroll-target="#topological-sort-step-3">Topological sort: step 3</a></li>
  <li><a href="#topological-sort-step-4" id="toc-topological-sort-step-4" class="nav-link" data-scroll-target="#topological-sort-step-4">Topological sort: step 4</a></li>
  <li><a href="#topological-sort-step-5" id="toc-topological-sort-step-5" class="nav-link" data-scroll-target="#topological-sort-step-5">Topological sort: step 5</a></li>
  <li><a href="#topological-sort-step-6" id="toc-topological-sort-step-6" class="nav-link" data-scroll-target="#topological-sort-step-6">Topological sort: step 6</a></li>
  <li><a href="#topological-sort-the-finished-order" id="toc-topological-sort-the-finished-order" class="nav-link" data-scroll-target="#topological-sort-the-finished-order">Topological sort: the finished order</a></li>
  <li><a href="#topological-sort-animated" id="toc-topological-sort-animated" class="nav-link" data-scroll-target="#topological-sort-animated">Topological sort, animated</a></li>
  <li><a href="#kahns-algorithm-in-pseudocode" id="toc-kahns-algorithm-in-pseudocode" class="nav-link" data-scroll-target="#kahns-algorithm-in-pseudocode">Kahn’s algorithm in pseudocode</a></li>
  </ul></li>
  <li><a href="#reverse-mode-autodiff" id="toc-reverse-mode-autodiff" class="nav-link" data-scroll-target="#reverse-mode-autodiff">Reverse-mode autodiff</a>
  <ul class="collapse">
  <li><a href="#scalar-regression-example" id="toc-scalar-regression-example" class="nav-link" data-scroll-target="#scalar-regression-example">Scalar regression example</a></li>
  <li><a href="#scalar-regression-graph-both-passes" id="toc-scalar-regression-graph-both-passes" class="nav-link" data-scroll-target="#scalar-regression-graph-both-passes">Scalar regression graph, both passes</a></li>
  <li><a href="#the-same-graph-in-pytorch" id="toc-the-same-graph-in-pytorch" class="nav-link" data-scroll-target="#the-same-graph-in-pytorch">The same graph in PyTorch</a></li>
  <li><a href="#reading-gradients-out-of-.grad" id="toc-reading-gradients-out-of-.grad" class="nav-link" data-scroll-target="#reading-gradients-out-of-.grad">Reading gradients out of <code>.grad</code></a></li>
  <li><a href="#scalar-classification-graph" id="toc-scalar-classification-graph" class="nav-link" data-scroll-target="#scalar-classification-graph">Scalar classification graph</a></li>
  <li><a href="#scalar-classification-graph-both-passes" id="toc-scalar-classification-graph-both-passes" class="nav-link" data-scroll-target="#scalar-classification-graph-both-passes">Scalar classification graph, both passes</a></li>
  <li><a href="#derivative-of-binary-cross-entropy" id="toc-derivative-of-binary-cross-entropy" class="nav-link" data-scroll-target="#derivative-of-binary-cross-entropy">Derivative of binary cross-entropy</a></li>
  <li><a href="#classification-in-pytorch" id="toc-classification-in-pytorch" class="nav-link" data-scroll-target="#classification-in-pytorch">Classification in PyTorch</a></li>
  <li><a href="#gradient-of-cross-entropy-with-a-sigmoid-output" id="toc-gradient-of-cross-entropy-with-a-sigmoid-output" class="nav-link" data-scroll-target="#gradient-of-cross-entropy-with-a-sigmoid-output">Gradient of cross-entropy with a sigmoid output</a></li>
  <li><a href="#forward-mode-and-reverse-mode" id="toc-forward-mode-and-reverse-mode" class="nav-link" data-scroll-target="#forward-mode-and-reverse-mode">Forward mode and reverse mode</a></li>
  <li><a href="#choosing-forward-or-reverse-mode" id="toc-choosing-forward-or-reverse-mode" class="nav-link" data-scroll-target="#choosing-forward-or-reverse-mode">Choosing forward or reverse mode</a></li>
  </ul></li>
  <li><a href="#from-a-scalar-to-a-layer" id="toc-from-a-scalar-to-a-layer" class="nav-link" data-scroll-target="#from-a-scalar-to-a-layer">From a scalar to a layer</a>
  <ul class="collapse">
  <li><a href="#backward-pass-of-a-linear-layer" id="toc-backward-pass-of-a-linear-layer" class="nav-link" data-scroll-target="#backward-pass-of-a-linear-layer">Backward pass of a linear layer</a></li>
  <li><a href="#shape-check-on-the-layer-gradients" id="toc-shape-check-on-the-layer-gradients" class="nav-link" data-scroll-target="#shape-check-on-the-layer-gradients">Shape check on the layer gradients</a></li>
  <li><a href="#layer-backward-pass-verified-against-autograd" id="toc-layer-backward-pass-verified-against-autograd" class="nav-link" data-scroll-target="#layer-backward-pass-verified-against-autograd">Layer backward pass, verified against autograd</a></li>
  <li><a href="#the-three-rules-that-reproduced-autograd" id="toc-the-three-rules-that-reproduced-autograd" class="nav-link" data-scroll-target="#the-three-rules-that-reproduced-autograd">The three rules that reproduced autograd</a></li>
  <li><a href="#ann-matrix-notation" id="toc-ann-matrix-notation" class="nav-link" data-scroll-target="#ann-matrix-notation">ANN matrix notation</a></li>
  <li><a href="#ann-forward-and-backward-worked" id="toc-ann-forward-and-backward-worked" class="nav-link" data-scroll-target="#ann-forward-and-backward-worked">ANN forward and backward, worked</a></li>
  <li><a href="#jacobian-memory-cost" id="toc-jacobian-memory-cost" class="nav-link" data-scroll-target="#jacobian-memory-cost">Jacobian memory cost</a></li>
  <li><a href="#one-entry-of-the-weight-gradient" id="toc-one-entry-of-the-weight-gradient" class="nav-link" data-scroll-target="#one-entry-of-the-weight-gradient">One entry of the weight gradient</a></li>
  <li><a href="#backward-pass-in-node-form-input-to-relu" id="toc-backward-pass-in-node-form-input-to-relu" class="nav-link" data-scroll-target="#backward-pass-in-node-form-input-to-relu">Backward pass in node form: input to ReLU</a></li>
  <li><a href="#backward-pass-in-node-form-output-layer-to-cost" id="toc-backward-pass-in-node-form-output-layer-to-cost" class="nav-link" data-scroll-target="#backward-pass-in-node-form-output-layer-to-cost">Backward pass in node form: output layer to cost</a></li>
  <li><a href="#exploding-and-vanishing-gradients" id="toc-exploding-and-vanishing-gradients" class="nav-link" data-scroll-target="#exploding-and-vanishing-gradients">Exploding and vanishing gradients</a></li>
  <li><a href="#gradient-magnitude-by-layer-measured" id="toc-gradient-magnitude-by-layer-measured" class="nav-link" data-scroll-target="#gradient-magnitude-by-layer-measured">Gradient magnitude by layer, measured</a></li>
  <li><a href="#causes-and-cures" id="toc-causes-and-cures" class="nav-link" data-scroll-target="#causes-and-cures">Causes and cures</a></li>
  </ul></li>
  <li><a href="#pytorch-autograd" id="toc-pytorch-autograd" class="nav-link" data-scroll-target="#pytorch-autograd">PyTorch autograd</a>
  <ul class="collapse">
  <li><a href="#what-a-tensor-is" id="toc-what-a-tensor-is" class="nav-link" data-scroll-target="#what-a-tensor-is">What a tensor is</a></li>
  <li><a href="#tensors-and-numpy-arrays" id="toc-tensors-and-numpy-arrays" class="nav-link" data-scroll-target="#tensors-and-numpy-arrays">Tensors and NumPy arrays</a></li>
  <li><a href="#dtype-and-device" id="toc-dtype-and-device" class="nav-link" data-scroll-target="#dtype-and-device">dtype and device</a></li>
  <li><a href="#requires_grad-and-the-tape" id="toc-requires_grad-and-the-tape" class="nav-link" data-scroll-target="#requires_grad-and-the-tape"><code>requires_grad</code> and the tape</a></li>
  <li><a href="#gradients-accumulate" id="toc-gradients-accumulate" class="nav-link" data-scroll-target="#gradients-accumulate">Gradients accumulate</a></li>
  <li><a href="#zero_grad-and-gradient-accumulation" id="toc-zero_grad-and-gradient-accumulation" class="nav-link" data-scroll-target="#zero_grad-and-gradient-accumulation"><code>zero_grad</code> and gradient accumulation</a></li>
  <li><a href="#nn.linear-is-lab-2s-layer" id="toc-nn.linear-is-lab-2s-layer" class="nav-link" data-scroll-target="#nn.linear-is-lab-2s-layer"><code>nn.Linear</code> is Lab 2’s layer</a></li>
  <li><a href="#nn.module" id="toc-nn.module" class="nav-link" data-scroll-target="#nn.module"><code>nn.Module</code></a></li>
  <li><a href="#modelx-versus-model.forwardx" id="toc-modelx-versus-model.forwardx" class="nav-link" data-scroll-target="#modelx-versus-model.forwardx"><code>model(x)</code> versus <code>model.forward(x)</code></a></li>
  <li><a href="#loss-functions-in-pytorch" id="toc-loss-functions-in-pytorch" class="nav-link" data-scroll-target="#loss-functions-in-pytorch">Loss functions in PyTorch</a></li>
  <li><a href="#logits-and-crossentropyloss" id="toc-logits-and-crossentropyloss" class="nav-link" data-scroll-target="#logits-and-crossentropyloss">Logits and <code>CrossEntropyLoss</code></a></li>
  </ul></li>
  <li><a href="#the-first-training-loop" id="toc-the-first-training-loop" class="nav-link" data-scroll-target="#the-first-training-loop">The first training loop</a>
  <ul class="collapse">
  <li><a href="#full-batch-mini-batch-stochastic" id="toc-full-batch-mini-batch-stochastic" class="nav-link" data-scroll-target="#full-batch-mini-batch-stochastic">Full batch, mini-batch, stochastic</a></li>
  <li><a href="#the-loop" id="toc-the-loop" class="nav-link" data-scroll-target="#the-loop">The loop</a></li>
  <li><a href="#lab-2s-network-trained-with-autograd" id="toc-lab-2s-network-trained-with-autograd" class="nav-link" data-scroll-target="#lab-2s-network-trained-with-autograd">Lab 2’s network, trained with autograd</a></li>
  <li><a href="#loss-curves-autograd-and-finite-differences" id="toc-loss-curves-autograd-and-finite-differences" class="nav-link" data-scroll-target="#loss-curves-autograd-and-finite-differences">Loss curves, autograd and finite differences</a></li>
  <li><a href="#finite-differences-and-autograd-side-by-side" id="toc-finite-differences-and-autograd-side-by-side" class="nav-link" data-scroll-target="#finite-differences-and-autograd-side-by-side">Finite differences and autograd, side by side</a></li>
  <li><a href="#scope-today-and-week-4" id="toc-scope-today-and-week-4" class="nav-link" data-scroll-target="#scope-today-and-week-4">Scope: today and Week 4</a></li>
  </ul></li>
  <li><a href="#closing" id="toc-closing" class="nav-link" data-scroll-target="#closing">Closing</a>
  <ul class="collapse">
  <li><a href="#lab-3" id="toc-lab-3" class="nav-link" data-scroll-target="#lab-3">Lab 3</a></li>
  <li><a href="#quiz-3-study-guide" id="toc-quiz-3-study-guide" class="nav-link" data-scroll-target="#quiz-3-study-guide">Quiz 3 study guide</a></li>
  <li><a href="#supplemental-content" id="toc-supplemental-content" class="nav-link" data-scroll-target="#supplemental-content">Supplemental content</a></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a></li>
  <li><a href="#quiz-2" id="toc-quiz-2" class="nav-link" data-scroll-target="#quiz-2">Quiz 2</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="presentation.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DSAN 6600 Week 03: Backpropagation and PyTorch</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Ben Houghton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="backpropagation-and-pytorch" class="level1">
<h1>Backpropagation and PyTorch</h1>
<ul>
<li>Thursdays, 3:30–6:00 PM · ICC 103</li>
<li>Week 3 of 14</li>
<li><strong>Quiz 2 is at the end of class today</strong>, covering Week 2 and Lab 2</li>
</ul>
<section id="agenda" class="level2">
<h2 class="anchored" data-anchor-id="agenda">Agenda</h2>
<ol type="1">
<li><strong>Why backpropagation exists</strong>: what Lab 2 cost, priced at scale</li>
<li><strong>The chain rule</strong>, in the form deep learning actually uses it</li>
<li><strong>Computational graphs</strong>: the forward pass, recorded</li>
<li><strong>Reverse-mode autodiff</strong>, worked by hand and then in PyTorch</li>
<li><strong>From a scalar to a layer</strong>, and why nobody stores a Jacobian</li>
<li><strong>PyTorch autograd</strong>: tensors, <code>.backward()</code>, <code>nn.Module</code></li>
<li><strong>The first training loop</strong></li>
</ol>
<p>Spotlights first. Quiz 2 in the last 20 minutes.</p>
</section>
<section id="lab-2-recap" class="level2">
<h2 class="anchored" data-anchor-id="lab-2-recap">Lab 2 recap</h2>
<p>You trained a <span class="math inline">1 \to 16 \to 1</span> tanh network on a noisy sine with <strong>no backpropagation</strong>. Finite differences, 400 steps of gradient descent:</p>
<table class="table">
<tbody>
<tr class="odd">
<td>Parameters</td>
<td>49</td>
</tr>
<tr class="even">
<td>Forward passes per gradient</td>
<td>50</td>
</tr>
<tr class="odd">
<td>Total forward passes</td>
<td>20,001</td>
</tr>
<tr class="even">
<td>Cost, start to end</td>
<td>1.3256 → 0.0190</td>
</tr>
<tr class="odd">
<td>A straight line, for comparison</td>
<td>0.1736</td>
</tr>
<tr class="even">
<td>The noise floor</td>
<td>0.0113</td>
</tr>
</tbody>
</table>
<p>The fit was real. It beat a straight line by an order of magnitude and landed near the noise floor. No library on earth trains a network this way.</p>
</section>
<section id="cost-of-one-gradient-step" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="cost-of-one-gradient-step">Cost of one gradient step</h2>
<p><a href="images/fig-cost-scaling.png" class="zoom" target="_blank"><img src="images/fig-cost-scaling.png" class="dw95 img-fluid" width="1150"></a></p>
<p>Left is measured on this laptop: the gap widens from 150x to over 1,600x across that range. Right is not measured, because it does not need to be. Finite differences take <strong>exactly</strong> <span class="math inline">n+1</span> forward passes for <span class="math inline">n</span> parameters. At one millisecond each, ResNet-50 needs 7 hours and GPT-3 needs 5.5 years, for <strong>one</strong> step of gradient descent.</p>
</section>
<section id="limits-of-analytical-solutions" class="level2">
<h2 class="anchored" data-anchor-id="limits-of-analytical-solutions">Limits of analytical solutions</h2>
<p>Week 1 found the least-squares solution in closed form. That does not generalize:</p>
<ol type="1">
<li><strong>Scale.</strong> 175 billion parameters is 175 billion coupled equations</li>
<li><strong>Nonlinearity.</strong> <span class="math inline">\tanh</span>, ReLU and softmax compose into transcendental equations with no algebraic solution</li>
<li><strong>Non-convexity.</strong> Many local minima and many saddle points, so “the” solution is not a well-posed request</li>
<li><strong>No closed form.</strong> Setting the gradient to zero gives you a system nobody can solve symbolically</li>
</ol>
<p>So we iterate. Iterating needs a gradient at the current parameters, and it needs one <strong>per step</strong>. The gradient is the thing that has to be cheap.</p>
</section>
<section id="three-ways-to-get-a-gradient" class="level2">
<h2 class="anchored" data-anchor-id="three-ways-to-get-a-gradient">Three ways to get a gradient</h2>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Exact?</th>
<th>Cost for <span class="math inline">n</span> parameters</th>
<th>Works on a network?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Symbolic, by hand</td>
<td>yes</td>
<td>your whole afternoon, once</td>
<td>only for tiny ones</td>
</tr>
<tr class="even">
<td>Finite differences</td>
<td><strong>no</strong>, approximate</td>
<td><span class="math inline">n+1</span> forward passes</td>
<td>yes, and too slowly</td>
</tr>
<tr class="odd">
<td>Reverse-mode autodiff</td>
<td><strong>yes</strong>, to floating point</td>
<td>1 forward + 1 backward</td>
<td>this is what we use</td>
</tr>
</tbody>
</table>
<p>Finite differences are worse on both axes. They are approximate <strong>and</strong> slow. The step size <span class="math inline">\varepsilon</span> has to be small enough to be accurate and large enough to survive floating-point cancellation, and those two demands fight.</p>
<p>Autodiff has no <span class="math inline">\varepsilon</span>. It is exact arithmetic on the derivative rules you already know.</p>
</section>
<section id="automatic-differentiation" class="level2">
<h2 class="anchored" data-anchor-id="automatic-differentiation">Automatic differentiation</h2>
<p><strong>Automatic differentiation</strong> computes partial derivatives of an arbitrary computer program by applying the chain rule to every elementary operation the program ran.</p>
<p>It works because every line of a forward pass is one of a short list:</p>
<ul>
<li><strong>Operations:</strong> add, subtract, multiply, divide</li>
<li><strong>Functions:</strong> <span class="math inline">\exp</span>, <span class="math inline">\log</span>, <span class="math inline">\sin</span>, <span class="math inline">\tanh</span>, <span class="math inline">\max</span></li>
</ul>
<p>Each has a derivative you learned in Calc I. Autodiff records which ones ran, in what order, on what values, and then walks that record backward.</p>
<p>PyTorch, TensorFlow and JAX are all autodiff engines with a neural-network library attached.</p>
</section>
<section id="backpropagation" class="level2">
<h2 class="anchored" data-anchor-id="backpropagation">Backpropagation</h2>
<p><strong>Backpropagation</strong> is reverse-mode autodiff applied to a neural network. It answers, for every weight and every bias in the model:</p>
<p><span class="math display">\frac{\partial \mathcal{L}}{\partial w} = \; ? \qquad
  \frac{\partial \mathcal{L}}{\partial b} = \; ?</span></p>
<p>after <strong>one</strong> forward pass and <strong>one</strong> backward pass, regardless of how many parameters there are.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The name is narrower than the idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Autodiff is the general procedure and predates deep learning. Backpropagation is its application to networks. In practice people use the words interchangeably, and you should know which one is the superset.</p>
</div>
</div>
</section>
<section id="loss-and-cost" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="loss-and-cost">Loss and cost</h2>
<p>These get used interchangeably. They are not the same thing, and today the distinction matters because the backward pass starts at one of them.</p>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>Loss</strong> <span class="math inline">\ell_i</span>: the error on a <strong>single</strong> example.</p>
<p><span class="math display">\ell_i = (y_i - \hat{y}_i)^2</span></p>
<p><span class="math display">\ell_i = -\big(y_i \log \hat{y}_i + (1-y_i)\log(1-\hat{y}_i)\big)</span></p>
</div><div class="column" style="width:48%;">
<p><strong>Cost</strong> <span class="math inline">\mathcal{L}</span>: the reduction of those losses over a batch of <span class="math inline">N</span>.</p>
<p><span class="math display">\mathcal{L} = \frac{1}{N}\sum_{i=1}^{N} \ell_i</span></p>
<p>The “mean” in <em>mean</em> squared error is what turns a loss into a cost.</p>
</div>
</div>
<p>The optimizer only ever sees a <strong>scalar</strong>. <code>loss.backward()</code> in PyTorch is called on the cost, and that scalar is why reverse mode is the right choice.</p>
</section>
</section>
<section id="the-chain-rule" class="level1">
<h1>The chain rule</h1>
<ul>
<li>One rule, applied a few million times</li>
<li>The multivariable version is the one that matters</li>
</ul>
<section id="chain-rule-for-composite-functions" class="level2">
<h2 class="anchored" data-anchor-id="chain-rule-for-composite-functions">Chain rule for composite functions</h2>
<p>A network is a composition of simple functions, so the chain rule is the entire mathematical content of backpropagation. There is no limit to the depth of the composition:</p>
<p><span class="math display">\frac{d}{dx}\big[f(g(h(x)))\big]
  = f'(g(h(x)))\; g'(h(x))\; h'(x)</span></p>
<p>Take <span class="math inline">f(x) = e^x</span>, <span class="math inline">g(x) = \sin x</span>, <span class="math inline">h(x) = x^2</span>, so <span class="math inline">f(g(h(x))) = e^{\sin(x^2)}</span>:</p>
<p><span class="math display">\frac{d}{dx}\big[e^{\sin(x^2)}\big]
  = e^{\sin(x^2)} \cdot \frac{d}{dx}\big[\sin(x^2)\big]
  = e^{\sin(x^2)} \cos(x^2) \cdot \frac{d}{dx}\big[x^2\big]
  = 2x\, e^{\sin(x^2)} \cos(x^2)</span></p>
<p>Read it right to left and you have just done a backward pass on a three-node graph.</p>
</section>
<section id="multivariable-chain-rule" class="level2">
<h2 class="anchored" data-anchor-id="multivariable-chain-rule">Multivariable chain rule</h2>
<p>Networks have thousands to billions of parameters, and a parameter early in the network reaches the cost through <strong>many</strong> downstream paths. The single-variable rule is not enough.</p>
<p>Let <span class="math inline">z = f(x, y)</span> where <span class="math inline">x = g(w, b)</span> and <span class="math inline">y = h(w, b)</span>. Then</p>
<p><span class="math display">\frac{\partial z}{\partial w}
  = \frac{\partial z}{\partial x}\frac{\partial x}{\partial w}
  + \frac{\partial z}{\partial y}\frac{\partial y}{\partial w}</span></p>
<p><span class="math display">\frac{\partial z}{\partial b}
  = \frac{\partial z}{\partial x}\frac{\partial x}{\partial b}
  + \frac{\partial z}{\partial y}\frac{\partial y}{\partial b}</span></p>
<p>Think of <span class="math inline">x</span> and <span class="math inline">y</span> as two hidden units that both feed a unit downstream. <span class="math inline">w</span> affects the result through both, so <strong>both paths are counted, and they add.</strong></p>
</section>
<section id="multivariable-chain-rule-worked" class="level2">
<h2 class="anchored" data-anchor-id="multivariable-chain-rule-worked">Multivariable chain rule, worked</h2>
<p>Let <span class="math inline">z = e^{xy}</span> where <span class="math inline">x = 2w + b</span> and <span class="math inline">y = \sin w + \cos 2b</span>.</p>
<p>The local derivatives are <span class="math inline">\partial z/\partial x = y e^{xy}</span>, <span class="math inline">\partial z/\partial y = x e^{xy}</span>, <span class="math inline">\partial x/\partial w = 2</span>, <span class="math inline">\partial y/\partial w = \cos w</span>.</p>
<p><span class="math display">\frac{\partial z}{\partial w}
  = \underbrace{y e^{xy}}_{\text{path through } x} \cdot 2
  + \underbrace{x e^{xy}}_{\text{path through } y} \cdot \cos w</span></p>
<p><span class="math display">\frac{\partial z}{\partial b}
  = y e^{xy} \cdot 1
  + x e^{xy} \cdot (-2 \sin 2b)</span></p>
<p>Nothing here is hard. It is bookkeeping. Autodiff exists because the bookkeeping does not stay manageable past about six nodes.</p>
</section>
<section id="chain-rule-along-a-network-path" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="chain-rule-along-a-network-path">Chain rule along a network path</h2>
<p><a href="images/2024-03-12-17-07-44.png" class="zoom" target="_blank"><img src="images/2024-03-12-17-07-44.png" class="dw70 img-fluid" width="735"></a></p>
<p>The bottom rows are the part to study: each factor written once as a <strong>formula</strong> and once as its <strong>value</strong>, with <span class="math inline">\partial L / \partial w</span> the product of the row, <span class="math inline">(1)(2)(1)(0.187)(-16) \approx -6</span>.</p>
</section>
<section id="generalized-chain-rule" class="level2">
<h2 class="anchored" data-anchor-id="generalized-chain-rule">Generalized chain rule</h2>
<p>The statement with no ceiling on the number of functions or variables, which is the shape a real network takes.</p>
<p>Let <span class="math inline">z = f(x_1, x_2, \ldots, x_m)</span> be differentiable in <span class="math inline">m</span> variables, and let each <span class="math inline">x_i = x_i(t_1, t_2, \ldots, t_n)</span> be differentiable in <span class="math inline">n</span> variables. Then for any <span class="math inline">j</span>:</p>
<p><span class="math display">\frac{\partial z}{\partial t_j}
  = \frac{\partial z}{\partial x_1}\frac{\partial x_1}{\partial t_j}
  + \frac{\partial z}{\partial x_2}\frac{\partial x_2}{\partial t_j}
  + \cdots
  + \frac{\partial z}{\partial x_m}\frac{\partial x_m}{\partial t_j}</span></p>
<p>Read <span class="math inline">z</span> as the cost, <span class="math inline">t_j</span> as one weight, and the <span class="math inline">x_i</span> as every activation that weight touches. That sum is the backward pass.</p>
</section>
<section id="gradient-notation" class="level2">
<h2 class="anchored" data-anchor-id="gradient-notation">Gradient notation</h2>
<p>The <strong>gradient</strong> of a function collects all of its partial derivatives into one object, written <span class="math inline">\nabla f</span>.</p>
<p>For <span class="math inline">z = f(x_1, \ldots, x_m)</span>:</p>
<p><span class="math display">\nabla_{\mathbf{x}} f =
  \begin{bmatrix}
  \partial f / \partial x_1 \\
  \partial f / \partial x_2 \\
  \vdots \\
  \partial f / \partial x_m
  \end{bmatrix}</span></p>
<p>In deep learning we want the gradient of the cost with respect to the <strong>parameters</strong>, written <span class="math inline">\nabla_{\theta} \mathcal{L}</span>, where <span class="math inline">\theta</span> is the whole parameter set. Lab 2 called that flat vector <code>theta</code> and it had 49 entries.</p>
</section>
<section id="gradient-of-the-cost-with-respect-to-a-weight-matrix" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="gradient-of-the-cost-with-respect-to-a-weight-matrix">Gradient of the cost with respect to a weight matrix</h2>
<p><a href="images/fig-gradient-shapes.png" class="zoom" target="_blank"><img src="images/fig-gradient-shapes.png" class="dw70 img-fluid" width="1050"></a></p>
<p>For <span class="math inline">\mathbf{W}</span> of shape <span class="math inline">(m, n)</span>, the gradient <span class="math inline">\nabla_{\mathbf{W}} \mathcal{L}</span> is also <span class="math inline">(m, n)</span>:</p>
<p><span class="math display">\nabla_{\mathbf{W}} \mathcal{L} =
  \begin{bmatrix}
  \partial \mathcal{L}/\partial w_{1,1} &amp; \cdots &amp; \partial \mathcal{L}/\partial w_{1,n} \\
  \vdots &amp; \ddots &amp; \vdots \\
  \partial \mathcal{L}/\partial w_{m,1} &amp; \cdots &amp; \partial \mathcal{L}/\partial w_{m,n}
  \end{bmatrix}</span></p>
<p>This is worth pausing on, because it is what makes <code>theta = theta - lr * grad</code> a legal line of code.</p>
</section>
</section>
<section id="computational-graphs" class="level1">
<h1>Computational graphs</h1>
<ul>
<li>Nodes are values, edges are operations</li>
<li>The forward pass builds the graph; the backward pass walks it</li>
</ul>
<section id="computational-graphs-as-directed-acyclic-graphs" class="level2">
<h2 class="anchored" data-anchor-id="computational-graphs-as-directed-acyclic-graphs">Computational graphs as directed acyclic graphs</h2>
<p><a href="images/computational-graph-sigmoid.png" class="zoom" target="_blank"><img src="images/computational-graph-sigmoid.png" class="dw70 img-fluid" width="735"></a></p>
<p>A network’s computational graph is a <strong>directed acyclic graph</strong>:</p>
<ul>
<li>Each node is a value that some operation produced</li>
<li>Each edge is an operation with a known derivative</li>
<li><strong>Acyclic</strong> means no cycles, which is what makes a single backward sweep well-defined</li>
<li>Nodes can be as primitive or as coarse as you like. <span class="math inline">\sigma(z)</span> can be four nodes or one</li>
</ul>
</section>
<section id="graph-of-an-expression" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="graph-of-an-expression">Graph of an expression</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p><a href="images/computational-graph-2.png" class="zoom" target="_blank"><img src="images/computational-graph-2.png" class="dw40 img-fluid" width="420"></a></p>
</div><div class="column" style="width:58%;">
<p>Before any numbers, the graph is just the structure of the expression. Reading it left to right: <span class="math inline">w</span> and <span class="math inline">x</span> meet at a multiply, the result meets <span class="math inline">v</span> at an add, and that meets <span class="math inline">-1</span> at a multiply.</p>
<p>Nothing here is specific to neural networks. Any expression built from differentiable pieces has a graph like this, which is why autodiff works on ordinary Python code and not only on models.</p>
</div>
</div>
</section>
<section id="forward-pass-on-a-graph" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="forward-pass-on-a-graph">Forward pass on a graph</h2>
<p><a href="images/kahns-algorithm.png" class="zoom" target="_blank"><img src="images/kahns-algorithm.png" class="dw68 img-fluid" width="714"></a></p>
<p>Three inputs and four operations. <span class="math inline">A \times B = C</span>, then <span class="math inline">D + C = F</span>, then <span class="math inline">F + A = G</span>, then <span class="math inline">G \times B = H</span>. The <strong>green</strong> numbers are the forward values; ignore the orange ones for now.</p>
<p>The forward pass does two things, and the second is the one people forget: it computes the values, <strong>and it records the operations and their inputs.</strong> That record is what the backward pass consumes, and it is why a forward pass under <code>torch.no_grad()</code> uses less memory.</p>
</section>
<section id="the-chain-rule-on-a-graph" class="level2">
<h2 class="anchored" data-anchor-id="the-chain-rule-on-a-graph">The chain rule on a graph</h2>
<p>The rule becomes local. At a node <span class="math inline">v</span> with parent <span class="math inline">u</span>:</p>
<p><span class="math display">\frac{\partial \mathcal{L}}{\partial u}
  = \underbrace{\frac{\partial \mathcal{L}}{\partial v}}_{\text{arrives from the right}}
    \cdot
    \underbrace{\frac{\partial v}{\partial u}}_{\text{one derivative, computed here}}</span></p>
<p>Each node needs to know exactly two things:</p>
<ol type="1">
<li>The gradient handed to it by its children, called the <strong>upstream gradient</strong></li>
<li>The derivative of its own operation, called the <strong>local gradient</strong></li>
</ol>
<p>Multiply them, pass the product to the parents. No node knows the size of the network it is in, and none of them needs to.</p>
</section>
<section id="local-derivatives-at-a-node" class="level2">
<h2 class="anchored" data-anchor-id="local-derivatives-at-a-node">Local derivatives at a node</h2>
<p><a href="images/backpropagation-node-types.png" class="zoom" target="_blank"><img src="images/backpropagation-node-types.png" class="dw90 img-fluid" width="945"></a></p>
<ul>
<li><strong>Add.</strong> <span class="math inline">z = a + b</span> has <span class="math inline">\partial z/\partial a = 1</span>, so the upstream gradient is <strong>copied</strong> to every input</li>
<li><strong>Multiply.</strong> <span class="math inline">z = ab</span> has <span class="math inline">\partial z/\partial a = b</span>, so the gradients <strong>swap</strong>: <span class="math inline">a</span> receives <span class="math inline">b \cdot \partial \mathcal{L}/\partial z</span></li>
<li><strong>Max.</strong> The gradient <strong>routes</strong> to whichever input won, and the other gets zero. ReLU is <span class="math inline">\max(0, z)</span>, so a negative pre-activation gets nothing</li>
</ul>
<p>Three rules cover most of a feedforward network. What does a <strong>min</strong> gate do? What about concatenation?</p>
</section>
<section id="backward-pass-on-a-graph" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="backward-pass-on-a-graph">Backward pass on a graph</h2>
<p><a href="images/kahns-algorithm.png" class="zoom" target="_blank"><img src="images/kahns-algorithm.png" class="dw68 img-fluid" width="714"></a></p>
<p>Same graph, now read the <strong>orange</strong> numbers, which are the gradients of <span class="math inline">H</span> with respect to each edge. They are produced right to left, starting from <span class="math inline">\partial H / \partial H = 1</span> at the output.</p>
<p>Every orange number is an upstream gradient times one local derivative. At <span class="math inline">H = G \times B</span>, for instance, <span class="math inline">G</span> receives <span class="math inline">1 \cdot B = 3</span> and <span class="math inline">B</span> receives <span class="math inline">1 \cdot G = 13</span>; the multiply node swaps its inputs.</p>
</section>
<section id="gradients-sum-over-paths" class="level2">
<h2 class="anchored" data-anchor-id="gradients-sum-over-paths">Gradients sum over paths</h2>
<p><a href="images/fig-fork-adds.png" class="zoom" target="_blank"><img src="images/fig-fork-adds.png" class="dw90 img-fluid" width="1050"></a></p>
<p><span class="math inline">A</span> reaches the output through <span class="math inline">C</span> and through <span class="math inline">G</span>, so the multivariable chain rule says count both and add: <span class="math inline">-9 + (-3) = -12</span>.</p>
<p>This is not a detail. <strong>It is the reason PyTorch accumulates into <code>.grad</code> instead of overwriting it,</strong> and therefore the reason you have to call <code>zero_grad()</code>. We will trip over that on purpose later.</p>
</section>
<section id="a-sigmoid-expanded-into-primitive-nodes" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="a-sigmoid-expanded-into-primitive-nodes">A sigmoid expanded into primitive nodes</h2>
<p><a href="images/backpropagation-single-node-sigmoid.png" class="zoom" target="_blank"><img src="images/backpropagation-single-node-sigmoid.png" class="dw68 img-fluid" width="725"></a></p>
<p>Written out, <span class="math inline">\sigma(z) = 1/(1 + e^{-z})</span> is four operations: negate, exponentiate, add one, take the reciprocal. Each is a node with its own local derivative, and backprop runs through all four.</p>
</section>
<section id="the-same-sigmoid-as-one-node" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-same-sigmoid-as-one-node">The same sigmoid as one node</h2>
<p><a href="images/backpropagation-single-node-sigmoid-simplified.png" class="zoom" target="_blank"><img src="images/backpropagation-single-node-sigmoid-simplified.png" class="dw60 img-fluid" width="725"></a></p>
<p>Because <span class="math inline">\sigma</span> has a derivative we know in closed form, those four nodes collapse into one:</p>
<p><span class="math display">\sigma'(z) = \sigma(z)\big(1 - \sigma(z)\big)</span></p>
<p>Same gradient, one node instead of four. The forward pass already computed <span class="math inline">\sigma(z)</span>, so the backward pass gets the local gradient for free from a value it has cached. This is the general pattern: autodiff engines trade memory for speed by keeping forward values around.</p>
</section>
<section id="execution-order-and-topological-sorting" class="level2">
<h2 class="anchored" data-anchor-id="execution-order-and-topological-sorting">Execution order and topological sorting</h2>
<p>A node cannot compute its gradient until <strong>every</strong> child has handed one over. Look at <span class="math inline">A</span> in the last figure: process it too early and you get <span class="math inline">-3</span> instead of <span class="math inline">-12</span>.</p>
<p>So the engine needs an ordering of the nodes where no node comes before something it depends on. That ordering is a <strong>topological sort</strong>, and it is not unique. For the graph below, both of these are valid:</p>
<p><span class="math display">[0, 1, 2, 3, 4, 5, 6, 7] \qquad [1, 0, 4, 3, 7, 6, 5, 2]</span></p>
<p><a href="images/topological-sort.png" class="zoom" target="_blank"><img src="images/topological-sort.png" class="dw40 img-fluid" width="420"></a></p>
</section>
<section id="kahns-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="kahns-algorithm">Kahn’s algorithm</h2>
<p>Repeatedly take a node with no remaining edges into it, emit it, and delete its edges. If edges are left over at the end, the graph had a cycle and there is no valid order.</p>
<p>We will walk the next eight slides one at a time. Watch two things:</p>
<ul>
<li>the <strong>queue</strong> on the left, which holds every node that is ready to be emitted</li>
<li>the <strong>topological order</strong> along the bottom, which fills left to right</li>
</ul>
<p>We start at the output node and work back toward the inputs, so the order this produces is exactly the order <code>loss.backward()</code> visits nodes in.</p>
</section>
<section id="topological-sort-the-starting-queue" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-the-starting-queue">Topological sort: the starting queue</h2>
<p><a href="images/kahns-algorithm-00.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-00.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-1" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-1">Topological sort: step 1</h2>
<p><a href="images/kahns-algorithm-01.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-01.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-2" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-2">Topological sort: step 2</h2>
<p><a href="images/kahns-algorithm-02.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-02.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-3" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-3">Topological sort: step 3</h2>
<p><a href="images/kahns-algorithm-03.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-03.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-4" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-4">Topological sort: step 4</h2>
<p><a href="images/kahns-algorithm-04.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-04.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-5" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-5">Topological sort: step 5</h2>
<p><a href="images/kahns-algorithm-05.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-05.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-step-6" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-step-6">Topological sort: step 6</h2>
<p><a href="images/kahns-algorithm-06.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-06.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-the-finished-order" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-the-finished-order">Topological sort: the finished order</h2>
<p><a href="images/kahns-algorithm-07.png" class="zoom" target="_blank"><img src="images/kahns-algorithm-07.png" class="dw85 img-fluid" width="880"></a></p>
</section>
<section id="topological-sort-animated" class="level2">
<h2 class="anchored" data-anchor-id="topological-sort-animated">Topological sort, animated</h2>
<p><a href="images/kahns-algorithm.gif" class="zoom" target="_blank"><img src="images/kahns-algorithm.gif" class="dw85 img-fluid" width="880"></a></p>
<p>The same eight steps, run end to end.</p>
</section>
<section id="kahns-algorithm-in-pseudocode" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="kahns-algorithm-in-pseudocode">Kahn’s algorithm in pseudocode</h2>
<pre><code>L &lt;- empty list that will hold the sorted elements
S &lt;- set of all nodes with no incoming edge

while S is not empty:
    remove a node n from S
    add n to L
    for each node m with an edge e from n to m:
        remove edge e from the graph
        if m has no other incoming edges:
            insert m into S

if the graph still has edges:
    return error          # at least one cycle
else:
    return L              # a topologically sorted order</code></pre>
<p>You will not implement this. You should know that it exists, that it is why the graph has to be acyclic, and that a recurrent network gets around the “acyclic” requirement by unrolling in time, which is Week 9.</p>
</section>
</section>
<section id="reverse-mode-autodiff" class="level1">
<h1>Reverse-mode autodiff</h1>
<ul>
<li>One scalar example, worked by hand</li>
<li>Then the identical example in PyTorch, so the API is not a mystery</li>
</ul>
<section id="scalar-regression-example" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="scalar-regression-example">Scalar regression example</h2>
<p>Take <span class="math inline">x = 3</span>, <span class="math inline">w = 2</span>, <span class="math inline">b = 4</span>, a ReLU, and squared error against <span class="math inline">y = 12</span>:</p>
<p><span class="math display">z_1 = wx = 6, \quad
  z_2 = z_1 + b = 10, \quad
  a = \mathrm{ReLU}(z_2) = 10, \quad
  \ell = (a - 12)^2 = 4</span></p>
<p>Four numbers and four recorded operations. This is a single neuron, which is exactly the object Week 2 built. Now walk it backward, starting from <span class="math inline">\partial \ell / \partial \ell = 1</span>:</p>
<p><span class="math display">\frac{\partial \ell}{\partial a} = 2(a - y) = -4,
  \quad
  \frac{\partial \ell}{\partial z_2} = -4 \cdot \mathbb{1}[z_2 &gt; 0] = -4,
  \quad
  \frac{\partial \ell}{\partial w} = -4x = -12,
  \quad
  \frac{\partial \ell}{\partial b} = -4</span></p>
<p>ReLU passed the gradient through because <span class="math inline">z_2 &gt; 0</span>. Had <span class="math inline">z_2</span> been negative, every gradient to its left would be exactly zero and this neuron would learn nothing from this example.</p>
</section>
<section id="scalar-regression-graph-both-passes" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="scalar-regression-graph-both-passes">Scalar regression graph, both passes</h2>
<p><a href="images/scalar-backpropagation-regression.png" class="zoom" target="_blank"><img src="images/scalar-backpropagation-regression.png" class="dw90 img-fluid" width="945"></a></p>
<p>Green is the forward pass, orange the backward pass, and every node carries the chain rule that produced its number. ReLU and MSE, with their derivatives, are in the top right.</p>
</section>
<section id="the-same-graph-in-pytorch" class="level2">
<h2 class="anchored" data-anchor-id="the-same-graph-in-pytorch">The same graph in PyTorch</h2>
<p><code>requires_grad=True</code> tells autograd to record. <code>retain_grad()</code> asks it to keep the gradient at an intermediate node, which it normally discards.</p>
<div id="6c522e43" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="fl">3.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> torch.tensor([<span class="fl">4.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> torch.tensor([<span class="fl">12.0</span>])</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>z1 <span class="op">=</span> w <span class="op">*</span> x<span class="op">;</span>                z1.retain_grad()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>z2 <span class="op">=</span> z1 <span class="op">+</span> b<span class="op">;</span>               z2.retain_grad()</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> torch.relu(z2)<span class="op">;</span>        a.retain_grad()</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> nn.MSELoss()(a, y)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>loss.backward()</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"forward    z1=</span><span class="sc">{</span>z1<span class="sc">.</span>item()<span class="sc">:5.1f}</span><span class="ss">  z2=</span><span class="sc">{</span>z2<span class="sc">.</span>item()<span class="sc">:5.1f}</span><span class="ss">  "</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"a=</span><span class="sc">{</span>a<span class="sc">.</span>item()<span class="sc">:5.1f}</span><span class="ss">  loss=</span><span class="sc">{</span>loss<span class="sc">.</span>item()<span class="sc">:5.1f}</span><span class="ss">"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, t <span class="kw">in</span> [(<span class="st">"a"</span>, a), (<span class="st">"z2"</span>, z2), (<span class="st">"z1"</span>, z1), (<span class="st">"b"</span>, b), (<span class="st">"w"</span>, w), (<span class="st">"x"</span>, x)]:</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  dloss/d</span><span class="sc">{</span>name<span class="sc">:&lt;2}</span><span class="ss"> </span><span class="sc">{</span>t<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.1f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>forward    z1=  6.0  z2= 10.0  a= 10.0  loss=  4.0

  dloss/da     -4.0
  dloss/dz2    -4.0
  dloss/dz1    -4.0
  dloss/db     -4.0
  dloss/dw    -12.0
  dloss/dx     -8.0</code></pre>
</div>
</div>
</section>
<section id="reading-gradients-out-of-.grad" class="level2">
<h2 class="anchored" data-anchor-id="reading-gradients-out-of-.grad">Reading gradients out of <code>.grad</code></h2>
<p>It approximated nothing. It ran the chain rule you just ran, on the graph it recorded during the forward pass, and every number matches the hand derivation.</p>
<ul>
<li><code>w.grad = -12</code> is <span class="math inline">\partial \ell / \partial w</span>. SGD will use it</li>
<li><code>b.grad = -4</code> is <span class="math inline">\partial \ell / \partial b</span>. SGD will use it</li>
<li><code>x.grad = -8</code> is <span class="math inline">\partial \ell / \partial x</span>. It got computed on the way past and we throw it away, because the input is not a parameter</li>
</ul>
<p>Finite differences would have needed one forward pass per scalar. This needed one forward and one backward, for all of them at once.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Where <span class="math inline">\partial \ell / \partial x</span> stops being garbage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Adversarial examples, saliency maps and style transfer all optimize the <strong>input</strong> while holding the weights fixed. Same machinery, different variable.</p>
</div>
</div>
</section>
<section id="scalar-classification-graph" class="level2">
<h2 class="anchored" data-anchor-id="scalar-classification-graph">Scalar classification graph</h2>
<p><a href="images/scalar-backpropagation-classification-simplified.png" class="zoom" target="_blank"><img src="images/scalar-backpropagation-classification-simplified.png" class="dw68 img-fluid" width="714"></a></p>
<p>Same shape, different head: sigmoid instead of ReLU, binary cross-entropy instead of squared error. Take <span class="math inline">x = 2</span>, <span class="math inline">w = 0.5</span>, <span class="math inline">b = -2.1</span>, and <span class="math inline">y = 0</span>.</p>
<p><span class="math display">z_2 = -1.1, \qquad
  \hat{y} = \sigma(z_2) = 0.2497, \qquad
  \ell = -\log(1 - \hat{y}) = 0.2873</span></p>
</section>
<section id="scalar-classification-graph-both-passes" class="level2">
<h2 class="anchored" data-anchor-id="scalar-classification-graph-both-passes">Scalar classification graph, both passes</h2>
<p><a href="images/scalar-backpropagation-classification.png" class="zoom" target="_blank"><img src="images/scalar-backpropagation-classification.png" class="dw95 img-fluid" width="1050"></a></p>
<p>The same expansion as the regression case, now with a sigmoid and binary cross entropy. The chain is longer because the loss is written out as <span class="math inline">\hat{y} = 1/a_3</span> rather than folded into one node.</p>
</section>
<section id="derivative-of-binary-cross-entropy" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="derivative-of-binary-cross-entropy">Derivative of binary cross-entropy</h2>
<p><a href="images/2024-03-12-20-12-43.png" class="zoom" target="_blank"><img src="images/2024-03-12-20-12-43.png" class="dw68 img-fluid" width="714"></a></p>
<p>Worth keeping for the two class cases at the middle of the slide: the same formula gives <span class="math inline">+1.33</span> when <span class="math inline">y = 0</span> and <span class="math inline">-4</span> when <span class="math inline">y = 1</span>, from the identical prediction <span class="math inline">\hat{y} = 0.25</span>. The sign is what tells the weight which way to move.</p>
</section>
<section id="classification-in-pytorch" class="level2">
<h2 class="anchored" data-anchor-id="classification-in-pytorch">Classification in PyTorch</h2>
<p>Watch <span class="math inline">\partial \ell / \partial z_2</span> in the output and compare it to <span class="math inline">\hat{y} - y</span>.</p>
<div id="7aec7678" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.tensor([<span class="fl">0.5</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> torch.tensor([<span class="op">-</span><span class="fl">2.1</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> torch.tensor([<span class="fl">0.0</span>])</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>z1 <span class="op">=</span> w <span class="op">*</span> x<span class="op">;</span>                    z1.retain_grad()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>z2 <span class="op">=</span> z1 <span class="op">+</span> b<span class="op">;</span>                   z2.retain_grad()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>y_hat <span class="op">=</span> torch.sigmoid(z2)<span class="op">;</span>     y_hat.retain_grad()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> nn.BCELoss()(y_hat, y)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>loss.backward()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z2 = </span><span class="sc">{</span>z2<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">   y_hat = </span><span class="sc">{</span>y_hat<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"loss = </span><span class="sc">{</span>loss<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  dloss/dz2  </span><span class="sc">{</span>z2<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  y_hat - y  </span><span class="sc">{</span>(y_hat <span class="op">-</span> y)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">   &lt;- the same number"</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, t <span class="kw">in</span> [(<span class="st">"w"</span>, w), (<span class="st">"b"</span>, b), (<span class="st">"x"</span>, x)]:</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  dloss/d</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">   </span><span class="sc">{</span>t<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>z2 = -1.1000   y_hat = 0.2497   loss = 0.2873

  dloss/dz2  0.2497
  y_hat - y  0.2497   &lt;- the same number

  dloss/dw    0.4995
  dloss/db    0.2497
  dloss/dx    0.1249</code></pre>
</div>
</div>
</section>
<section id="gradient-of-cross-entropy-with-a-sigmoid-output" class="level2">
<h2 class="anchored" data-anchor-id="gradient-of-cross-entropy-with-a-sigmoid-output">Gradient of cross-entropy with a sigmoid output</h2>
<p>The two ugly derivatives cancel. For binary cross-entropy on a sigmoid output:</p>
<p><span class="math display">\frac{\partial \ell}{\partial \hat{y}}
  = \frac{\hat{y} - y}{\hat{y}(1 - \hat{y})},
  \qquad
  \frac{\partial \hat{y}}{\partial z}
  = \hat{y}(1 - \hat{y})
  \quad\Longrightarrow\quad
  \frac{\partial \ell}{\partial z} = \hat{y} - y</span></p>
<p>The gradient entering the linear part is just <strong>the prediction minus the truth</strong>. Squared error on a linear output gives the same form. It is why these loss and activation pairings are the defaults, and it is the same algebra Week 1 met in logistic regression.</p>
<p>This is also why <code>nn.CrossEntropyLoss</code> takes logits and applies <span class="math inline">\log\mathrm{softmax}</span> itself: doing them together is both simpler and numerically stabler than doing them apart.</p>
</section>
<section id="forward-mode-and-reverse-mode" class="level2">
<h2 class="anchored" data-anchor-id="forward-mode-and-reverse-mode">Forward mode and reverse mode</h2>
<p><a href="images/fig-forward-vs-reverse.png" class="zoom" target="_blank"><img src="images/fig-forward-vs-reverse.png" class="dw85 img-fluid" width="1100"></a></p>
<p>Autodiff has two directions, and the choice is not stylistic.</p>
<ul>
<li><strong>Forward mode</strong> propagates a derivative from one input forward. To get all <span class="math inline">n</span> parameter gradients you sweep <span class="math inline">n</span> times</li>
<li><strong>Reverse mode</strong> propagates a derivative from one output backward. One sweep gives you every input gradient</li>
</ul>
</section>
<section id="choosing-forward-or-reverse-mode" class="level2">
<h2 class="anchored" data-anchor-id="choosing-forward-or-reverse-mode">Choosing forward or reverse mode</h2>
<p>The cost of each mode is set by the <strong>shape</strong> of the function, not by the architecture:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Sweeps needed</th>
<th>Good when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forward mode</td>
<td>one per <strong>input</strong></td>
<td>few inputs, many outputs</td>
</tr>
<tr class="even">
<td>Reverse mode</td>
<td>one per <strong>output</strong></td>
<td>many inputs, <strong>one</strong> output</td>
</tr>
</tbody>
</table>
<p>A neural network maps millions of parameters to a <strong>single scalar cost</strong>. That is the best possible case for reverse mode and the worst possible case for forward mode.</p>
<p>If the cost were a vector of a million values, forward mode would win and deep learning would look very different. It is a scalar because we chose to reduce the batch to a mean, which brings us back to loss versus cost.</p>
</section>
</section>
<section id="from-a-scalar-to-a-layer" class="level1">
<h1>From a scalar to a layer</h1>
<ul>
<li>The same three rules, now on matrices</li>
<li>What gets stored, and what does not</li>
</ul>
<section id="backward-pass-of-a-linear-layer" class="level2">
<h2 class="anchored" data-anchor-id="backward-pass-of-a-linear-layer">Backward pass of a linear layer</h2>
<p>Week 2: a layer with <span class="math inline">\mathbf{W}</span> of shape <code>(units, inputs)</code> computes <span class="math inline">\mathbf{z} = \mathbf{W}\mathbf{x} + \mathbf{b}</span>.</p>
<p>Given <span class="math inline">\partial \mathcal{L} / \partial \mathbf{z}</span> arriving from the next layer, the layer owes three things:</p>
<p><span class="math display">\frac{\partial \mathcal{L}}{\partial \mathbf{W}}
  = \frac{\partial \mathcal{L}}{\partial \mathbf{z}}\, \mathbf{x}^{\top},
  \qquad
  \frac{\partial \mathcal{L}}{\partial \mathbf{b}}
  = \frac{\partial \mathcal{L}}{\partial \mathbf{z}},
  \qquad
  \frac{\partial \mathcal{L}}{\partial \mathbf{x}}
  = \mathbf{W}^{\top} \frac{\partial \mathcal{L}}{\partial \mathbf{z}}</span></p>
<p>The first two are what the optimizer updates. The third is the upstream gradient for the layer <strong>behind</strong> this one, which is what makes the pass propagate.</p>
</section>
<section id="shape-check-on-the-layer-gradients" class="level2">
<h2 class="anchored" data-anchor-id="shape-check-on-the-layer-gradients">Shape check on the layer gradients</h2>
<p>The formulas are memorable because the shapes force them. A layer with 3 units and 2 inputs, on a single example:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Object</th>
<th>Shape</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\mathbf{W}</span></td>
<td>(3, 2)</td>
<td>units by inputs</td>
</tr>
<tr class="even">
<td><span class="math inline">\mathbf{x}</span></td>
<td>(2,)</td>
<td>what came in</td>
</tr>
<tr class="odd">
<td><span class="math inline">\partial \mathcal{L} / \partial \mathbf{z}</span></td>
<td>(3,)</td>
<td>one per unit</td>
</tr>
<tr class="even">
<td><span class="math inline">\partial \mathcal{L} / \partial \mathbf{W}</span></td>
<td>(3, 2)</td>
<td>(3,) outer (2,)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\partial \mathcal{L} / \partial \mathbf{x}</span></td>
<td>(2,)</td>
<td>(2, 3) times (3,)</td>
</tr>
</tbody>
</table>
<p>Only one arrangement of <span class="math inline">\mathbf{W}</span>, <span class="math inline">\mathbf{W}^{\top}</span> and the incoming gradient produces each required shape. <strong>If the shapes work, the formula is almost certainly right</strong>, and that is the debugging trick to remember.</p>
</section>
<section id="layer-backward-pass-verified-against-autograd" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="layer-backward-pass-verified-against-autograd">Layer backward pass, verified against autograd</h2>
<p>Lab 2’s 2-3-2-1 network, same seed. The whole backward pass written out in NumPy, then checked against <code>loss.backward()</code>. Source code for your reference; the numbers are the point.</p>
<div id="123297a7" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">6600</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>W1, b1 <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="fl">0.8</span>, (<span class="dv">3</span>, <span class="dv">2</span>)), np.zeros(<span class="dv">3</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>W2, b2 <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="fl">0.8</span>, (<span class="dv">2</span>, <span class="dv">3</span>)), np.zeros(<span class="dv">2</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>W3, b3 <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="fl">0.8</span>, (<span class="dv">1</span>, <span class="dv">2</span>)), np.zeros(<span class="dv">1</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>X, Y <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">1</span>, (<span class="dv">5</span>, <span class="dv">2</span>)), rng.normal(<span class="dv">0</span>, <span class="dv">1</span>, (<span class="dv">5</span>, <span class="dv">1</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> X.shape[<span class="dv">0</span>]</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># forward, keeping every activation because the backward pass needs them</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>z1 <span class="op">=</span> X <span class="op">@</span> W1.T <span class="op">+</span> b1<span class="op">;</span>   a1 <span class="op">=</span> np.tanh(z1)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>z2 <span class="op">=</span> a1 <span class="op">@</span> W2.T <span class="op">+</span> b2<span class="op">;</span>  a2 <span class="op">=</span> np.tanh(z2)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>z3 <span class="op">=</span> a2 <span class="op">@</span> W3.T <span class="op">+</span> b3</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>cost <span class="op">=</span> <span class="bu">float</span>(np.mean((z3 <span class="op">-</span> Y) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># backward, right to left: seed, then (local gradient) x (upstream gradient)</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>dz3 <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (z3 <span class="op">-</span> Y) <span class="op">/</span> N                     <span class="co"># d cost / d z3</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>gW3, gb3 <span class="op">=</span> dz3.T <span class="op">@</span> a2, dz3.<span class="bu">sum</span>(<span class="dv">0</span>)          <span class="co"># this layer's parameters</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>dz2 <span class="op">=</span> (dz3 <span class="op">@</span> W3) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> a2 <span class="op">**</span> <span class="dv">2</span>)           <span class="co"># through W3, then through tanh</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>gW2, gb2 <span class="op">=</span> dz2.T <span class="op">@</span> a1, dz2.<span class="bu">sum</span>(<span class="dv">0</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>dz1 <span class="op">=</span> (dz2 <span class="op">@</span> W2) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> a1 <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>gW1, gb1 <span class="op">=</span> dz1.T <span class="op">@</span> X, dz1.<span class="bu">sum</span>(<span class="dv">0</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="co"># the same thing, asked of autograd</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> nn.Sequential(nn.Linear(<span class="dv">2</span>, <span class="dv">3</span>), nn.Tanh(),</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>                      nn.Linear(<span class="dv">3</span>, <span class="dv">2</span>), nn.Tanh(),</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>                      nn.Linear(<span class="dv">2</span>, <span class="dv">1</span>)).double()</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> layer, (W, b) <span class="kw">in</span> <span class="bu">zip</span>([model[<span class="dv">0</span>], model[<span class="dv">2</span>], model[<span class="dv">4</span>]],</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>                             [(W1, b1), (W2, b2), (W3, b3)]):</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>        layer.weight.copy_(torch.from_numpy(W))</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>        layer.bias.copy_(torch.from_numpy(b))</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>torch_cost <span class="op">=</span> nn.MSELoss()(model(torch.from_numpy(X)), torch.from_numpy(Y))</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>torch_cost.backward()</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cost   by hand </span><span class="sc">{</span>cost<span class="sc">:.6f}</span><span class="ss">   autograd </span><span class="sc">{</span><span class="bu">float</span>(torch_cost)<span class="sc">:.6f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">''</span><span class="sc">:&gt;4}{</span><span class="st">'shape'</span><span class="sc">:&gt;9}{</span><span class="st">'max |by hand - autograd|'</span><span class="sc">:&gt;28}</span><span class="ss">"</span>)</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, mine, p <span class="kw">in</span> [(<span class="st">"W1"</span>, gW1, model[<span class="dv">0</span>].weight), (<span class="st">"b1"</span>, gb1, model[<span class="dv">0</span>].bias),</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"W2"</span>, gW2, model[<span class="dv">2</span>].weight), (<span class="st">"b2"</span>, gb2, model[<span class="dv">2</span>].bias),</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"W3"</span>, gW3, model[<span class="dv">4</span>].weight), (<span class="st">"b3"</span>, gb3, model[<span class="dv">4</span>].bias)]:</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&gt;4}{</span><span class="bu">str</span>(mine.shape)<span class="sc">:&gt;9}</span><span class="ss">"</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(mine <span class="op">-</span> p.grad.numpy())<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:&gt;28.2e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>cost   by hand 2.863851   autograd 2.863851

        shape    max |by hand - autograd|
  W1   (3, 2)                    4.44e-16
  b1     (3,)                    2.22e-16
  W2   (2, 3)                    2.22e-16
  b2     (2,)                    2.22e-16
  W3   (1, 2)                    3.33e-16
  b3     (1,)                    2.22e-16</code></pre>
</div>
</div>
</section>
<section id="the-three-rules-that-reproduced-autograd" class="level2">
<h2 class="anchored" data-anchor-id="the-three-rules-that-reproduced-autograd">The three rules that reproduced autograd</h2>
<p>Twelve lines of NumPy reproduced <code>loss.backward()</code> to floating-point noise, on a three-layer network, using nothing but:</p>
<ul>
<li><span class="math inline">\partial \mathcal{L}/\partial \mathbf{W} = \partial \mathcal{L}/\partial \mathbf{z} \cdot \mathbf{x}^{\top}</span></li>
<li><span class="math inline">\partial \mathcal{L}/\partial \mathbf{x} = \mathbf{W}^{\top} \cdot \partial \mathcal{L}/\partial \mathbf{z}</span></li>
<li><span class="math inline">\tanh'(z) = 1 - \tanh^2(z)</span>, which reuses the cached activation</li>
</ul>
<p>Autograd is not doing anything you cannot do. It is doing it for an arbitrary graph, without you writing the six lines per layer, and without getting a transpose wrong at 2 AM.</p>
</section>
<section id="ann-matrix-notation" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="ann-matrix-notation">ANN matrix notation</h2>
<p>The same network, written out in full. Worth having on hand once; not worth reading aloud.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p><a href="images/ann-matrix-notation.png" class="zoom" target="_blank"><img src="images/ann-matrix-notation.png" class="dh460 img-fluid" width="450"></a></p>
</div><div class="column" style="width:45%;">
<p>Notation to keep straight:</p>
<ul>
<li><span class="math inline">\mathbf{W}^{(\ell)}</span> is layer <span class="math inline">\ell</span>’s weights, <code>(units, inputs)</code></li>
<li><span class="math inline">\mathbf{z}^{(\ell)}</span> is the pre-activation</li>
<li><span class="math inline">\mathbf{a}^{(\ell)} = g(\mathbf{z}^{(\ell)})</span> is the activation</li>
<li><span class="math inline">\mathbf{a}^{(0)} = \mathbf{x}</span> is the input</li>
<li>The superscript is the layer, the subscript is the unit</li>
</ul>
<p>Every quantity in the backward pass has a matching shape on this diagram.</p>
</div>
</div>
</section>
<section id="ann-forward-and-backward-worked" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="ann-forward-and-backward-worked">ANN forward and backward, worked</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Forward</strong></p>
<p><a href="images/ann-forward-regression.png" class="zoom" target="_blank"><img src="images/ann-forward-regression.png" class="dh420 img-fluid" width="510"></a></p>
</div><div class="column" style="width:50%;">
<p><strong>Backward</strong></p>
<p><a href="images/ann-backward-regression.png" class="zoom" target="_blank"><img src="images/ann-backward-regression.png" class="dh420 img-fluid" width="543"></a></p>
</div>
</div>
<p>Left to right, then right to left, on the same network. These are on the handout at full size; the point here is the symmetry, not the entries.</p>
</section>
<section id="jacobian-memory-cost" class="level2">
<h2 class="anchored" data-anchor-id="jacobian-memory-cost">Jacobian memory cost</h2>
<p>The full Jacobian of a layer holds the derivative of every output coordinate with respect to every input coordinate. For a batch of 128, 128 features in and 256 units out, in float32:</p>
<p><span class="math display">128 \times 128 \times 128 \times 256 \times 4 \text{ bytes}
  \approx 6.5 \text{ GB}</span></p>
<p>For <strong>one layer</strong>. The two gradients training actually needs, <span class="math inline">\partial \mathcal{L}/\partial \mathbf{W}</span> and <span class="math inline">\partial \mathcal{L}/\partial \mathbf{x}</span>, come to about <strong>198 KB</strong>.</p>
<p>Reverse mode never forms the Jacobian. It only ever computes Jacobian-times-vector, which is the matrix multiply on the previous slides. That is the difference between a model that fits in memory and one that does not.</p>
</section>
<section id="one-entry-of-the-weight-gradient" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="one-entry-of-the-weight-gradient">One entry of the weight gradient</h2>
<p><a href="images/matrix-multiplication-differentiation-w11.png" class="zoom" target="_blank"><img src="images/matrix-multiplication-differentiation-w11.png" class="dw60 img-fluid" width="630"></a></p>
<p>Expanding <span class="math inline">\partial J / \partial w_{1,1}</span> gives eight terms and <strong>six are zero</strong>, leaving a column of <span class="math inline">\mathbf{X}</span> dotted with a column of <span class="math inline">\nabla_{\mathbf{Z}} J</span>. That pattern, over every entry, is exactly <span class="math inline">\nabla_{\mathbf{W}} J = \mathbf{X}^{\top} \nabla_{\mathbf{Z}} J</span>.</p>
</section>
<section id="backward-pass-in-node-form-input-to-relu" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="backward-pass-in-node-form-input-to-relu">Backward pass in node form: input to ReLU</h2>
<p><a href="images/ann-backward-node-left.png" class="zoom" target="_blank"><img src="images/ann-backward-node-left.png" class="dw95 img-fluid" width="1050"></a></p>
<p>One column per node, with the matrix each node hands backward written out. At the multiply node, the two familiar rules: <span class="math inline">\nabla_{\mathbf{X}} J = \nabla_{\mathbf{Z}} J \mathbf{W}^{\top}</span> and <span class="math inline">\nabla_{\mathbf{W}} J = \mathbf{X}^{\top} \nabla_{\mathbf{Z}} J</span>. At the ReLU, a gate: pass the entry through where <span class="math inline">z &gt; 0</span>, otherwise zero.</p>
</section>
<section id="backward-pass-in-node-form-output-layer-to-cost" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="backward-pass-in-node-form-output-layer-to-cost">Backward pass in node form: output layer to cost</h2>
<p><a href="images/ann-backward-node-right.png" class="zoom" target="_blank"><img src="images/ann-backward-node-right.png" class="dw95 img-fluid" width="1050"></a></p>
<p>The right half of the same strip. The linear output layer has derivative 1, so it passes its gradient straight through, and the cost node starts the whole chain with <span class="math inline">\nabla_{\mathbf{A}} J = \frac{2}{m}(\hat{\mathbf{Y}} -
\mathbf{Y})</span>.</p>
</section>
<section id="exploding-and-vanishing-gradients" class="level2">
<h2 class="anchored" data-anchor-id="exploding-and-vanishing-gradients">Exploding and vanishing gradients</h2>
<p><a href="images/exploding-vanishing-gradient.png" class="zoom" target="_blank"><img src="images/exploding-vanishing-gradient.png" class="dw70 img-fluid" width="735"></a></p>
<p>The gradient is a product of one factor per layer, so it compounds as it travels right to left. Consistently large factors make it <strong>explode</strong> before it reaches the early layers; consistently small ones make it <strong>vanish</strong>.</p>
<p>Either way the layers nearest the input are the ones that suffer, which is exactly the opposite of what you want, since they set the features every later layer builds on.</p>
</section>
<section id="gradient-magnitude-by-layer-measured" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="gradient-magnitude-by-layer-measured">Gradient magnitude by layer, measured</h2>
<p><a href="images/fig-gradient-decay.png" class="zoom" target="_blank"><img src="images/fig-gradient-decay.png" class="dw85 img-fluid" width="1050"></a></p>
<p>Twenty layers, real gradients read out of autograd. The chain rule <strong>multiplies</strong>, so a local derivative consistently below 1 drives the product to zero and one consistently above 1 drives it to infinity.</p>
<p>Sigmoid’s derivative peaks at <span class="math inline">0.25</span>. Twenty of those in a row is <span class="math inline">10^{-13}</span>, which is what the blue line shows: <strong>the layers nearest the input get no signal at all.</strong> Scaling the weights up 60% sends the same architecture to <span class="math inline">10^{7}</span>.</p>
</section>
<section id="causes-and-cures" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="causes-and-cures">Causes and cures</h2>
<div class="columns contrast">
<div class="column col-no" style="width:48%;">
<section id="exploding" class="level3">
<h3 class="anchored" data-anchor-id="exploding">Exploding</h3>
<p>Local derivatives above 1, compounding.</p>
<ul>
<li>Weight initialization too large, or a weight update that overshot</li>
<li><strong>Gradient clipping</strong> caps the norm and is very effective</li>
<li><strong>Weight regularization</strong>, <span class="math inline">\mathcal{L} = \text{error} + \lambda \sum w_i^2</span></li>
<li><strong>Batch normalization</strong></li>
</ul>
</section>
</div><div class="column col-yes" style="width:48%;">
<section id="vanishing" class="level3">
<h3 class="anchored" data-anchor-id="vanishing">Vanishing</h3>
<p>Local derivatives near 0, compounding.</p>
<ul>
<li>Saturating activations, and excessive depth</li>
<li><strong>ReLU</strong> instead of sigmoid, since its derivative is exactly 1 where it is on</li>
<li><strong>Skip connections</strong>, as in ResNet, hand the input forward past layers</li>
<li><strong>Better initialization</strong>, Kaiming or Xavier</li>
</ul>
</section>
</div>
</div>
<p>This is a <strong>training</strong> problem, not an autodiff problem. Autograd will hand you a gradient of <span class="math inline">10^{15}</span> without complaint. <strong>Every cure listed here is Week 4.</strong></p>
</section>
</section>
<section id="pytorch-autograd" class="level1">
<h1>PyTorch autograd</h1>
<ul>
<li>A tensor is an array that remembers where it came from</li>
<li>Everything else in this section is vocabulary</li>
</ul>
<section id="what-a-tensor-is" class="level2">
<h2 class="anchored" data-anchor-id="what-a-tensor-is">What a tensor is</h2>
<p>A <strong>tensor</strong> is an <span class="math inline">n</span>-dimensional array. <strong>Rank</strong>, or <code>ndim</code>, is the number of axes, meaning the number of indices needed to reach one element.</p>
<table class="table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Shape</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><code>[]</code></td>
<td>scalar</td>
</tr>
<tr class="even">
<td>1</td>
<td><code>[n]</code></td>
<td>vector</td>
</tr>
<tr class="odd">
<td>2</td>
<td><code>[m, n]</code></td>
<td>matrix</td>
</tr>
<tr class="even">
<td><span class="math inline">k</span></td>
<td><code>[d1, ..., dk]</code></td>
<td>tensor</td>
</tr>
</tbody>
</table>
<p>A PyTorch tensor is a NumPy array plus three things Lab 2 did not have:</p>
<ul>
<li>A <strong>device</strong>, CPU or CUDA or MPS</li>
<li>A <strong><code>requires_grad</code></strong> flag</li>
<li>A recorded <strong>graph</strong>, so it knows which operation produced it</li>
</ul>
</section>
<section id="tensors-and-numpy-arrays" class="level2">
<h2 class="anchored" data-anchor-id="tensors-and-numpy-arrays">Tensors and NumPy arrays</h2>
<p>The arithmetic is the same. <code>torch.from_numpy</code> even shares memory on CPU, so writing through one view changes the other.</p>
<div id="9b42e78a" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>A_np <span class="op">=</span> np.arange(<span class="dv">6</span>).reshape(<span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> torch.from_numpy(A_np)          <span class="co"># shares storage with A_np on CPU</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"numpy  </span><span class="sc">{</span>A_np<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">  torch  </span><span class="sc">{</span><span class="bu">tuple</span>(A.shape)<span class="sc">}</span><span class="ss">  ndim </span><span class="sc">{</span>A<span class="sc">.</span>ndim<span class="sc">}</span><span class="ss">  "</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"numel </span><span class="sc">{</span>A<span class="sc">.</span>numel()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>A_np[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">=</span> <span class="dv">99</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"wrote through the numpy view; torch sees </span><span class="sc">{</span>A[<span class="dv">0</span>, <span class="dv">0</span>]<span class="sc">.</span>item()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([[<span class="fl">0.7</span>, <span class="op">-</span><span class="fl">1.2</span>]])                  <span class="co"># one batched example, (1, 2)</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> torch.randn(<span class="dv">3</span>, <span class="dv">2</span>, requires_grad<span class="op">=</span><span class="va">True</span>)        <span class="co"># (units, inputs), as in Lab 2</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> torch.zeros(<span class="dv">3</span>, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> x <span class="op">@</span> W.T <span class="op">+</span> b                                  <span class="co"># the batched layer from Lab 2</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">x </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss"> @ W.T </span><span class="sc">{</span><span class="bu">tuple</span>(W.T.shape)<span class="sc">}</span><span class="ss"> + b </span><span class="sc">{</span><span class="bu">tuple</span>(b.shape)<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"-&gt; z </span><span class="sc">{</span><span class="bu">tuple</span>(z.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z was produced by </span><span class="sc">{</span><span class="bu">type</span>(z.grad_fn)<span class="sc">.</span><span class="va">__name__</span><span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"which is the graph autograd recorded"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>numpy  (2, 3)  torch  (2, 3)  ndim 2  numel 6
wrote through the numpy view; torch sees 99

x (1, 2) @ W.T (2, 3) + b (3,) -&gt; z (1, 3)
z was produced by AddBackward0, which is the graph autograd recorded</code></pre>
</div>
</div>
</section>
<section id="dtype-and-device" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="dtype-and-device">dtype and device</h2>
<p>Two attributes that cause most first-week PyTorch errors.</p>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>dtype.</strong> Memory is <code>numel</code> times bytes per element.</p>
<table class="table">
<thead>
<tr class="header">
<th>dtype</th>
<th>Bytes</th>
<th>Used for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>float32</code></td>
<td>4</td>
<td>the default for training</td>
</tr>
<tr class="even">
<td><code>float64</code></td>
<td>8</td>
<td>precision, and slower</td>
</tr>
<tr class="odd">
<td><code>float16</code></td>
<td>2</td>
<td>fast GPU training</td>
</tr>
<tr class="even">
<td><code>bfloat16</code></td>
<td>2</td>
<td>wider exponent, stabler</td>
</tr>
<tr class="odd">
<td><code>int64</code></td>
<td>8</td>
<td>indices, class labels</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:48%;">
<p><strong>device.</strong> Tensors must be on the same device to interact.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>torch.cuda.is_available()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> x.to(<span class="st">"cuda"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>RuntimeError: Expected all tensors to be on the same device</code> is the error you will hit in Lab 3. The fix is always to move one of them.</p>
<p><code>nn.CrossEntropyLoss</code> wants labels as <code>int64</code>. That is the other one.</p>
</div>
</div>
</section>
<section id="requires_grad-and-the-tape" class="level2">
<h2 class="anchored" data-anchor-id="requires_grad-and-the-tape"><code>requires_grad</code> and the tape</h2>
<p>Three rules that explain most of autograd’s behaviour:</p>
<ol type="1">
<li>An operation is recorded if <strong>any</strong> input has <code>requires_grad=True</code></li>
<li><code>.backward()</code> is called on a <strong>scalar</strong>, and it fills <code>.grad</code> on every leaf tensor that requested gradients</li>
<li>Intermediate results do not keep their gradient unless you ask with <code>retain_grad()</code></li>
</ol>
<p>To stop recording, either wrap the block in <code>torch.no_grad()</code> or call <code>.detach()</code>. Do this for evaluation and inference: it is faster and it does not build a graph you are about to throw away.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    val_loss <span class="op">=</span> criterion(model(x_val), y_val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="gradients-accumulate" class="level2">
<h2 class="anchored" data-anchor-id="gradients-accumulate">Gradients accumulate</h2>
<p><code>.grad</code> is a <strong>running sum</strong>, for the reason we saw at the fork. Here is the failure mode rather than a warning about it.</p>
<div id="142bcb84" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x, y <span class="op">=</span> torch.tensor([<span class="fl">3.0</span>]), torch.tensor([<span class="fl">12.0</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> call <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> (w <span class="op">*</span> x <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    loss.backward()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"backward call </span><span class="sc">{</span>call<span class="sc">}</span><span class="ss">:  w.grad = </span><span class="sc">{</span>w<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.1f}</span><span class="ss">"</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"   (</span><span class="sc">{</span>call<span class="sc">}</span><span class="ss">x the true gradient)"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>w.grad.zero_()</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> (w <span class="op">*</span> x <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>loss.backward()</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">after zero_():   w.grad = </span><span class="sc">{</span>w<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.1f}</span><span class="ss">   (correct again)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>backward call 1:  w.grad =   -36.0   (1x the true gradient)
backward call 2:  w.grad =   -72.0   (2x the true gradient)
backward call 3:  w.grad =  -108.0   (3x the true gradient)

after zero_():   w.grad =   -36.0   (correct again)</code></pre>
</div>
</div>
</section>
<section id="zero_grad-and-gradient-accumulation" class="level2">
<h2 class="anchored" data-anchor-id="zero_grad-and-gradient-accumulation"><code>zero_grad</code> and gradient accumulation</h2>
<p>Every training step is these four lines, and the order matters:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>optimizer.zero_grad()    <span class="co"># clear the running sum from last step</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> criterion(model(x), y)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>loss.backward()          <span class="co"># write .grad on every parameter</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>optimizer.step()         <span class="co"># theta &lt;- theta - lr * theta.grad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Forget <code>zero_grad()</code> and step 3 adds to whatever was already there. You are not descending on the current gradient; you are descending on the sum of every gradient since the model was built. The loss usually diverges, and it looks exactly like a learning rate that is too high.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The accumulation is a feature too
</div>
</div>
<div class="callout-body-container callout-body">
<p>Deliberately skipping <code>zero_grad()</code> for a few mini-batches simulates a larger batch than fits in memory. That is <strong>gradient accumulation</strong>, and it is a real technique. It is only a bug when it is an accident.</p>
</div>
</div>
</section>
<section id="nn.linear-is-lab-2s-layer" class="level2">
<h2 class="anchored" data-anchor-id="nn.linear-is-lab-2s-layer"><code>nn.Linear</code> is Lab 2’s layer</h2>
<p><code>nn.Linear(in_features, out_features)</code> stores <span class="math inline">\mathbf{W}</span> as <code>(out_features, in_features)</code> and <span class="math inline">\mathbf{b}</span> as <code>(out_features,)</code>. That is the <code>(units, inputs)</code> convention from Week 2, unchanged.</p>
<div id="96e17aa8" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6600</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>layer <span class="op">=</span> nn.Linear(<span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">5</span>, <span class="dv">2</span>)                       <span class="co"># five examples, two features</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"layer.weight </span><span class="sc">{</span><span class="bu">tuple</span>(layer.weight.shape)<span class="sc">}</span><span class="ss">   "</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"layer.bias </span><span class="sc">{</span><span class="bu">tuple</span>(layer.bias.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"x </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss">  -&gt;  layer(x) </span><span class="sc">{</span><span class="bu">tuple</span>(layer(x).shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># the same arithmetic, written out</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>by_hand <span class="op">=</span> x <span class="op">@</span> layer.weight.T <span class="op">+</span> layer.bias</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">max |layer(x) - (x @ W.T + b)| = "</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>(layer(x) <span class="op">-</span> by_hand)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"nn.Linear is that line, plus the gradient tape"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>layer.weight (3, 2)   layer.bias (3,)
x (5, 2)  -&gt;  layer(x) (5, 3)

max |layer(x) - (x @ W.T + b)| = 0.00e+00
nn.Linear is that line, plus the gradient tape</code></pre>
</div>
</div>
</section>
<section id="nn.module" class="level2">
<h2 class="anchored" data-anchor-id="nn.module"><code>nn.Module</code></h2>
<p>A model is a class with two jobs: declare the layers in <code>__init__</code>, and write the forward pass in <code>forward</code>. Subclassing <code>nn.Module</code> is what registers the parameters so the optimizer, <code>.to(device)</code> and saving all find them.</p>
<div id="3591f81b" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MLP(nn.Module):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, hidden<span class="op">=</span><span class="dv">16</span>):</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden <span class="op">=</span> nn.Linear(<span class="dv">1</span>, hidden)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, <span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(torch.tanh(<span class="va">self</span>.hidden(x)))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> MLP()</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, p <span class="kw">in</span> model.named_parameters():</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">:&lt;14}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">str</span>(<span class="bu">tuple</span>(p.shape))<span class="sc">:&gt;10}</span><span class="ss">  </span><span class="sc">{</span>p<span class="sc">.</span>numel()<span class="sc">:&gt;3}</span><span class="ss"> "</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"parameter</span><span class="sc">{</span><span class="st">'s'</span> <span class="cf">if</span> p<span class="sc">.</span>numel() <span class="op">!=</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">''</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">total: </span><span class="sc">{</span><span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> model.parameters())<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(Lab 2's network, exactly)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MLP(
  (hidden): Linear(in_features=1, out_features=16, bias=True)
  (out): Linear(in_features=16, out_features=1, bias=True)
)

  hidden.weight     (16, 1)   16 parameters
  hidden.bias         (16,)   16 parameters
  out.weight        (1, 16)   16 parameters
  out.bias             (1,)    1 parameter

total: 49 (Lab 2's network, exactly)</code></pre>
</div>
</div>
</section>
<section id="modelx-versus-model.forwardx" class="level2">
<h2 class="anchored" data-anchor-id="modelx-versus-model.forwardx"><code>model(x)</code> versus <code>model.forward(x)</code></h2>
<p>Call <code>model(x)</code>, never <code>model.forward(x)</code>. The first runs registered hooks and respects train and eval mode; the second skips them.</p>
<ul>
<li><code>nn.Sequential</code> is the same thing when the graph is a straight line, which is all of today</li>
<li><code>model.train()</code> and <code>model.eval()</code> change the behaviour of dropout and batch normalization. Neither is in today’s model, so neither matters yet, and both will bite you in Week 4 if you forget them</li>
<li><code>model.parameters()</code> is what you hand the optimizer</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span><span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="loss-functions-in-pytorch" class="level2">
<h2 class="anchored" data-anchor-id="loss-functions-in-pytorch">Loss functions in PyTorch</h2>
<table class="table">
<thead>
<tr class="header">
<th>Task</th>
<th>Final layer</th>
<th>PyTorch loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>linear, 1 unit</td>
<td><code>nn.MSELoss</code></td>
</tr>
<tr class="even">
<td>Binary classification</td>
<td>linear, 1 unit</td>
<td><code>nn.BCEWithLogitsLoss</code></td>
</tr>
<tr class="odd">
<td>Multi-class, <span class="math inline">C</span> classes</td>
<td>linear, <span class="math inline">C</span> units</td>
<td><code>nn.CrossEntropyLoss</code></td>
</tr>
</tbody>
</table>
<p>Note what is <strong>not</strong> in that middle column: no sigmoid, and no softmax.</p>
<p><code>nn.BCELoss</code> exists and takes probabilities, so it needs a sigmoid in the model. Prefer <code>BCEWithLogitsLoss</code>, which folds the sigmoid in and is numerically stabler for the reason on the cancellation slide.</p>
</section>
<section id="logits-and-crossentropyloss" class="level2">
<h2 class="anchored" data-anchor-id="logits-and-crossentropyloss">Logits and <code>CrossEntropyLoss</code></h2>
<p>In Keras you apply softmax in the model. <strong>In PyTorch you do not.</strong> <code>nn.CrossEntropyLoss</code> applies <span class="math inline">\log\mathrm{softmax}</span> internally and then takes the negative log-likelihood:</p>
<p><span class="math display">\mathcal{L}(z, y) = -\log \frac{e^{z_y}}{\sum_j e^{z_j}}</span></p>
<p>So classification models in this course return <strong>logits</strong>, raw scores of shape <code>(N, C)</code>, and the targets are <strong>integer class labels</strong> of shape <code>(N,)</code> with dtype <code>int64</code>. Not one-hot.</p>
<p>Apply softmax in the model as well and you have applied it twice: the gradients degrade and the numerics get worse. It is a quiet bug, because the model still trains, just badly.</p>
</section>
</section>
<section id="the-first-training-loop" class="level1">
<h1>The first training loop</h1>
<ul>
<li>Lab 2’s network, Lab 2’s data, Lab 2’s initialization</li>
<li>One backward pass per step instead of fifty forward passes</li>
</ul>
<section id="full-batch-mini-batch-stochastic" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="full-batch-mini-batch-stochastic">Full batch, mini-batch, stochastic</h2>
<p>One <strong>optimizer step</strong> is one parameter update. How much data goes into it has a name. For <span class="math inline">N = 100</span> training examples:</p>
<table class="table">
<thead>
<tr class="header">
<th>Paradigm</th>
<th>Batch size</th>
<th>Updates per epoch</th>
<th>Gradient noise</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full batch</td>
<td>100</td>
<td>1</td>
<td>none</td>
</tr>
<tr class="even">
<td>Stochastic</td>
<td>1</td>
<td>100</td>
<td>very high</td>
</tr>
<tr class="odd">
<td>Mini-batch</td>
<td>25</td>
<td>4</td>
<td>moderate</td>
</tr>
</tbody>
</table>
<p>An <strong>epoch</strong> is one pass through the whole training set.</p>
<p>Mini-batch is the standard, and the noise turns out to be useful rather than merely tolerable. Today’s demo is <strong>full batch</strong> on 200 points, so there is one update per epoch and the loss curve is smooth. <code>DataLoader</code> and real mini-batches are Week 4.</p>
</section>
<section id="the-loop" class="level2">
<h2 class="anchored" data-anchor-id="the-loop">The loop</h2>
<p>These five lines will not change for the rest of the semester:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(STEPS):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()               <span class="co"># clear the running sum</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> criterion(model(x), y)        <span class="co"># forward, and record</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    loss.backward()                      <span class="co"># backward, fill every .grad</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    optimizer.step()                     <span class="co"># theta &lt;- theta - lr * grad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Everything else is which model, which loss, which optimizer, and what data comes in. The optimizer is plain <strong>SGD</strong> today, the same update rule from Week 1:</p>
<p><span class="math display">\theta^{(t+1)} = \theta^{(t)} - \eta\, \nabla_{\theta} \mathcal{L}\big(\theta^{(t)}\big)</span></p>
<p>Adam, schedules and momentum are Week 4. Today we only want the gradient to be correct and cheap.</p>
</section>
<section id="lab-2s-network-trained-with-autograd" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="lab-2s-network-trained-with-autograd">Lab 2’s network, trained with autograd</h2>
<p>Same seed, same weights, same 400 steps, same learning rate. Source code for your reference. The printed losses should match Lab 2 to four decimals; the work per step should not.</p>
<div id="7e1724a4" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>SEED, HIDDEN, STEPS, LR <span class="op">=</span> <span class="dv">6600</span>, <span class="dv">16</span>, <span class="dv">400</span>, <span class="fl">0.1</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>SHAPES <span class="op">=</span> [(<span class="st">"W"</span>, (HIDDEN, <span class="dv">1</span>)), (<span class="st">"b"</span>, (HIDDEN,)), (<span class="st">"W"</span>, (<span class="dv">1</span>, HIDDEN)), (<span class="st">"b"</span>, (<span class="dv">1</span>,))]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Lab 2's data and initialization, reproduced exactly: two generators, both</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># seeded with SEED, so neither advances the other's stream.</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>rng_data, rng_init <span class="op">=</span> np.random.default_rng(SEED), np.random.default_rng(SEED)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>x_np <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">200</span>).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>y_np <span class="op">=</span> np.sin(<span class="fl">3.0</span> <span class="op">*</span> x_np.ravel()) <span class="op">+</span> rng_data.normal(<span class="dv">0</span>, <span class="fl">0.10</span>, <span class="dv">200</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>theta, i <span class="op">=</span> np.zeros(<span class="bu">sum</span>(<span class="bu">int</span>(np.prod(s)) <span class="cf">for</span> _, s <span class="kw">in</span> SHAPES)), <span class="dv">0</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> kind, shape <span class="kw">in</span> SHAPES:</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">int</span>(np.prod(shape))</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    theta[i:i <span class="op">+</span> n] <span class="op">=</span> (rng_init.normal(<span class="dv">0</span>, <span class="dv">1</span> <span class="op">/</span> np.sqrt(shape[<span class="dv">1</span>]), n)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>                      <span class="cf">if</span> kind <span class="op">==</span> <span class="st">"W"</span> <span class="cf">else</span> <span class="fl">0.0</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> n</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> nn.Sequential(nn.Linear(<span class="dv">1</span>, HIDDEN), nn.Tanh(),</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>                      nn.Linear(HIDDEN, <span class="dv">1</span>)).double()</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">0</span>].weight.copy_(torch.from_numpy(theta[:HIDDEN].reshape(HIDDEN, <span class="dv">1</span>)))</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">0</span>].bias.copy_(torch.from_numpy(theta[HIDDEN:<span class="dv">2</span> <span class="op">*</span> HIDDEN]))</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">2</span>].weight.copy_(torch.from_numpy(</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>        theta[<span class="dv">2</span> <span class="op">*</span> HIDDEN:<span class="dv">3</span> <span class="op">*</span> HIDDEN].reshape(<span class="dv">1</span>, HIDDEN)))</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">2</span>].bias.copy_(torch.from_numpy(theta[<span class="op">-</span><span class="dv">1</span>:]))</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.from_numpy(x_np)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> torch.from_numpy(y_np).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span>LR)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.MSELoss()</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="bu">float</span>(criterion(model(x), y))</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(STEPS):</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> criterion(model(x), y)</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>    loss.backward()</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>    optimizer.step()</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>elapsed <span class="op">=</span> time.perf_counter() <span class="op">-</span> t0</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="bu">float</span>(criterion(model(x), y))</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>n_params <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> model.parameters())</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parameters      </span><span class="sc">{</span>n_params<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cost at start   </span><span class="sc">{</span>start<span class="sc">:.4f}</span><span class="ss">      (Lab 2: 1.3256)"</span>)</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cost at end     </span><span class="sc">{</span>end<span class="sc">:.4f}</span><span class="ss">      (Lab 2: 0.0190)"</span>)</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"wall time       </span><span class="sc">{</span>elapsed<span class="sc">:.2f}</span><span class="ss"> s for </span><span class="sc">{</span>STEPS<span class="sc">}</span><span class="ss"> steps"</span>)</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"work per step   1 forward + 1 backward, not </span><span class="sc">{</span>n_params <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> forwards"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>parameters      49
cost at start   1.3256      (Lab 2: 1.3256)
cost at end     0.0190      (Lab 2: 0.0190)
wall time       0.15 s for 400 steps
work per step   1 forward + 1 backward, not 50 forwards</code></pre>
</div>
</div>
</section>
<section id="loss-curves-autograd-and-finite-differences" class="level2">
<h2 class="anchored" data-anchor-id="loss-curves-autograd-and-finite-differences">Loss curves, autograd and finite differences</h2>
<p><a href="images/demo-autograd-training.gif" class="zoom" target="_blank"><img src="images/demo-autograd-training.gif" class="dw85 img-fluid" width="880"></a></p>
<p>The grey curve is Lab 2’s finite-difference run. The red curve is today’s. They agree to <span class="math inline">3.8 \times 10^{-7}</span> over all 400 steps, because both are estimating the <strong>same gradient of the same cost on the same data</strong>.</p>
<p>Finite differences were never wrong. They were just expensive.</p>
</section>
<section id="finite-differences-and-autograd-side-by-side" class="level2">
<h2 class="anchored" data-anchor-id="finite-differences-and-autograd-side-by-side">Finite differences and autograd, side by side</h2>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Lab 2</th>
<th>Today</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gradient from</td>
<td>finite differences</td>
<td>reverse-mode autodiff</td>
</tr>
<tr class="even">
<td>Cost at start</td>
<td>1.3256</td>
<td>1.3256</td>
</tr>
<tr class="odd">
<td>Cost at end</td>
<td>0.0190</td>
<td>0.0190</td>
</tr>
<tr class="even">
<td>Work per step</td>
<td>50 forward passes</td>
<td>1 forward + 1 backward</td>
</tr>
<tr class="odd">
<td>Work for 400 steps</td>
<td>20,001 forward passes</td>
<td>400 backward passes</td>
</tr>
<tr class="even">
<td>Exact?</td>
<td>no, <span class="math inline">O(\varepsilon)</span> error</td>
<td>yes, to floating point</td>
</tr>
</tbody>
</table>
<p>Same descent, 50x less work, and no <span class="math inline">\varepsilon</span> to tune. At ResNet-50 scale the ratio is not 50, it is 25 million.</p>
<p>The gradient has stopped being the expensive part. Everything that can still go wrong is now about the <strong>optimizer</strong>, the <strong>data</strong>, and the <strong>loss surface</strong>.</p>
</section>
<section id="scope-today-and-week-4" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="scope-today-and-week-4">Scope: today and Week 4</h2>
<p>Left out on purpose, and all of it lands next week:</p>
<div class="columns contrast">
<div class="column col-yes" style="width:48%;">
<section id="today" class="level3">
<h3 class="anchored" data-anchor-id="today">Today</h3>
<ul>
<li>Why finite differences do not scale</li>
<li>The chain rule on a graph</li>
<li>Reverse-mode autodiff, by hand and in PyTorch</li>
<li>Tensors, <code>.backward()</code>, <code>.grad</code>, <code>zero_grad</code></li>
<li><code>nn.Linear</code>, <code>nn.Module</code>, SGD</li>
<li>One 49-parameter training loop</li>
</ul>
</section>
</div><div class="column col-no" style="width:48%;">
<section id="week-4" class="level3">
<h3 class="anchored" data-anchor-id="week-4">Week 4</h3>
<ul>
<li>Adam, RMSProp, momentum, weight decay</li>
<li>Dropout, batch norm, skip connections</li>
<li>Learning-rate schedules, gradient clipping</li>
<li>Initialization as a decision you make</li>
<li><code>Dataset</code>, <code>DataLoader</code>, real mini-batches</li>
<li>A training run worth the name</li>
</ul>
</section>
</div>
</div>
<p>You should leave able to read any PyTorch training loop and say which line is the backward pass. You should not leave an optimizer expert.</p>
</section>
</section>
<section id="closing" class="level1">
<h1>Closing</h1>
<ul>
<li>Lab 3</li>
<li>Quiz 3 study guide</li>
<li>Supplemental content</li>
<li>Quiz 2, right now</li>
</ul>
<section id="lab-3" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="lab-3">Lab 3</h2>
<p><strong>Released today. Due Wednesday Sep 16, 11:59 PM ET.</strong></p>
<p>Lab 2’s network, in PyTorch:</p>
<ol type="1">
<li>Wrap the <span class="math inline">1 \to 16 \to 1</span> model as an <code>nn.Module</code></li>
<li>Delete <code>finite_difference_gradient</code>; call <code>loss.backward()</code> instead</li>
<li>Confirm your loss curve matches the one you produced last week</li>
<li>Break it on purpose: run the loop once with <code>zero_grad()</code> removed, and report what happened</li>
<li>Hand-derive the gradient for one weight and check it against <code>.grad</code></li>
</ol>
<p>Same rules as Labs 1 and 2: graded for <strong>completion</strong>, work together if you like, solutions posted after the deadline.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why this order
</div>
</div>
<div class="callout-body-container callout-body">
<p>Last week you paid 20,001 forward passes for 400 steps. This week the same fit is one <code>loss.backward()</code> per step. The payoff only lands if you felt the bill first.</p>
</div>
</div>
</section>
<section id="quiz-3-study-guide" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="quiz-3-study-guide">Quiz 3 study guide</h2>
<p><strong>Next week, end of class.</strong> Closed-book, no notes. A formula sheet comes with the quiz.</p>
<p>Everything on it comes from today and Lab 3:</p>
<ol type="1">
<li><strong>Why finite differences do not scale</strong>, and what reverse-mode autodiff computes instead</li>
<li><strong>The chain rule on a graph</strong>: the add node, the multiply node, the max node, and why gradients sum over paths</li>
<li><strong><code>.backward()</code>, <code>.grad</code>, <code>zero_grad()</code></strong>: what each does, and what breaks if you skip the third</li>
<li><strong>Reverse mode versus forward mode</strong>, and why a scalar cost decides it</li>
<li><strong><code>nn.Linear</code> shapes</strong>: <code>(out_features, in_features)</code>, matching Lab 2</li>
<li><strong>The training loop</strong>, in order: zero, forward, loss, backward, step</li>
<li><strong>Loss versus cost</strong>, and which one <code>.backward()</code> is called on</li>
<li><strong>From Lab 3</strong>: what changed when autograd replaced finite differences, and what happened when you removed <code>zero_grad()</code>. Explanations, not numbers</li>
</ol>
</section>
<section id="supplemental-content" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="supplemental-content">Supplemental content</h2>
<p>These are <strong>optional</strong>. No graded work assumes you read them. They go deeper than we had time for, and the first two are the source notebooks this deck was built from.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Autodiff and gradients</strong></p>
<ul>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/backprop/automatic-differentiation/automatic-differentiation.html">Automatic differentiation</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/backprop/matrix-multiplication-differentiation/matrix-multiplication-differentiaion.html">Matrix-multiplication differentiation</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/fundamentals/gradient-descent/notes.html">Gradient descent</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/backprop/backprop-basics-video/notes.html">Backprop basics, video</a></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>PyTorch</strong></p>
<ul>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-tensors/notes.html">Tensors</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-models/torch-models.html">Models</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-data/torch-data.html">Data</a></li>
</ul>
</div>
</div>
<p><sup>All of these live on the <a href="https://jfh.georgetown.domains/centralized-lecture-content/">centralized lecture content</a> site. The autodiff page also carries a from-scratch <code>Node</code> class that implements today’s graph, topological sort and backward pass in about 80 lines of NumPy. The PyTorch pages carry the Week 4 material as well, so expect to see them again.</sup></p>
</section>
<section id="wrap-up" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>Where we started: 20,001 forward passes for one decent fit. Where we are:</p>
<ul>
<li>A <strong>computational graph</strong> is the forward pass, recorded. Values at the nodes, operations on the edges</li>
<li><strong>Backpropagation</strong> is the chain rule on that graph, right to left, multiplying local derivatives and <strong>adding where paths meet</strong></li>
<li><strong>Reverse mode</strong> is the right direction because the cost is a <strong>scalar</strong></li>
<li>A <strong>layer’s</strong> backward pass is two matrix multiplies. Nobody forms a Jacobian</li>
<li><strong>Autograd</strong> implements all of it. <code>.backward()</code> is the backward pass; <code>zero_grad()</code> clears the running sum</li>
<li><strong><code>nn.Linear</code></strong> is Lab 2’s layer and <strong><code>nn.Module</code></strong> is a forward pass with parameters attached</li>
<li>The <strong>training loop</strong> is five lines, and the interesting one is <code>optimizer</code></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Next week
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Training deep neural networks.</strong> Adam, regularization, schedules, initialization, mini-batches, and all the reasons a correct gradient is not the same thing as a training run that works.</p>
</div>
</div>
<p><strong>Before Thursday:</strong> Lab 3, due Wednesday. And claim a Spotlight slot if you have not.</p>
</section>
<section id="quiz-2" class="level2">
<h2 class="anchored" data-anchor-id="quiz-2">Quiz 2</h2>
<p>Closed-book, no notes. A formula sheet comes with it.</p>
<p>Covers <strong>Week 2 and Lab 2</strong>:</p>
<ul>
<li>Layer shapes and parameter counts</li>
<li>The forward pass, single example and batched</li>
<li>Why nonlinearities exist, and what stacked linear layers collapse to</li>
<li>Activations: sigmoid, tanh, ReLU, softmax</li>
<li>Depth versus width</li>
<li>Why finite-difference gradients do not scale</li>
</ul>
<p>Twenty-five points. Show your work; an answer with no reasoning earns partial credit at best.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>