<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Ben Houghton">
<meta name="dcterms.date" content="2026-10-01">

<title>DSAN 6600: Convolutional Neural Networks</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="05-convolutional-networks_files/libs/clipboard/clipboard.min.js"></script>
<script src="05-convolutional-networks_files/libs/quarto-html/quarto.js"></script>
<script src="05-convolutional-networks_files/libs/quarto-html/popper.min.js"></script>
<script src="05-convolutional-networks_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="05-convolutional-networks_files/libs/quarto-html/anchor.min.js"></script>
<link href="05-convolutional-networks_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="05-convolutional-networks_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="05-convolutional-networks_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="05-convolutional-networks_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="05-convolutional-networks_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link rel="icon" type="image/png" href="/icon.png">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#today" id="toc-today" class="nav-link active" data-scroll-target="#today">Today</a></li>
  <li><a href="#labs-and-quizzes" id="toc-labs-and-quizzes" class="nav-link" data-scroll-target="#labs-and-quizzes">Labs and quizzes</a></li>
  <li><a href="#what-lab-4-threw-away" id="toc-what-lab-4-threw-away" class="nav-link" data-scroll-target="#what-lab-4-threw-away">What Lab 4 threw away</a></li>
  <li><a href="#image-data" id="toc-image-data" class="nav-link" data-scroll-target="#image-data">Image data</a>
  <ul class="collapse">
  <li><a href="#where-image-data-comes-from" id="toc-where-image-data-comes-from" class="nav-link" data-scroll-target="#where-image-data-comes-from">Where image data comes from</a></li>
  <li><a href="#an-image-is-a-tensor" id="toc-an-image-is-a-tensor" class="nav-link" data-scroll-target="#an-image-is-a-tensor">An image is a tensor</a></li>
  <li><a href="#what-a-pixel-is" id="toc-what-a-pixel-is" class="nav-link" data-scroll-target="#what-a-pixel-is">What a pixel is</a></li>
  <li><a href="#channel-layout-hwc-chw-and-nchw" id="toc-channel-layout-hwc-chw-and-nchw" class="nav-link" data-scroll-target="#channel-layout-hwc-chw-and-nchw">Channel layout: HWC, CHW and NCHW</a></li>
  <li><a href="#coordinate-conventions" id="toc-coordinate-conventions" class="nav-link" data-scroll-target="#coordinate-conventions">Coordinate conventions</a></li>
  <li><a href="#channel-order-rgb-and-bgr" id="toc-channel-order-rgb-and-bgr" class="nav-link" data-scroll-target="#channel-order-rgb-and-bgr">Channel order: RGB and BGR</a></li>
  <li><a href="#quantization-and-bit-depth" id="toc-quantization-and-bit-depth" class="nav-link" data-scroll-target="#quantization-and-bit-depth">Quantization and bit depth</a></li>
  <li><a href="#dynamic-range-and-normalization" id="toc-dynamic-range-and-normalization" class="nav-link" data-scroll-target="#dynamic-range-and-normalization">Dynamic range and normalization</a></li>
  <li><a href="#why-models-normalize-their-inputs" id="toc-why-models-normalize-their-inputs" class="nav-link" data-scroll-target="#why-models-normalize-their-inputs">Why models normalize their inputs</a></li>
  <li><a href="#resolution" id="toc-resolution" class="nav-link" data-scroll-target="#resolution">Resolution</a></li>
  <li><a href="#upsampling-does-not-undo-downsampling" id="toc-upsampling-does-not-undo-downsampling" class="nav-link" data-scroll-target="#upsampling-does-not-undo-downsampling">Upsampling does not undo downsampling</a></li>
  <li><a href="#aliasing" id="toc-aliasing" class="nav-link" data-scroll-target="#aliasing">Aliasing</a></li>
  <li><a href="#data-augmentation" id="toc-data-augmentation" class="nav-link" data-scroll-target="#data-augmentation">Data augmentation</a></li>
  <li><a href="#augmentation-applied" id="toc-augmentation-applied" class="nav-link" data-scroll-target="#augmentation-applied">Augmentation, applied</a></li>
  <li><a href="#automatic-augmentation-policies" id="toc-automatic-augmentation-policies" class="nav-link" data-scroll-target="#automatic-augmentation-policies">Automatic augmentation policies</a></li>
  <li><a href="#what-augmentation-is-worth-measured" id="toc-what-augmentation-is-worth-measured" class="nav-link" data-scroll-target="#what-augmentation-is-worth-measured">What augmentation is worth, measured</a></li>
  </ul></li>
  <li><a href="#convolution" id="toc-convolution" class="nav-link" data-scroll-target="#convolution">Convolution</a>
  <ul class="collapse">
  <li><a href="#why-a-fully-connected-layer-is-wrong-for-images" id="toc-why-a-fully-connected-layer-is-wrong-for-images" class="nav-link" data-scroll-target="#why-a-fully-connected-layer-is-wrong-for-images">Why a fully connected layer is wrong for images</a></li>
  <li><a href="#two-problems-not-one" id="toc-two-problems-not-one" class="nav-link" data-scroll-target="#two-problems-not-one">Two problems, not one</a></li>
  <li><a href="#the-convolution-operation" id="toc-the-convolution-operation" class="nav-link" data-scroll-target="#the-convolution-operation">The convolution operation</a></li>
  <li><a href="#definition-of-a-convolutional-layer" id="toc-definition-of-a-convolutional-layer" class="nav-link" data-scroll-target="#definition-of-a-convolutional-layer">Definition of a convolutional layer</a></li>
  <li><a href="#convolution-over-channels" id="toc-convolution-over-channels" class="nav-link" data-scroll-target="#convolution-over-channels">Convolution over channels</a></li>
  <li><a href="#filters-and-feature-maps" id="toc-filters-and-feature-maps" class="nav-link" data-scroll-target="#filters-and-feature-maps">Filters and feature maps</a></li>
  <li><a href="#a-hand-set-filter-on-a-real-image" id="toc-a-hand-set-filter-on-a-real-image" class="nav-link" data-scroll-target="#a-hand-set-filter-on-a-real-image">A hand-set filter on a real image</a></li>
  <li><a href="#weight-sharing-and-translation-equivariance" id="toc-weight-sharing-and-translation-equivariance" class="nav-link" data-scroll-target="#weight-sharing-and-translation-equivariance">Weight sharing and translation equivariance</a></li>
  <li><a href="#padding-and-output-size" id="toc-padding-and-output-size" class="nav-link" data-scroll-target="#padding-and-output-size">Padding and output size</a></li>
  <li><a href="#stride" id="toc-stride" class="nav-link" data-scroll-target="#stride">Stride</a></li>
  <li><a href="#pooling" id="toc-pooling" class="nav-link" data-scroll-target="#pooling">Pooling</a></li>
  <li><a href="#pooling-against-strided-convolution" id="toc-pooling-against-strided-convolution" class="nav-link" data-scroll-target="#pooling-against-strided-convolution">Pooling against strided convolution</a></li>
  <li><a href="#receptive-field" id="toc-receptive-field" class="nav-link" data-scroll-target="#receptive-field">Receptive field</a></li>
  <li><a href="#why-small-kernels-stacked" id="toc-why-small-kernels-stacked" class="nav-link" data-scroll-target="#why-small-kernels-stacked">Why small kernels, stacked</a></li>
  <li><a href="#nn.conv2d" id="toc-nn.conv2d" class="nav-link" data-scroll-target="#nn.conv2d"><code>nn.Conv2d</code></a></li>
  </ul></li>
  <li><a href="#building-a-cnn" id="toc-building-a-cnn" class="nav-link" data-scroll-target="#building-a-cnn">Building a CNN</a>
  <ul class="collapse">
  <li><a href="#the-shape-of-a-cnn" id="toc-the-shape-of-a-cnn" class="nav-link" data-scroll-target="#the-shape-of-a-cnn">The shape of a CNN</a></li>
  <li><a href="#activations-in-convolutional-networks" id="toc-activations-in-convolutional-networks" class="nav-link" data-scroll-target="#activations-in-convolutional-networks">Activations in convolutional networks</a></li>
  <li><a href="#batch-normalization" id="toc-batch-normalization" class="nav-link" data-scroll-target="#batch-normalization">Batch normalization</a></li>
  <li><a href="#batchnorm-behaves-differently-in-eval-mode" id="toc-batchnorm-behaves-differently-in-eval-mode" class="nav-link" data-scroll-target="#batchnorm-behaves-differently-in-eval-mode">BatchNorm behaves differently in eval mode</a></li>
  <li><a href="#x1-convolutions" id="toc-x1-convolutions" class="nav-link" data-scroll-target="#x1-convolutions">1x1 convolutions</a></li>
  <li><a href="#global-average-pooling-against-flatten" id="toc-global-average-pooling-against-flatten" class="nav-link" data-scroll-target="#global-average-pooling-against-flatten">Global average pooling against flatten</a></li>
  <li><a href="#residual-connections" id="toc-residual-connections" class="nav-link" data-scroll-target="#residual-connections">Residual connections</a></li>
  <li><a href="#a-small-cnn-in-pytorch" id="toc-a-small-cnn-in-pytorch" class="nav-link" data-scroll-target="#a-small-cnn-in-pytorch">A small CNN in PyTorch</a></li>
  <li><a href="#the-same-budget-two-ways" id="toc-the-same-budget-two-ways" class="nav-link" data-scroll-target="#the-same-budget-two-ways">The same budget, two ways</a></li>
  <li><a href="#what-the-first-layer-learns" id="toc-what-the-first-layer-learns" class="nav-link" data-scroll-target="#what-the-first-layer-learns">What the first layer learns</a></li>
  <li><a href="#what-the-deeper-layers-hold" id="toc-what-the-deeper-layers-hold" class="nav-link" data-scroll-target="#what-the-deeper-layers-hold">What the deeper layers hold</a></li>
  </ul></li>
  <li><a href="#architectures-that-mattered" id="toc-architectures-that-mattered" class="nav-link" data-scroll-target="#architectures-that-mattered">Architectures that mattered</a>
  <ul class="collapse">
  <li><a href="#timeline" id="toc-timeline" class="nav-link" data-scroll-target="#timeline">Timeline</a></li>
  <li><a href="#lenet-5-1989-to-1998" id="toc-lenet-5-1989-to-1998" class="nav-link" data-scroll-target="#lenet-5-1989-to-1998">LeNet-5, 1989 to 1998</a></li>
  <li><a href="#alexnet-2012" id="toc-alexnet-2012" class="nav-link" data-scroll-target="#alexnet-2012">AlexNet, 2012</a></li>
  <li><a href="#vgg-2014" id="toc-vgg-2014" class="nav-link" data-scroll-target="#vgg-2014">VGG, 2014</a></li>
  <li><a href="#vgg-16" id="toc-vgg-16" class="nav-link" data-scroll-target="#vgg-16">VGG-16</a></li>
  <li><a href="#vgg-configurations" id="toc-vgg-configurations" class="nav-link" data-scroll-target="#vgg-configurations">VGG configurations</a></li>
  <li><a href="#inception-modules-2014" id="toc-inception-modules-2014" class="nav-link" data-scroll-target="#inception-modules-2014">Inception modules, 2014</a></li>
  <li><a href="#the-degradation-problem" id="toc-the-degradation-problem" class="nav-link" data-scroll-target="#the-degradation-problem">The degradation problem</a></li>
  <li><a href="#resnet-2015" id="toc-resnet-2015" class="nav-link" data-scroll-target="#resnet-2015">ResNet, 2015</a></li>
  <li><a href="#resnet-configurations" id="toc-resnet-configurations" class="nav-link" data-scroll-target="#resnet-configurations">ResNet configurations</a></li>
  <li><a href="#densenet-2016" id="toc-densenet-2016" class="nav-link" data-scroll-target="#densenet-2016">DenseNet, 2016</a></li>
  <li><a href="#grouped-convolution" id="toc-grouped-convolution" class="nav-link" data-scroll-target="#grouped-convolution">Grouped convolution</a></li>
  <li><a href="#depthwise-separable-convolution" id="toc-depthwise-separable-convolution" class="nav-link" data-scroll-target="#depthwise-separable-convolution">Depthwise separable convolution</a></li>
  <li><a href="#choosing-an-architecture" id="toc-choosing-an-architecture" class="nav-link" data-scroll-target="#choosing-an-architecture">Choosing an architecture</a></li>
  </ul></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a>
  <ul class="collapse">
  <li><a href="#what-to-keep-from-today" id="toc-what-to-keep-from-today" class="nav-link" data-scroll-target="#what-to-keep-from-today">What to keep from today</a></li>
  <li><a href="#next-week-detection-and-segmentation" id="toc-next-week-detection-and-segmentation" class="nav-link" data-scroll-target="#next-week-detection-and-segmentation">Next week: detection and segmentation</a></li>
  <li><a href="#supplemental-content" id="toc-supplemental-content" class="nav-link" data-scroll-target="#supplemental-content">Supplemental content</a></li>
  <li><a href="#lab-5" id="toc-lab-5" class="nav-link" data-scroll-target="#lab-5">Lab 5</a></li>
  <li><a href="#quiz-5" id="toc-quiz-5" class="nav-link" data-scroll-target="#quiz-5">Quiz 5</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="presentation.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DSAN 6600: Convolutional Neural Networks</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Ben Houghton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="today" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="today">Today</h2>
<p>Four sections, and the first two are the ones that make the rest make sense.</p>
<ol type="1">
<li><strong>Image data.</strong> What an image actually is once it is in memory, and the conventions that cause silent bugs.</li>
<li><strong>Convolution.</strong> The operation, its parameters, and the arithmetic you need to predict output shapes.</li>
<li><strong>Building a CNN.</strong> The standard parts, then one real network measured against the fully connected model you built in Lab 4.</li>
<li><strong>Architectures that mattered.</strong> LeNet through EfficientNet, and what each one actually contributed.</li>
</ol>
<p>Next week is what you build <strong>on top</strong> of a CNN: object detection and image segmentation.</p>
</section>
<section id="labs-and-quizzes" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="labs-and-quizzes">Labs and quizzes</h2>
<p><strong>Lab 4 was due yesterday</strong>, Wednesday Sep 30. That was the full training pipeline: your own <code>Dataset</code>, a <code>DataLoader</code>, an optimizer comparison, early stopping, and one look at the test set.</p>
<p><strong>Quiz 5 is today</strong>, at the end of class. It covers <strong>last week’s PyTorch and training material plus Lab 4</strong>. Nothing from today’s deck is on it.</p>
<p><strong>Lab 5 goes out today</strong>, due Wednesday Oct 7.</p>
<p>One thing to flag about Quiz 5: the format changed. There are four parts now, and the last one gives you a short training script with bugs in it and asks you to find them. The study guide and formula sheet on the course site match the new format.</p>
</section>
<section id="what-lab-4-threw-away" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-lab-4-threw-away">What Lab 4 threw away</h2>
<p>Your Lab 4 model started with <code>nn.Flatten()</code>, then <code>nn.Linear(784, 256)</code>. It reached <strong>0.833</strong> test accuracy on Fashion-MNIST, which is a real result.</p>
<p>But look at what flattening does. A 28x28 image becomes a vector of 784 numbers, in row-major order. Pixel 100 and pixel 128 are directly above and below each other in the image. After flattening they are 28 apart, which is the same distance as pixel 100 and pixel 72, and the same distance as pixel 500 and pixel 528.</p>
<p><code>nn.Linear</code> has no way to know any of that. It sees 784 unrelated inputs. Every spatial relationship in the image is still <strong>present</strong> in the data, and it is <strong>invisible</strong> to the layer.</p>
<p>So the layer has to learn, separately, that a vertical edge at position 100 and a vertical edge at position 300 are the same kind of thing. Nothing shares that knowledge between positions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The question this deck answers
</div>
</div>
<div class="callout-body-container callout-body">
<p>What layer would use the structure instead of ignoring it?</p>
</div>
</div>
</section>
<section id="image-data" class="level1">
<h1>Image data</h1>
<section id="where-image-data-comes-from" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="where-image-data-comes-from">Where image data comes from</h2>
<p>Light from the scene passes through a lens and lands on a sensor: a grid of millions of photosites.</p>
<ol type="1">
<li>Each photosite <strong>samples</strong> light from one small region of the scene. That is where height and width come from.</li>
<li>A <strong>colour filter array</strong> sits over the grid, so each photosite measures only red, green, or blue. That is where channels come from.</li>
<li>A <strong>photodiode</strong> turns arriving photons into electric charge.</li>
<li>An <strong>analog-to-digital converter</strong> turns that charge into an integer, usually between 0 and 255.</li>
</ol>
<p>What comes out is a three-dimensional array of integers: height by width by channels.</p>
<p>Two words for later. <strong>Sampling</strong> is taking measurements at discrete positions instead of everywhere. <strong>Quantization</strong> is rounding each measurement to one of a fixed set of levels. Both lose information, and both have failure modes we will look at.</p>
</section>
<section id="an-image-is-a-tensor" class="level2">
<h2 class="anchored" data-anchor-id="an-image-is-a-tensor">An image is a tensor</h2>
<div id="eaf94f6d" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> PIL <span class="im">import</span> Image</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pil <span class="op">=</span> Image.<span class="bu">open</span>(<span class="st">"images/cats-dog.jpg"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> np.array(pil)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"shape      "</span>, img.shape)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dtype      "</span>, img.dtype)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"value range"</span>, <span class="ss">f"[</span><span class="sc">{</span>img<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>img<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">]"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"total numbers"</span>, <span class="ss">f"</span><span class="sc">{</span>img<span class="sc">.</span>size<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">6</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>ax.imshow(img)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="ss">f"</span><span class="sc">{</span>img<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> rows x </span><span class="sc">{</span>img<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> columns x "</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>             <span class="ss">f"</span><span class="sc">{</span>img<span class="sc">.</span>shape[<span class="dv">2</span>]<span class="sc">}</span><span class="ss"> channels"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>shape       (1299, 2309, 3)
dtype       uint8
value range [0, 255]
total numbers 8,998,173</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05-convolutional-networks_files/figure-html/cell-2-output-2.png" width="808" height="483" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-a-pixel-is" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-a-pixel-is">What a pixel is</h2>
<p>A pixel is a <strong>measurement from a sensor</strong>. It is not the truth about the scene.</p>
<p>The same object photographed under warm indoor light and under daylight produces different RGB values. Nothing is broken; the measurement genuinely differs. This is why “the red channel” is only meaningful relative to the lighting and the camera’s white balance.</p>
<p>Three consequences that matter for training:</p>
<ul>
<li>Pixel values carry <strong>noise</strong>, and the noise is larger in dark regions.</li>
<li>The same object can have very different values across two photographs, which is part of why augmentation helps.</li>
<li>A model trained on one camera’s images can get worse on another’s.</li>
</ul>
<div id="158cda6f" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row, col <span class="kw">in</span> [(<span class="dv">260</span>, <span class="dv">390</span>), (<span class="dv">250</span>, <span class="dv">1150</span>), (<span class="dv">250</span>, <span class="dv">1750</span>)]:</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    r, g, b <span class="op">=</span> img[row, col]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"img[</span><span class="sc">{</span>row<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">] = R </span><span class="sc">{</span>r<span class="sc">:3d}</span><span class="ss">  G </span><span class="sc">{</span>g<span class="sc">:3d}</span><span class="ss">  B </span><span class="sc">{</span>b<span class="sc">:3d}</span><span class="ss">"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"one pixel is a vector of"</span>, img.shape[<span class="dv">2</span>], <span class="st">"numbers"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"the whole image is"</span>, <span class="ss">f"</span><span class="sc">{</span>img<span class="sc">.</span>size<span class="sc">:,}</span><span class="ss">"</span>, <span class="st">"numbers"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>img[260, 390] = R 177  G 178  B 173
img[250, 1150] = R 173  G 174  B 169
img[250, 1750] = R 161  G 160  B 156

one pixel is a vector of 3 numbers
the whole image is 8,998,173 numbers</code></pre>
</div>
</div>
</section>
<section id="channel-layout-hwc-chw-and-nchw" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="channel-layout-hwc-chw-and-nchw">Channel layout: HWC, CHW and NCHW</h2>
<p>The same image can be stored with its axes in different orders, and the libraries disagree.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layout</th>
<th>Shape</th>
<th>Who uses it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>HWC</strong></td>
<td><code>(height, width, channels)</code></td>
<td>NumPy, PIL, matplotlib, OpenCV, TensorFlow</td>
</tr>
<tr class="even">
<td><strong>CHW</strong></td>
<td><code>(channels, height, width)</code></td>
<td><strong>PyTorch</strong></td>
</tr>
<tr class="odd">
<td><strong>NCHW</strong></td>
<td><code>(batch, channels, height, width)</code></td>
<td>PyTorch, batched</td>
</tr>
<tr class="even">
<td>NHWC</td>
<td><code>(batch, height, width, channels)</code></td>
<td>TensorFlow, batched</td>
</tr>
</tbody>
</table>
<p>You have already used NCHW. Lab 4’s batches were <code>(128, 1, 28, 28)</code>: 128 images, one channel because Fashion-MNIST is greyscale, 28 rows, 28 columns.</p>
<p><code>transforms.ToTensor()</code> does two things at once that are easy to miss. It converts HWC to CHW, <strong>and</strong> it divides by 255 so values land in <code>[0, 1]</code>.</p>
<div id="913c30a8" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"HWC, as loaded       "</span>, img.shape)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>chw <span class="op">=</span> np.transpose(img, (<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CHW, axes reordered  "</span>, chw.shape)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>nchw <span class="op">=</span> chw[np.newaxis, ...]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"NCHW, batch axis added"</span>, nchw.shape)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> torch.from_numpy(nchw).<span class="bu">float</span>() <span class="op">/</span> <span class="fl">255.0</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"as a float tensor    "</span>, <span class="bu">tuple</span>(t.shape), t.dtype,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"range [</span><span class="sc">{</span>t<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>t<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># The same pixel, found both ways. Reordering axes does not move data.</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"HWC img[250, 1150]   "</span>, img[<span class="dv">250</span>, <span class="dv">1150</span>])</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CHW chw[:, 250, 1150]"</span>, chw[:, <span class="dv">250</span>, <span class="dv">1150</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>HWC, as loaded        (1299, 2309, 3)
CHW, axes reordered   (3, 1299, 2309)
NCHW, batch axis added (1, 3, 1299, 2309)
as a float tensor     (1, 3, 1299, 2309) torch.float32 range [0.000, 1.000]

HWC img[250, 1150]    [173 174 169]
CHW chw[:, 250, 1150] [173 174 169]</code></pre>
</div>
</div>
</section>
<section id="coordinate-conventions" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="coordinate-conventions">Coordinate conventions</h2>
<p>The origin is the <strong>top left</strong>. Row index grows <strong>downward</strong>. Arrays are indexed <code>img[row, column]</code>.</p>
<p>Matplotlib, and most plotting and annotation code, wants <code>(x, y)</code>, which is <code>(column, row)</code>. <strong>The order is reversed.</strong> Swapping them is one of the most common bugs in vision code, and it does not raise an error. You get a box in the wrong place, or a transposed image if the dimensions happen to match.</p>
<p><a href="images/fig-coords.png" class="zoom" target="_blank"><img src="images/fig-coords.png" class="dw75 img-fluid"></a></p>
</section>
<section id="channel-order-rgb-and-bgr" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="channel-order-rgb-and-bgr">Channel order: RGB and BGR</h2>
<p>Most libraries give you RGB. <strong>OpenCV gives you BGR</strong>, for historical reasons.</p>
<p>If you read with OpenCV and display or normalize as if it were RGB, the red and blue channels are swapped. Nothing raises. The array has the right shape and the right dtype. Training still runs. The model is just worse, and the reason is invisible.</p>
<p><a href="images/fig-channel-order.png" class="zoom" target="_blank"><img src="images/fig-channel-order.png" class="dw75 img-fluid"></a></p>
</section>
<section id="quantization-and-bit-depth" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="quantization-and-bit-depth">Quantization and bit depth</h2>
<p>An 8-bit channel has <span class="math inline">2^8 = 256</span> possible values per pixel. That is the usual case. Medical and scientific imaging often use 16 bits, which is 65,536 levels.</p>
<p>Fewer levels means visible <strong>banding</strong>: smooth gradients become flat steps. It shows up in the smooth regions first, because that is where neighbouring pixels would otherwise differ by only one or two levels.</p>
<p><a href="images/fig-quantization.png" class="zoom" target="_blank"><img src="images/fig-quantization.png" class="dw100 img-fluid"></a></p>
</section>
<section id="dynamic-range-and-normalization" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="dynamic-range-and-normalization">Dynamic range and normalization</h2>
<p><strong>Dynamic range</strong> is the span between the darkest and brightest values a sensor can record. Push past either end and the values <strong>clip</strong>: everything brighter than the maximum records as 255, everything darker than the minimum records as 0.</p>
<p>Clipped values are gone. Scaling the image back down afterwards does not return them, because the differences that distinguished them were never recorded.</p>
<p><a href="images/fig-dynamic-range.png" class="zoom" target="_blank"><img src="images/fig-dynamic-range.png" class="dw100 img-fluid"></a></p>
<p>In the overexposed panel, <strong>65.9%</strong> of all subpixel values are pinned at exactly 255. In the underexposed panel, <strong>37.7%</strong> are at or below 16.</p>
</section>
<section id="why-models-normalize-their-inputs" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-models-normalize-their-inputs">Why models normalize their inputs</h2>
<p>Week 5 covered the reason: when inputs sit on very different scales, one learning rate cannot suit all of them. Images have a milder version of the same problem, so the convention is to <strong>standardize</strong> each channel, meaning subtract a mean and divide by a standard deviation.</p>
<p><span class="math display">x' = \frac{x - \mu_c}{\sigma_c}</span></p>
<p>The ImageNet statistics are the ones you will meet most often, because most pretrained backbones are ImageNet classifiers. They are <strong>not</strong> universal:</p>
<p><a href="images/fig-preprocessing.png" class="zoom" target="_blank"><img src="images/fig-preprocessing.png" class="dw92 img-fluid"></a></p>
<p>So do not hard-code the constants. <code>weights.transforms()</code> gives you the exact preprocessing those weights were trained with. Next week we measure what happens when you get this wrong.</p>
</section>
<section id="resolution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="resolution">Resolution</h2>
<p>Resolution is <strong>sampling density</strong>: how many measurements you take across the scene. More samples means more detail, more memory, and more compute.</p>
<p>Downsampling discards information permanently.</p>
<p><a href="images/fig-resolution.png" class="zoom" target="_blank"><img src="images/fig-resolution.png" class="dw100 img-fluid"></a></p>
</section>
<section id="upsampling-does-not-undo-downsampling" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="upsampling-does-not-undo-downsampling">Upsampling does not undo downsampling</h2>
<p>Interpolation fills in plausible values between the samples you kept. It cannot recover the samples you threw away.</p>
<p><a href="images/fig-upsample.png" class="zoom" target="_blank"><img src="images/fig-upsample.png" class="dw90 img-fluid"></a></p>
<p>Bilinear interpolation gives you a smooth guess, nearest-neighbour gives you blocks, and neither gives you the whiskers back. Keep this in mind for next week: segmentation networks have to upsample, and this is the problem they are fighting.</p>
</section>
<section id="aliasing" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="aliasing">Aliasing</h2>
<p><strong>Aliasing</strong> is when detail finer than your sampling grid shows up as a different, coarser pattern that was never in the scene. The fix is to <strong>blur before you shrink</strong>, so detail too fine to represent is gone before it can masquerade as something coarser.</p>
<p><a href="images/fig-aliasing.png" class="zoom" target="_blank"><img src="images/fig-aliasing.png" class="dw89 img-fluid"></a></p>
<p>Without a filter the whiskers break into speckles and the coat turns to noise. In torchvision, <code>transforms.Resize(antialias=True)</code> is the default now and did not used to be.</p>
</section>
<section id="data-augmentation" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="data-augmentation">Data augmentation</h2>
<p><strong>Data augmentation</strong> is applying random, label-preserving transformations to training images, so the model sees a different version of each example every epoch.</p>
<p>It is a regularizer. Week 5 covered dropout and weight decay, which constrain the model. Augmentation works on the other side: it enlarges the training distribution.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torchvision <span class="im">import</span> transforms <span class="im">as</span> T</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>train_tf <span class="op">=</span> T.Compose([               <span class="co"># random, different every epoch</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    T.RandomResizedCrop(<span class="dv">224</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    T.RandomHorizontalFlip(),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    T.ColorJitter(brightness<span class="op">=</span><span class="fl">0.2</span>, contrast<span class="op">=</span><span class="fl">0.2</span>),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    T.ToTensor(),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    T.Normalize(mean, std),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>eval_tf <span class="op">=</span> T.Compose([                <span class="co"># deterministic, always the same</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    T.Resize(<span class="dv">256</span>), T.CenterCrop(<span class="dv">224</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    T.ToTensor(),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    T.Normalize(mean, std),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The two pipelines are <strong>different on purpose</strong>. Randomness at evaluation time would make your validation score depend on the dice roll.</p>
</section>
<section id="augmentation-applied" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="augmentation-applied">Augmentation, applied</h2>
<p><a href="images/fig-augmentation.png" class="zoom" target="_blank"><img src="images/fig-augmentation.png" class="dw100 img-fluid"></a></p>
<p>Every panel still shows a dog and two cats, which is the requirement: the transformation must not change the label.</p>
<p>That requirement is easy to break. A horizontal flip is safe for animals and <strong>wrong for handwritten digits and text</strong>, where it changes what the symbol is. A 180 degree rotation is safe for satellite imagery and wrong for street scenes. Augmentation choices are claims about which variations your task should ignore.</p>
</section>
<section id="automatic-augmentation-policies" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="automatic-augmentation-policies">Automatic augmentation policies</h2>
<p>The pipeline two slides ago was hand-written. Which transforms, at what strength? That literature moved toward <strong>less</strong> tuning, not more.</p>
<ul>
<li><strong>AutoAugment</strong> (2019) searched for a policy with reinforcement learning, at a cost of thousands of GPU hours, and published one policy per dataset. <code>torchvision</code> ships the three it found.</li>
<li><strong>RandAugment</strong> (2020) showed the search was mostly unnecessary: pick 2 transforms at random from a list of 14 and apply both at one strength.</li>
<li><strong>TrivialAugment</strong> (2021) removed even those two numbers. One random transform at one random strength per image, and nothing to tune.</li>
</ul>
<p><a href="images/fig-augment-policies.png" class="zoom" target="_blank"><img src="images/fig-augment-policies.png" class="dw92 img-fluid"></a></p>
</section>
<section id="what-augmentation-is-worth-measured" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-augmentation-is-worth-measured">What augmentation is worth, measured</h2>
<p><code>torchvision</code> published the recipe that took ResNet-50 from <strong>76.13% to 80.86%</strong> on ImageNet with the architecture completely unchanged, and the contribution of each step.</p>
<p><a href="images/fig-recipe-ablation.png" class="zoom" target="_blank"><img src="images/fig-recipe-ablation.png" class="dw100 img-fluid"></a></p>
<p>Augmentation accounts for <strong>1.08 of the 4.73 points</strong>. The largest single step is longer training, and that only pays off because the augmentation is strong enough to keep a longer run from overfitting. In this recipe, the aggressive and untuned <code>TrivialAugmentWide</code> beat both AutoAugment and RandAugment.</p>
<p><strong>Mixup</strong> and <strong>CutMix</strong> break the label-preserving rule on purpose: they combine two images and combine their labels in the same proportion, so the target becomes <code>0.7 cat + 0.3 dog</code> rather than one class.</p>
</section>
</section>
<section id="convolution" class="level1">
<h1>Convolution</h1>
<section id="why-a-fully-connected-layer-is-wrong-for-images" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-a-fully-connected-layer-is-wrong-for-images">Why a fully connected layer is wrong for images</h2>
<p>Take a 224x224 colour image, which is the standard size for pretrained models, and send it to a modest hidden layer of 1024 units.</p>
<div id="b5a250f0" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>fc   <span class="op">=</span> nn.Linear(<span class="dv">224</span> <span class="op">*</span> <span class="dv">224</span> <span class="op">*</span> <span class="dv">3</span>, <span class="dv">1024</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>conv <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>n_fc   <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> fc.parameters())</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>n_conv <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> conv.parameters())</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Linear(224*224*3, 1024)  </span><span class="sc">{</span>n_fc<span class="sc">:&gt;12,}</span><span class="ss"> parameters"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Conv2d(3, 32, 3)         </span><span class="sc">{</span>n_conv<span class="sc">:&gt;12,}</span><span class="ss"> parameters"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ratio                    </span><span class="sc">{</span>n_fc <span class="op">/</span> n_conv<span class="sc">:&gt;12,.0f}</span><span class="ss">x"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear(224*224*3, 1024)   154,141,696 parameters
Conv2d(3, 32, 3)                  896 parameters
ratio                         172,033x</code></pre>
</div>
</div>
</section>
<section id="two-problems-not-one" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="two-problems-not-one">Two problems, not one</h2>
<p><strong>The parameter count.</strong> 154 million parameters in one layer. That is more than VGG-16 has in its entirety, and it is the first layer of a network that has not done anything yet.</p>
<p><strong>The one that matters more.</strong> A dense layer learns an independent weight for every input position. If it learns to detect a vertical edge in the top left, it has learned nothing about vertical edges in the bottom right. That knowledge is not shared, so it must be learned again, from separate examples, for every position.</p>
<p>An edge is an edge wherever it appears. That is a fact about images, and it is a fact a dense layer cannot use.</p>
<p>Convolution is the layer that uses it. Two ideas do all the work:</p>
<ul>
<li><strong>Locality.</strong> A unit looks at a small neighbourhood, not the whole image.</li>
<li><strong>Weight sharing.</strong> The same small set of weights is applied at every position.</li>
</ul>
</section>
<section id="the-convolution-operation" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-convolution-operation">The convolution operation</h2>
<p>A small grid of weights, the <strong>kernel</strong>, slides across the input. At each position it multiplies the overlapping values elementwise and sums them. That single number becomes one output value.</p>
<p><a href="images/fig-conv-anim.gif" class="zoom" target="_blank"><img src="images/fig-conv-anim.gif" class="dw80 img-fluid"></a></p>
<p>A 5x5 input and a 3x3 kernel give a 3x3 output, because there are only 3x3 positions where the kernel fits entirely inside the input.</p>
</section>
<section id="definition-of-a-convolutional-layer" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="definition-of-a-convolutional-layer">Definition of a convolutional layer</h2>
<p>For a single-channel input <span class="math inline">X</span> and one <span class="math inline">K \times K</span> kernel <span class="math inline">W</span>:</p>
<p><span class="math display">
Y_{i,j} = \sum_{m=1}^{K}\sum_{n=1}^{K} X_{i+m-1,\;j+n-1}\, W_{m,n} + b
</span></p>
<p>The learned parameters are the <span class="math inline">K^2</span> kernel weights and one bias.</p>
<p><strong>Worked example.</strong> The patch, the kernel and the bias:</p>
<p><span class="math display">
X_{\text{patch}}=\begin{bmatrix} 1 &amp; 0 &amp; 2 \\ -1 &amp; 3 &amp; 1 \\
0 &amp; 2 &amp; -2 \end{bmatrix},\quad
W=\begin{bmatrix} 1 &amp; 0 &amp; -1 \\ 1 &amp; 0 &amp; -1 \\ 1 &amp; 0 &amp; -1
\end{bmatrix},\quad b=2
</span></p>
<p>Multiply elementwise, add the nine products, add the bias:</p>
<p><span class="math display">
Y = \big[(1)(1) + (2)(-1) + (-1)(1) + (1)(-1) + (0)(1) + (-2)(-1)\big] + 2
= -1
</span></p>
<p>Note what the kernel does: it subtracts the right column from the left column and ignores the middle. That is a vertical edge detector.</p>
</section>
<section id="convolution-over-channels" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="convolution-over-channels">Convolution over channels</h2>
<p>A real image has 3 channels, and a layer in the middle of a network may have 256. So a kernel is not <span class="math inline">K \times K</span>. It is <span class="math inline">K \times K \times C_{\text{in}}</span>, and it sums over channels as well as over space.</p>
<p>For <span class="math inline">C_{\text{in}}</span> input channels and <span class="math inline">F</span> filters:</p>
<p><span class="math display">
Y_{i,j,f} = \sum_{c=1}^{C_{\text{in}}}\sum_{m=1}^{K}\sum_{n=1}^{K}
X_{i+m-1,\;j+n-1,\;c}\, W_{m,n,c,f} + b_f
</span></p>
<p><a href="images/cnn-multi-channel-cnn.png" class="zoom" target="_blank"><img src="images/cnn-multi-channel-cnn.png" class="dw60 img-fluid"></a></p>
<p>So one filter has <span class="math inline">K^2 C_{\text{in}}</span> weights and one bias, and a layer with <span class="math inline">F</span> filters has <span class="math inline">F(K^2 C_{\text{in}} + 1)</span> parameters in total. That formula is worth memorizing; it is on the formula sheet.</p>
</section>
<section id="filters-and-feature-maps" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="filters-and-feature-maps">Filters and feature maps</h2>
<p>One filter produces <strong>one</strong> output channel, called a <strong>feature map</strong>. It records how strongly that filter responded at every position.</p>
<p>A layer with <span class="math inline">F</span> filters produces <span class="math inline">F</span> feature maps, stacked into one output tensor. Different filters learn to respond to different things.</p>
<div id="e592a3d1" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.zeros(<span class="dv">7</span>, <span class="dv">7</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>:<span class="dv">6</span>, <span class="dv">3</span>] <span class="op">=</span> <span class="fl">1.0</span>     <span class="co"># a vertical line</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">4</span>, <span class="dv">1</span>:<span class="dv">6</span>] <span class="op">=</span> <span class="fl">1.0</span>     <span class="co"># a horizontal line</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>k_vert  <span class="op">=</span> torch.tensor([[<span class="fl">1.</span>, <span class="fl">0.</span>, <span class="op">-</span><span class="fl">1.</span>]] <span class="op">*</span> <span class="dv">3</span>)            <span class="co"># left minus right</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>k_horiz <span class="op">=</span> k_vert.T.contiguous()                        <span class="co"># top minus bottom</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>y_vert  <span class="op">=</span> F.conv2d(x[<span class="va">None</span>, <span class="va">None</span>], k_vert[<span class="va">None</span>, <span class="va">None</span>])[<span class="dv">0</span>, <span class="dv">0</span>]</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>y_horiz <span class="op">=</span> F.conv2d(x[<span class="va">None</span>, <span class="va">None</span>], k_horiz[<span class="va">None</span>, <span class="va">None</span>])[<span class="dv">0</span>, <span class="dv">0</span>]</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="fl">4.2</span>))</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a, (d, t) <span class="kw">in</span> <span class="bu">zip</span>(ax, [(x, <span class="st">"input: a cross"</span>),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>                          (y_vert, <span class="st">"vertical-edge filter"</span>),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>                          (y_horiz, <span class="st">"horizontal-edge filter"</span>)]):</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    a.imshow(d, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, vmin<span class="op">=-</span><span class="dv">3</span>, vmax<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    a.set_title(t)<span class="op">;</span> a.set_xticks([])<span class="op">;</span> a.set_yticks([])</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"two filters, same input, two different feature maps"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05-convolutional-networks_files/figure-html/cell-6-output-1.png" width="1209" height="407" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>two filters, same input, two different feature maps</code></pre>
</div>
</div>
</section>
<section id="a-hand-set-filter-on-a-real-image" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="a-hand-set-filter-on-a-real-image">A hand-set filter on a real image</h2>
<p>Nine numbers, chosen by hand, no training at all.</p>
<p><a href="images/fig-sobel.png" class="zoom" target="_blank"><img src="images/fig-sobel.png" class="dw70 img-fluid"></a></p>
<p>This is what “feature detector” means concretely. A CNN does not get these kernels from you. It starts from random values and the gradient of the loss moves them toward whatever is useful, which in the first layer turns out to look a lot like this.</p>
</section>
<section id="weight-sharing-and-translation-equivariance" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="weight-sharing-and-translation-equivariance">Weight sharing and translation equivariance</h2>
<p>The same kernel is applied at every position, so the layer has <span class="math inline">K^2
C_{\text{in}} + 1</span> parameters no matter how large the image is. A 4K image and a thumbnail use the same weights.</p>
<p>The second consequence has a name. <strong>Translation equivariance</strong> means that if you shift the input, the output shifts by the same amount:</p>
<p><span class="math display">
\text{conv}(\text{shift}(X)) = \text{shift}(\text{conv}(X))
</span></p>
<p>Be careful with the vocabulary, because the two words get mixed up constantly:</p>
<ul>
<li><strong>Equivariance</strong>: the output moves with the input. Convolution has this.</li>
<li><strong>Invariance</strong>: the output does not change when the input moves. Convolution does <strong>not</strong> have this. Pooling adds a little, and global pooling at the end of the network adds a lot.</li>
</ul>
<p>Equivariance is the useful property for a feature extractor. You want to know <em>where</em> the edge is, not just that there is one somewhere.</p>
</section>
<section id="padding-and-output-size" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="padding-and-output-size">Padding and output size</h2>
<p>Without padding, each convolution shrinks the image by <span class="math inline">K-1</span> pixels, so a stack of layers runs out of image. <strong>Padding</strong> adds a border of zeros so the output can keep the input’s size.</p>
<p><span class="math display">
H_{\text{out}}=\left\lfloor\frac{H+2P-K}{S}\right\rfloor+1,
\qquad
W_{\text{out}}=\left\lfloor\frac{W+2P-K}{S}\right\rfloor+1
</span></p>
<p><span class="math inline">H, W</span> are the input height and width, <span class="math inline">K</span> the kernel size, <span class="math inline">P</span> the padding on each side, <span class="math inline">S</span> the stride, and <span class="math inline">\lfloor\cdot\rfloor</span> rounds down.</p>
<p><strong>Two cases worth knowing by heart.</strong></p>
<p><span class="math inline">K=3, P=1, S=1</span> keeps the size exactly: <span class="math inline">(H + 2 - 3) + 1 = H</span>. This is why 3x3 with padding 1 is everywhere.</p>
<p>ResNet’s first layer is <span class="math inline">K=7, P=3, S=2</span> on a 224 input: <span class="math inline">\lfloor(224 + 6 - 7)/2\rfloor + 1 = 112</span>. Halved.</p>
<p>And the earlier example, <span class="math inline">H=32, K=3, P=1, S=2</span>: <span class="math inline">\lfloor 31/2 \rfloor + 1 = 16</span>.</p>
</section>
<section id="stride" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="stride">Stride</h2>
<p><strong>Stride</strong> is how far the kernel moves between positions. Stride 1 visits every position; stride 2 skips every other one, which roughly halves the output’s height and width.</p>
<p><a href="images/fig-stride-anim.gif" class="zoom" target="_blank"><img src="images/fig-stride-anim.gif" class="dw80 img-fluid"></a></p>
<p>A 5x5 input with a 3x3 kernel at stride 2 gives a 2x2 output. Fewer positions means less compute and a smaller output, at the cost of skipping detail.</p>
</section>
<section id="pooling" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="pooling">Pooling</h2>
<p><strong>Pooling</strong> reduces spatial size with a fixed rule and no learned parameters. Max pooling takes the largest value in each window. Average pooling takes the mean.</p>
<p><a href="images/fig-pool-anim.gif" class="zoom" target="_blank"><img src="images/fig-pool-anim.gif" class="dw80 img-fluid"></a></p>
<p>Max pooling keeps the strongest response and discards where in the window it was, which is where a small amount of translation invariance comes from. Average pooling keeps a smoother summary.</p>
</section>
<section id="pooling-against-strided-convolution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="pooling-against-strided-convolution">Pooling against strided convolution</h2>
<p>Both shrink the feature map. They are not the same thing.</p>
<div class="columns contrast">
<div class="column">
<section id="pooling-1" class="level3 col-yes">
<h3 class="col-yes anchored" data-anchor-id="pooling-1">Pooling</h3>
<ul>
<li>No parameters. The rule is fixed before training.</li>
<li>Max pooling is nonlinear.</li>
<li>Cheap, and one less thing to learn.</li>
<li>Discards position within the window, on purpose.</li>
</ul>
</section>
</div><div class="column">
<section id="strided-convolution" class="level3 col-no">
<h3 class="col-no anchored" data-anchor-id="strided-convolution">Strided convolution</h3>
<ul>
<li>Learns how to downsample.</li>
<li>One operation instead of two.</li>
<li>More parameters and more compute.</li>
<li>Modern architectures mostly prefer this.</li>
</ul>
</section>
</div>
</div>
<p>The practical summary: classification benefits from throwing position away, so pooling is fine and common. Segmentation and detection need position, so aggressive pooling hurts them, and that tension drives most of next week’s architectures.</p>
</section>
<section id="receptive-field" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="receptive-field">Receptive field</h2>
<p>The <strong>receptive field</strong> of an output unit is the region of the <strong>input</strong> that can affect its value.</p>
<p>One 3x3 layer gives a 3x3 receptive field. Stack another and it is 5x5. Each 3x3 layer with stride 1 adds 2.</p>
<p><a href="images/fig-receptive-field.png" class="zoom" target="_blank"><img src="images/fig-receptive-field.png" class="dw85 img-fluid"></a></p>
<p>So why not use one big kernel instead of stacking small ones?</p>
</section>
<section id="why-small-kernels-stacked" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-small-kernels-stacked">Why small kernels, stacked</h2>
<p>Two 3x3 convolutions and one 5x5 convolution see the same 5x5 input region. Compare them at 64 input and 64 output channels:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Parameters</th>
<th>Receptive field</th>
<th>Nonlinearities</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One <code>Conv2d(64, 64, 5)</code></td>
<td>102,464</td>
<td>5x5</td>
<td>1</td>
</tr>
<tr class="even">
<td>Two <code>Conv2d(64, 64, 3)</code></td>
<td><strong>73,856</strong></td>
<td>5x5</td>
<td><strong>2</strong></td>
</tr>
</tbody>
</table>
<p>The stack is <strong>28% smaller</strong> and puts an activation function in the middle, so it can represent more. This is the observation VGG was built on, and it is why 3x3 is the default kernel size in almost every architecture since 2014.</p>
<p>The cost is depth. More layers means a longer path for gradients, which is the problem residual connections were invented to solve.</p>
</section>
<section id="nn.conv2d" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="nn.conv2d"><code>nn.Conv2d</code></h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(in_channels, out_channels, kernel_size,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>          stride<span class="op">=</span><span class="dv">1</span>, padding<span class="op">=</span><span class="dv">0</span>, bias<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>in_channels</code> must match the channel count of whatever comes in. <code>out_channels</code> is the number of filters, so it is the channel count coming out.</p>
<div id="d0cb30eb" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>layer <span class="op">=</span> nn.Conv2d(in_channels<span class="op">=</span><span class="dv">3</span>, out_channels<span class="op">=</span><span class="dv">16</span>, kernel_size<span class="op">=</span><span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">8</span>, <span class="dv">3</span>, <span class="dv">32</span>, <span class="dv">32</span>)       <span class="co"># NCHW: 8 images, 3 channels, 32x32</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> layer(x)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"input "</span>, <span class="bu">tuple</span>(x.shape))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"output"</span>, <span class="bu">tuple</span>(y.shape))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"weight"</span>, <span class="bu">tuple</span>(layer.weight.shape), <span class="st">"= (out, in, K, K)"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"bias  "</span>, <span class="bu">tuple</span>(layer.bias.shape))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>by_hand <span class="op">=</span> <span class="dv">16</span> <span class="op">*</span> (<span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> <span class="dv">3</span> <span class="op">+</span> <span class="dv">1</span>)      <span class="co"># F * (K*K*C_in + 1)</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>counted <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> layer.parameters())</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"F * (K*K*C_in + 1) = 16 * (27 + 1) = </span><span class="sc">{</span>by_hand<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"actual parameter count            = </span><span class="sc">{</span>counted<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>input  (8, 3, 32, 32)
output (8, 16, 32, 32)

weight (16, 3, 3, 3) = (out, in, K, K)
bias   (16,)

F * (K*K*C_in + 1) = 16 * (27 + 1) = 448
actual parameter count            = 448</code></pre>
</div>
</div>
</section>
</section>
<section id="building-a-cnn" class="level1">
<h1>Building a CNN</h1>
<section id="the-shape-of-a-cnn" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-shape-of-a-cnn">The shape of a CNN</h2>
<p>Almost every convolutional classifier is the same three-part skeleton.</p>
<p><strong>Body.</strong> A block repeated several times:</p>
<pre><code>Conv2d -&gt; BatchNorm2d -&gt; ReLU  (often twice)  -&gt; downsample</code></pre>
<p><strong>Downsampling</strong> between blocks, by pooling or by stride.</p>
<p><strong>Head.</strong> Collapse the spatial dimensions and produce one score per class.</p>
<p>The pattern across the body is that <strong>spatial size falls while channel count rises</strong>. A 224x224x3 input becomes 7x7x512 in ResNet-18.</p>
<p>That trade is the whole design. You give up knowing exactly <em>where</em> things are and buy the ability to represent <em>what</em> is there. Early layers know position precisely and meaning barely; late layers know meaning well and position only coarsely.</p>
</section>
<section id="activations-in-convolutional-networks" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="activations-in-convolutional-networks">Activations in convolutional networks</h2>
<p>Week 2 covered why a nonlinearity is needed at all: without one, stacked linear layers collapse into a single linear layer. Nothing about that changes here.</p>
<p>What changes is which one you reach for.</p>
<p><span class="math display">
\mathrm{ReLU}(x)=\max(0,x), \qquad
\mathrm{LeakyReLU}(x)=\max(\alpha x, x), \qquad
\mathrm{GELU}(x)=x\,\Phi(x)
</span></p>
<p><strong>ReLU is the default</strong> in convolutional networks. Sigmoid and tanh saturate: once a unit’s input is large, the derivative is near zero and the gradient stops. In a 50-layer network that is fatal, and it is the same vanishing gradient problem from Week 5, arriving through the activation function instead of through the weights.</p>
<p>LeakyReLU keeps a small slope for negative inputs, so a unit that has gone negative can still recover. GELU is smoother and is standard in transformers, which is Week 9.</p>
</section>
<section id="batch-normalization" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="batch-normalization">Batch normalization</h2>
<p><strong>Batch normalization</strong> standardizes each channel’s activations using the mean and variance computed across the current mini-batch, then applies a learned scale and shift.</p>
<p><span class="math display">
\hat{x}=\frac{x-\mu_{B}}{\sqrt{\sigma_{B}^{2}+\epsilon}},
\qquad y=\gamma\hat{x}+\beta
</span></p>
<p><span class="math inline">\mu_B</span> and <span class="math inline">\sigma^2_B</span> come from the batch. <span class="math inline">\gamma</span> and <span class="math inline">\beta</span> are learned, one pair per channel, so the layer can undo the normalization if that is what minimizes the loss.</p>
<p>What it buys you: higher learning rates without diverging, much less sensitivity to how you initialized, and faster convergence. It is in essentially every CNN from 2015 onward.</p>
<p>There is a catch, and it is the kind that wastes an afternoon.</p>
</section>
<section id="batchnorm-behaves-differently-in-eval-mode" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="batchnorm-behaves-differently-in-eval-mode">BatchNorm behaves differently in eval mode</h2>
<p>At test time you may have one image, so there is no batch to compute statistics from. BatchNorm therefore keeps a <strong>running estimate</strong> of the mean and variance during training, and uses those in <code>eval()</code> mode instead of batch statistics.</p>
<p>The estimate is an exponential moving average, so it <strong>lags</strong> the weights.</p>
<p><a href="images/fig-batchnorm-eval.png" class="zoom" target="_blank"><img src="images/fig-batchnorm-eval.png" class="dw75 img-fluid"></a></p>
<p>Both curves are the same weights on the same images. Only <code>eval()</code> wobbles, because only <code>eval()</code> uses the lagging statistics.</p>
<p>If validation accuracy is wild while training accuracy is smooth, suspect the BatchNorm statistics before the model. Decaying the learning rate settles them, because the weights stop moving.</p>
</section>
<section id="x1-convolutions" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="x1-convolutions">1x1 convolutions</h2>
<p>A 1x1 kernel looks like it cannot do anything. It sees one spatial position.</p>
<p>But it still sums over <strong>channels</strong>. A <code>Conv2d(256, 64, 1)</code> takes the 256-number vector at each position and maps it to a 64-number vector, using the same mapping at every position. It is a fully connected layer applied across channels only.</p>
<p>That makes it the cheap way to change channel count:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(<span class="dv">256</span>, <span class="dv">64</span>, kernel_size<span class="op">=</span><span class="dv">1</span>)   <span class="co"># 256*64 + 64 = 16,448 parameters</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(<span class="dv">256</span>, <span class="dv">64</span>, kernel_size<span class="op">=</span><span class="dv">3</span>)   <span class="co"># 9*256*64 + 64 = 147,520 parameters</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Nine times fewer parameters for the job of “fewer channels now”.</p>
<p>This shows up three times in the next section. Inception uses 1x1 to shrink channels before an expensive 5x5. ResNet’s bottleneck blocks use 1x1 to go down and back up around a 3x3. MobileNet’s pointwise convolution <strong>is</strong> a 1x1.</p>
</section>
<section id="global-average-pooling-against-flatten" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="global-average-pooling-against-flatten">Global average pooling against flatten</h2>
<p>The head has to turn a <code>(C, H, W)</code> feature map into <code>num_classes</code> scores. Two ways.</p>
<p><strong>Flatten, then a linear layer.</strong> VGG-16 ends with a 7x7x512 feature map, flattens it to 25,088 numbers, and sends that to a 4096-unit layer. That one layer has over 102 million parameters, which is most of VGG’s 138 million. And because 25,088 is baked into the layer’s shape, the network only accepts 224x224 inputs.</p>
<p><strong>Global average pooling.</strong> Average each channel over all positions. A 7x7x512 map becomes 512 numbers, with no parameters at all, then one <code>Linear(512, 10)</code>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(), nn.Linear(<span class="dv">512</span>, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This is what ResNet and everything after it does. Far fewer parameters, less overfitting, and the network accepts any input size large enough to survive the downsampling.</p>
</section>
<section id="residual-connections" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="residual-connections">Residual connections</h2>
<div class="columns">
<div class="column" style="width:62%;">
<p>A <strong>residual connection</strong> adds a layer block’s input to its output:</p>
<p><span class="math display">
\mathbf{y}=\mathcal{F}(\mathbf{x})+\mathbf{x}
</span></p>
<p>So the block only has to learn the <strong>difference</strong> between what it is given and what is wanted, which is where “residual” comes from.</p>
<p>Why it helps is easiest to see in the backward pass. The derivative of <span class="math inline">\mathbf{y}</span> with respect to <span class="math inline">\mathbf{x}</span> is</p>
<p><span class="math display">
\frac{\partial \mathbf{y}}{\partial \mathbf{x}}
= \frac{\partial \mathcal{F}}{\partial \mathbf{x}} + I
</span></p>
<p>That <span class="math inline">+I</span> is the point. Even if the block’s own term is tiny, the gradient still has a route back through the identity. Multiply many such terms together and you get sums involving 1 instead of products of small numbers.</p>
<p>If the shapes do not match, a 1x1 convolution on the shortcut fixes them.</p>
</div><div class="column" style="width:38%;">
<p><a href="images/residual-block.png" class="zoom" target="_blank"><img src="images/residual-block.png" class="dh420 img-fluid"></a></p>
</div>
</div>
</section>
<section id="a-small-cnn-in-pytorch" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="a-small-cnn-in-pytorch">A small CNN in PyTorch</h2>
<div id="40650450" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cnn <span class="op">=</span> nn.Sequential(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">1</span>, <span class="dv">32</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.BatchNorm2d(<span class="dv">32</span>), nn.ReLU(),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    nn.MaxPool2d(<span class="dv">2</span>),                                        <span class="co"># 28 -&gt; 14</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">32</span>, <span class="dv">64</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.BatchNorm2d(<span class="dv">64</span>), nn.ReLU(),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    nn.MaxPool2d(<span class="dv">2</span>),                                        <span class="co"># 14 -&gt; 7</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">64</span>, <span class="dv">128</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.BatchNorm2d(<span class="dv">128</span>), nn.ReLU(),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    nn.Conv2d(<span class="dv">128</span>, <span class="dv">96</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>), nn.BatchNorm2d(<span class="dv">96</span>), nn.ReLU(),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    nn.AdaptiveAvgPool2d(<span class="dv">1</span>), nn.Flatten(), nn.Linear(<span class="dv">96</span>, <span class="dv">10</span>),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> torch.randn(<span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">28</span>, <span class="dv">28</span>)        <span class="co"># a Fashion-MNIST batch of 4</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> cnn:</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    z <span class="op">=</span> layer(z)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(layer, (nn.Conv2d, nn.MaxPool2d, nn.Linear,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>                          nn.AdaptiveAvgPool2d, nn.Flatten)):</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>layer<span class="sc">.</span>__class__<span class="sc">.</span><span class="va">__name__</span><span class="sc">:18s}</span><span class="ss"> -&gt; </span><span class="sc">{</span><span class="bu">tuple</span>(z.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"total parameters: </span><span class="sc">{</span><span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> cnn.parameters())<span class="sc">:,}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Conv2d             -&gt; (4, 32, 28, 28)
MaxPool2d          -&gt; (4, 32, 14, 14)
Conv2d             -&gt; (4, 64, 14, 14)
MaxPool2d          -&gt; (4, 64, 7, 7)
Conv2d             -&gt; (4, 128, 7, 7)
Conv2d             -&gt; (4, 96, 7, 7)
AdaptiveAvgPool2d  -&gt; (4, 96, 1, 1)
Flatten            -&gt; (4, 96)
Linear             -&gt; (4, 10)

total parameters: 204,970</code></pre>
</div>
</div>
</section>
<section id="the-same-budget-two-ways" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-same-budget-two-ways">The same budget, two ways</h2>
<p>Lab 4’s model was <code>Linear(784, 256)</code> then <code>Linear(256, 10)</code>: <strong>203,530</strong> parameters. The CNN on the previous slide has <strong>204,970</strong>. Within 1% of each other, so capacity is not the variable.</p>
<p>Same 12,000 Fashion-MNIST training images, same 2,000 validation images, same AdamW at the same learning rate, same cosine schedule, same 18 epochs. The only difference is the architecture.</p>
<p><a href="images/fig-cnn-vs-mlp.png" class="zoom" target="_blank"><img src="images/fig-cnn-vs-mlp.png" class="dw95 img-fluid"></a></p>
<p><strong>0.8735 against 0.9200.</strong> The CNN is 4.7 points better, which is an error rate of 8.0% instead of 12.7%, so <strong>37% of the remaining errors are gone</strong>. At the same parameter count, on the same data, in the same time.</p>
<p>That difference is locality and weight sharing. Nothing else changed.</p>
</section>
<section id="what-the-first-layer-learns" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-the-first-layer-learns">What the first layer learns</h2>
<p>These are the actual 64 kernels in the first layer of a trained ResNet-18, each one 7x7x3, shown as colour patches. 9,408 numbers in total.</p>
<p><a href="images/fig-resnet-filters.png" class="zoom" target="_blank"><img src="images/fig-resnet-filters.png" class="dw95 img-fluid"></a></p>
<p>Nobody specified these. They are oriented edges at various angles, and colour-opponent blobs. Minimizing cross entropy on ImageNet produced them, and they look remarkably like the hand-set Sobel kernel from earlier, and remarkably like what the early visual system in mammals does.</p>
</section>
<section id="what-the-deeper-layers-hold" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-the-deeper-layers-hold">What the deeper layers hold</h2>
<p>The same network, run on our image. Six strongest channels at four depths.</p>
<p><a href="images/fig-feature-maps.png" class="zoom" target="_blank"><img src="images/fig-feature-maps.png" class="dh480 img-fluid"></a></p>
<p><code>layer1</code> is 56x56 and still looks like the photograph. <code>layer4</code> is 7x7 and does not. Position has been traded for meaning, exactly as the skeleton slide described, and the 512 numbers per position at the end are what a classifier head actually reads.</p>
</section>
</section>
<section id="architectures-that-mattered" class="level1">
<h1>Architectures that mattered</h1>
<section id="timeline" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="timeline">Timeline</h2>
<p><a href="images/jfh-timeline.png" class="zoom" target="_blank"><img src="images/jfh-timeline.png" class="dh480 img-fluid"></a></p>
<p>Six ideas, roughly one per architecture, and each one is still in use. The rest of this section is what each contributed.</p>
</section>
<section id="lenet-5-1989-to-1998" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="lenet-5-1989-to-1998">LeNet-5, 1989 to 1998</h2>
<p><a href="images/jfh-lenet5.png" class="zoom" target="_blank"><img src="images/jfh-lenet5.png" class="dw75 img-fluid"></a></p>
<p>Yann LeCun’s network for reading handwritten digits on cheques. Roughly 60,000 parameters.</p>
<p>Everything structural is already here: convolution, subsampling, repeated blocks, then fully connected layers to the output. What it lacked was data, compute, and ReLU. It used tanh and was trained on CPUs in the 1990s.</p>
<p>It worked, in production, on real cheques. Then the field moved to other methods for over a decade.</p>
</section>
<section id="alexnet-2012" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="alexnet-2012">AlexNet, 2012</h2>
<div class="columns">
<div class="column" style="width:56%;">
<p>The ImageNet result that restarted the field. Top-5 error fell from about 26% to about 16% in one year, which was not an incremental improvement.</p>
<p>What was actually new:</p>
<ul>
<li><strong>ReLU</strong> instead of tanh, so deep stacks trained in reasonable time.</li>
<li><strong>Two GPUs</strong>, which is why the published diagram is split into two parallel streams.</li>
<li><strong>Dropout</strong> in the fully connected layers.</li>
<li><strong>Augmentation</strong>: random crops and flips.</li>
<li><strong>ImageNet</strong>: 1.2 million labelled images, which did not exist before.</li>
</ul>
<p>61.1 million parameters, 56.5% top-1 accuracy.</p>
</div><div class="column" style="width:44%;">
<p><a href="images/jfh-alexnet.png" class="zoom" target="_blank"><img src="images/jfh-alexnet.png" class="dh420 img-fluid"></a></p>
</div>
</div>
<p>The architecture was not the breakthrough. The combination of enough data, enough compute, and ReLU was.</p>
</section>
<section id="vgg-2014" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="vgg-2014">VGG, 2014</h2>
<p><a href="images/cnn-kernels-filters.png" class="zoom" target="_blank"><img src="images/cnn-kernels-filters.png" class="dw85 img-fluid"></a></p>
<p>One design rule, applied uniformly: <strong>every convolution is 3x3 with padding 1</strong>, and you go deeper instead of wider. Downsampling is 2x2 max pooling. That is the whole architecture.</p>
<p>This is the slide from earlier made into a network: two 3x3 layers beat one 5x5 on parameters and on expressiveness, so use many small kernels.</p>
<p>VGG-16 has 16 weight layers and 138 million parameters, and <strong>102 million of them are in the first fully connected layer</strong>. The convolutional part is only about 15 million.</p>
</section>
<section id="vgg-16" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="vgg-16">VGG-16</h2>
<p><a href="images/vgg-16.png" class="zoom" target="_blank"><img src="images/vgg-16.png" class="dh500 img-fluid"></a></p>
</section>
<section id="vgg-configurations" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="vgg-configurations">VGG configurations</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p>The paper’s table of the family, from 11 to 19 weight layers. Reading it is a useful exercise: each column is one network, and the only thing that changes down a column is how many 3x3 convolutions sit in each block.</p>
<p>Two details worth noticing:</p>
<ul>
<li>The channel count doubles after each pooling stage: 64, 128, 256, 512, 512. Spatial size halves, channels double. That keeps the compute per block roughly constant and is a convention you will see everywhere.</li>
<li>All three fully connected layers are identical across every variant, which is where the parameters are.</li>
</ul>
</div><div class="column" style="width:54%;">
<p><a href="https://arxiv.org/pdf/1409.1556#page=3">[<img src="images/vgg-configurations.png" class="dh440 img-fluid">](images/vgg-configurations.png){target=“_blank” .zoom}</a></p>
</div>
</div>
</section>
<section id="inception-modules-2014" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="inception-modules-2014">Inception modules, 2014</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p>VGG makes you choose a kernel size for every layer. Inception’s answer is to stop choosing: run 1x1, 3x3, 5x5 and pooling <strong>in parallel</strong> on the same input, and concatenate the results along the channel axis. The network learns which branch to rely on.</p>
<p>Done naively this is expensive, because a 5x5 over 256 channels is a lot of multiplications. The fix is the 1x1 convolution from earlier: shrink the channel count first, then do the 5x5, then expand.</p>
<p>GoogLeNet stacked these and reached better accuracy than VGG with about <strong>7 million</strong> parameters against VGG’s 138 million.</p>
</div><div class="column" style="width:52%;">
<p><a href="images/jfh-inception.png" class="zoom" target="_blank"><img src="images/jfh-inception.png" class="dh460 img-fluid"></a></p>
</div>
</div>
</section>
<section id="the-degradation-problem" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-degradation-problem">The degradation problem</h2>
<p>By 2015 the obvious next move was more depth. It stopped working, and not for the reason you would guess.</p>
<p>The ResNet authors trained a plain 20-layer network and a plain 56-layer network on CIFAR-10. The 56-layer network was worse. Not just on test error, on <strong>training</strong> error.</p>
<p>That rules out overfitting, which is the usual suspect when a bigger model does worse. A model that overfits fits the training set <em>better</em>. This one fit it worse.</p>
<p>It is also not expressiveness. The 56-layer network can represent everything the 20-layer one can: set the extra 36 layers to the identity function. So a solution exists, with equal or better training error, and gradient descent did not find it.</p>
<p>The problem is <strong>optimization</strong>. Stacked nonlinear layers find it hard to learn the identity, and gradients attenuate on the way back through dozens of weight matrices.</p>
</section>
<section id="resnet-2015" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="resnet-2015">ResNet, 2015</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>The fix is to make the identity the <strong>default</strong> instead of something to be learned. Add the input back:</p>
<p><span class="math display">
\mathbf{y}=\mathcal{F}(\mathbf{x})+\mathbf{x}
</span></p>
<p>If a block has nothing useful to contribute, driving <span class="math inline">\mathcal{F}</span> to zero leaves the identity, and driving weights to zero is something gradient descent does easily.</p>
<p>Reading the diagram, which is the convention across the detection and segmentation papers next week:</p>
<ul>
<li><strong>Solid arrows</strong> are residual connections where the shapes already match.</li>
<li><strong>Dashed arrows</strong> are residual connections where they do not, so a 1x1 convolution with stride 2 fixes them.</li>
<li><strong><code>/2</code></strong> means stride 2, so that layer halves the spatial size.</li>
<li><strong><code>3x3 conv, 64</code></strong> means a 3x3 kernel with 64 filters.</li>
</ul>
<p>152 layers trained successfully. ResNet-50 is still a sensible default backbone in 2026.</p>
</div><div class="column" style="width:42%;">
<p><a href="https://arxiv.org/pdf/1512.03385#page=4">[<img src="images/resenet-diagram.png" class="dh480 img-fluid">](images/resenet-diagram.png){target=“_blank” .zoom}</a></p>
</div>
</div>
</section>
<section id="resnet-configurations" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="resnet-configurations">ResNet configurations</h2>
<p><a href="https://arxiv.org/pdf/1512.03385#page=5">[<img src="images/resnet-configurations.png" class="dw90 img-fluid">](images/resnet-configurations.png){target=“_blank” .zoom}</a></p>
<p>ResNet-18 and ResNet-34 use two 3x3 convolutions per block. ResNet-50 and above use a <strong>bottleneck</strong>: 1x1 down to fewer channels, 3x3 at that reduced width, then 1x1 back up. That is the third appearance of the 1x1 convolution, and it is what makes 50 and 101 layers affordable.</p>
<p>The naming is just the count of weight layers.</p>
</section>
<section id="densenet-2016" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="densenet-2016">DenseNet, 2016</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>One change from ResNet, and it is a single word. ResNet <strong>adds</strong> the shortcut:</p>
<p><span class="math display">
\mathbf{y} = \mathcal{F}(\mathbf{x}) + \mathbf{x}
</span></p>
<p>DenseNet <strong>concatenates</strong> it, and not just from the previous layer: every layer in a block receives the feature maps of all layers before it.</p>
<p><span class="math display">
\mathbf{y}_{\ell} =
\mathcal{F}_{\ell}\big([\mathbf{y}_0, \mathbf{y}_1, \dots,
\mathbf{y}_{\ell-1}]\big)
</span></p>
<p>Because features are reused rather than recomputed, each layer can be narrow. The <strong>growth rate</strong> is how many channels each layer adds, often just 32. <strong>Transition layers</strong> between blocks use 1x1 convolutions and pooling to stop the channel count exploding.</p>
<p>DenseNet-121 reaches 74.4% top-1 with 8.0 million parameters, beating ResNet-50 per parameter.</p>
</div><div class="column" style="width:48%;">
<p><a href="images/dense-block.png" class="zoom" target="_blank"><img src="images/dense-block.png" class="dh280 img-fluid"></a></p>
<p><a href="images/densenet-overview-diagram.png" class="zoom" target="_blank"><img src="images/densenet-overview-diagram.png" class="dw100 img-fluid"></a></p>
</div>
</div>
</section>
<section id="grouped-convolution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="grouped-convolution">Grouped convolution</h2>
<p>Needed before the next slide makes sense.</p>
<p>A normal convolution connects <strong>every</strong> input channel to every filter. A <strong>grouped</strong> convolution splits the channels into <span class="math inline">g</span> groups and keeps them separate: group 1’s filters only see group 1’s channels.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><a href="images/1-group-convolution.png" class="zoom" target="_blank"><img src="images/1-group-convolution.png" class="dw100 img-fluid"></a></p>
<p>One group. Every filter sees every channel.</p>
</div><div class="column" style="width:50%;">
<p><a href="images/2-group-convolution.png" class="zoom" target="_blank"><img src="images/2-group-convolution.png" class="dw100 img-fluid"></a></p>
<p>Two groups. Each half is independent, so the layer costs half as much.</p>
</div>
</div>
<p><code>nn.Conv2d(..., groups=g)</code>. AlexNet used two groups because it had to split across two GPUs. It turned out to be useful on its own.</p>
</section>
<section id="depthwise-separable-convolution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="depthwise-separable-convolution">Depthwise separable convolution</h2>
<p>Take grouping to its limit: one group per channel. Each filter now sees exactly one input channel, so it filters spatially without mixing channels at all. That is a <strong>depthwise</strong> convolution. A 1x1 convolution then does the mixing, and that is the <strong>pointwise</strong> step. Together they are a <strong>depthwise separable</strong> convolution.</p>
<div class="columns">
<div class="column" style="width:52%;">
<p><a href="images/depth-wise-seperable.png" class="zoom" target="_blank"><img src="images/depth-wise-seperable.png" class="dw100 img-fluid"></a></p>
</div><div class="column" style="width:48%;">
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one ordinary convolution</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(<span class="dv">64</span>, <span class="dv">64</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   36,928 parameters</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the separable pair</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(<span class="dv">64</span>, <span class="dv">64</span>, <span class="dv">3</span>, padding<span class="op">=</span><span class="dv">1</span>, groups<span class="op">=</span><span class="dv">64</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co">#      640 parameters</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>nn.Conv2d(<span class="dv">64</span>, <span class="dv">64</span>, <span class="dv">1</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co">#    4,160 parameters</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>36,928 against 4,800.</strong> The cost ratio is <span class="math inline">\frac{1}{N}+\frac{1}{K^2}</span>, so for 3x3 with many channels it approaches <span class="math inline">1/9</span>.</p>
</div>
</div>
<p>This is what makes MobileNet work: 3.5 million parameters and 71.9% top-1, which is <strong>better than VGG-16</strong> with 39 times fewer parameters.</p>
</section>
<section id="choosing-an-architecture" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="choosing-an-architecture">Choosing an architecture</h2>
<p>Every number here is torchvision’s own reported figure for its own pretrained weights.</p>
<p><a href="images/fig-arch-comparison.png" class="zoom" target="_blank"><img src="images/fig-arch-comparison.png" class="dw70 img-fluid"></a></p>
<p>Progress did not come from adding parameters. <strong>VGG-16</strong> has 138.4M and gets 71.6%; <strong>MobileNetV2</strong> has 3.5M and gets 71.9%. <strong>EfficientNet-B0</strong> has 5.3M and beats ResNet-50’s 25.6M.</p>
<p><strong>What to use.</strong> Pretrained ResNet-50 is the safe default. EfficientNet or ConvNeXt for more accuracy per parameter. MobileNet if it has to run on a phone. In all three cases you start from pretrained weights, which is where next week begins.</p>
</section>
</section>
<section id="wrap-up" class="level1">
<h1>Wrap-up</h1>
<section id="what-to-keep-from-today" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-to-keep-from-today">What to keep from today</h2>
<ol type="1">
<li><p><strong>An image is a tensor, and the conventions bite.</strong> HWC against CHW, RGB against BGR, <code>img[row, col]</code> against <code>(x, y)</code>. None of these raise an error when you get them wrong.</p></li>
<li><p><strong>Convolution is locality plus weight sharing.</strong> A small kernel applied at every position. That is the entire idea, and it bought 4.7 accuracy points over a dense network at the same parameter count.</p></li>
<li><p><strong>You can predict every shape.</strong> <span class="math inline">\lfloor (H + 2P - K)/S \rfloor + 1</span> for the spatial size, <span class="math inline">F(K^2 C_{\text{in}} + 1)</span> for the parameter count. If you cannot say what shape comes out of a layer, you cannot debug the network.</p></li>
<li><p><strong>Depth needed help to work.</strong> ResNet’s 56-layer network was worse than its 20-layer one on <em>training</em> error. Residual connections fixed an optimization problem, not a capacity problem.</p></li>
<li><p><strong>Smaller and smarter beat bigger.</strong> MobileNetV2 matches VGG-16 with 39 times fewer parameters.</p></li>
</ol>
</section>
<section id="next-week-detection-and-segmentation" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="next-week-detection-and-segmentation">Next week: detection and segmentation</h2>
<p>Today’s network answers one question about an image: which class. Next week is the three questions it cannot answer.</p>
<p><strong>How many, and where?</strong> That is object detection, and the hard part is that the answer has no fixed length. A classifier always emits one vector of scores. A detector has to emit a variable-length set of boxes.</p>
<p><strong>Which pixels?</strong> That is segmentation, and the hard part is the opposite of what we did today. We spent this whole lecture throwing spatial resolution away on purpose. Segmentation needs it back.</p>
<p>We will also not be training any of it from scratch. The first thing next week is <strong>transfer learning</strong>: starting from weights someone else paid for. Every detector and segmenter we look at is a pretrained backbone with a different head bolted on.</p>
</section>
<section id="supplemental-content" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="supplemental-content">Supplemental content</h2>
<p>These are <strong>optional</strong>. No graded work assumes you read them. Today’s deck condenses roughly four weeks of a computer vision course, so these are where the detail went.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>My DSAN 6500 computer vision course</strong></p>
<ul>
<li><a href="https://benjaminhoughton.georgetown.domains/computer-vision/week-1/week-1.html">Image and audio data</a></li>
<li><a href="https://benjaminhoughton.georgetown.domains/computer-vision/week-4/week-4.html">CNNs and modern architectures</a></li>
</ul>
<p>The week 1 page goes much further on file formats, colour spaces and audio. The week 4 page has the DenseNet and MobileNet configuration tables we skipped, plus a worked transfer learning example.</p>
</div><div class="column" style="width:50%;">
<p><strong>Prof.&nbsp;Hickman’s centralized lecture content</strong></p>
<ul>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/computer-vision/convolutional-neural-networks/CNN-model-history/notes.html">CNN model history</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/computer-vision/modern-cnn-architectures/modern-architectures/notes.html">Modern CNN architectures</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/computer-vision/convolutional-neural-networks/convolution-operation-examples/notes.html">Convolution operation examples</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/computer-vision/convolutional-neural-networks/pytorch-conv-layer-examples/notes.html">PyTorch conv layer examples</a></li>
</ul>
<p><strong>PyTorch’s own documentation</strong></p>
<ul>
<li><a href="https://pytorch.org/vision/stable/auto_examples/transforms/plot_transforms_illustrations.html">Illustration of transforms</a></li>
<li><a href="https://pytorch.org/blog/how-to-train-state-of-the-art-models-using-torchvision-latest-primitives/">How torchvision trained ResNet-50 to 80.9%</a></li>
</ul>
</div>
</div>
<p><sup>The timeline, LeNet, AlexNet and Inception diagrams in this deck are from Prof.&nbsp;Hickman’s CNN model history page. The convolution animations and the architecture diagrams are from my DSAN 6500 week 4.</sup></p>
</section>
<section id="lab-5" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="lab-5">Lab 5</h2>
<p><strong>Due Wednesday Oct 7.</strong></p>
<p>You will build a convolutional network and compare it against the fully connected model from Lab 4 on the same data, which is the measurement on the “same budget, two ways” slide, done yourself rather than taken on trust.</p>
<p>The pieces you will need are all from today:</p>
<ul>
<li><code>nn.Conv2d</code>, and predicting its output shape before you run it</li>
<li>the conv, norm, activation, pool block</li>
<li><code>nn.AdaptiveAvgPool2d</code> and why the head does not flatten</li>
<li><code>model.train()</code> and <code>model.eval()</code>, and the BatchNorm reason it matters</li>
<li>an augmentation pipeline for training and a deterministic one for evaluation</li>
</ul>
<p>Everything else is the Lab 4 training loop, which you already wrote.</p>
<p>The augmentation part does not come out the way you would expect, and working out why is the point of it.</p>
</section>
<section id="quiz-5" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="quiz-5">Quiz 5</h2>
<p>Closed-book, no notes. A formula sheet comes with it.</p>
<p>Covers <strong>PyTorch and training</strong>, from last week’s deck, plus Lab 4:</p>
<ul>
<li>Tensors, <code>requires_grad</code>, and reading gradients out of <code>.grad</code></li>
<li>Broadcasting, and the shapes that silently produce the wrong answer</li>
<li><code>nn.Linear</code> weight shapes</li>
<li>Logits and <code>CrossEntropyLoss</code></li>
<li><code>Dataset</code> and <code>DataLoader</code>, including <code>num_workers</code></li>
<li>Optimizers and learning rates, and what Adam at an SGD learning rate does</li>
<li>Learning rate schedules, gradient clipping, initialization</li>
<li>Dropout, weight decay, early stopping</li>
</ul>
<p>Four parts: true or false, multiple choice, fill in the blank, and <strong>find the bugs in a training script</strong>. Twenty-five points, about fifteen minutes.</p>
<p>Nothing from today is on it.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>