<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Ben Houghton">
<meta name="dcterms.date" content="2026-09-24">

<title>DSAN 6600: PyTorch and Training</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="04-pytorch-and-training_files/libs/clipboard/clipboard.min.js"></script>
<script src="04-pytorch-and-training_files/libs/quarto-html/quarto.js"></script>
<script src="04-pytorch-and-training_files/libs/quarto-html/popper.min.js"></script>
<script src="04-pytorch-and-training_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04-pytorch-and-training_files/libs/quarto-html/anchor.min.js"></script>
<link href="04-pytorch-and-training_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04-pytorch-and-training_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04-pytorch-and-training_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04-pytorch-and-training_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04-pytorch-and-training_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link rel="icon" type="image/png" href="/icon.png">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#pytorch-and-training" id="toc-pytorch-and-training" class="nav-link active" data-scroll-target="#pytorch-and-training">PyTorch and Training</a>
  <ul class="collapse">
  <li><a href="#agenda" id="toc-agenda" class="nav-link" data-scroll-target="#agenda">Agenda</a></li>
  <li><a href="#where-backpropagation-left-us" id="toc-where-backpropagation-left-us" class="nav-link" data-scroll-target="#where-backpropagation-left-us">Where backpropagation left us</a></li>
  <li><a href="#cures-for-vanishing-and-exploding-gradients" id="toc-cures-for-vanishing-and-exploding-gradients" class="nav-link" data-scroll-target="#cures-for-vanishing-and-exploding-gradients">Cures for vanishing and exploding gradients</a></li>
  <li><a href="#what-changes-and-what-does-not" id="toc-what-changes-and-what-does-not" class="nav-link" data-scroll-target="#what-changes-and-what-does-not">What changes, and what does not</a></li>
  </ul></li>
  <li><a href="#tensors" id="toc-tensors" class="nav-link" data-scroll-target="#tensors">Tensors</a>
  <ul class="collapse">
  <li><a href="#rank-shape-and-what-a-tensor-is" id="toc-rank-shape-and-what-a-tensor-is" class="nav-link" data-scroll-target="#rank-shape-and-what-a-tensor-is">Rank, shape, and what a tensor is</a></li>
  <li><a href="#tensors-and-numpy-arrays" id="toc-tensors-and-numpy-arrays" class="nav-link" data-scroll-target="#tensors-and-numpy-arrays">Tensors and NumPy arrays</a></li>
  <li><a href="#dtype-and-device" id="toc-dtype-and-device" class="nav-link" data-scroll-target="#dtype-and-device">dtype and device</a></li>
  <li><a href="#shape-discipline" id="toc-shape-discipline" class="nav-link" data-scroll-target="#shape-discipline">Shape discipline</a></li>
  <li><a href="#broadcasting-drawn" id="toc-broadcasting-drawn" class="nav-link" data-scroll-target="#broadcasting-drawn">Broadcasting, drawn</a></li>
  <li><a href="#reading-the-shape-bug" id="toc-reading-the-shape-bug" class="nav-link" data-scroll-target="#reading-the-shape-bug">Reading the shape bug</a></li>
  </ul></li>
  <li><a href="#autograd" id="toc-autograd" class="nav-link" data-scroll-target="#autograd">Autograd</a>
  <ul class="collapse">
  <li><a href="#requires_grad-and-the-recorded-graph" id="toc-requires_grad-and-the-recorded-graph" class="nav-link" data-scroll-target="#requires_grad-and-the-recorded-graph"><code>requires_grad</code> and the recorded graph</a></li>
  <li><a href="#reading-gradients-out-of-.grad" id="toc-reading-gradients-out-of-.grad" class="nav-link" data-scroll-target="#reading-gradients-out-of-.grad">Reading gradients out of <code>.grad</code></a></li>
  <li><a href="#gradient-accumulation-into-.grad" id="toc-gradient-accumulation-into-.grad" class="nav-link" data-scroll-target="#gradient-accumulation-into-.grad">Gradient accumulation into <code>.grad</code></a></li>
  <li><a href="#zero_grad-in-the-training-loop" id="toc-zero_grad-in-the-training-loop" class="nav-link" data-scroll-target="#zero_grad-in-the-training-loop"><code>zero_grad</code> in the training loop</a></li>
  </ul></li>
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models">Models</a>
  <ul class="collapse">
  <li><a href="#nn.linear-and-the-shape-convention" id="toc-nn.linear-and-the-shape-convention" class="nav-link" data-scroll-target="#nn.linear-and-the-shape-convention"><code>nn.Linear</code> and the shape convention</a></li>
  <li><a href="#nn.module" id="toc-nn.module" class="nav-link" data-scroll-target="#nn.module"><code>nn.Module</code></a></li>
  <li><a href="#calling-a-model-and-train-and-eval-mode" id="toc-calling-a-model-and-train-and-eval-mode" class="nav-link" data-scroll-target="#calling-a-model-and-train-and-eval-mode">Calling a model, and train and eval mode</a></li>
  <li><a href="#losses-and-what-goes-in-the-final-layer" id="toc-losses-and-what-goes-in-the-final-layer" class="nav-link" data-scroll-target="#losses-and-what-goes-in-the-final-layer">Losses, and what goes in the final layer</a></li>
  <li><a href="#logits-and-crossentropyloss" id="toc-logits-and-crossentropyloss" class="nav-link" data-scroll-target="#logits-and-crossentropyloss">Logits and <code>CrossEntropyLoss</code></a></li>
  <li><a href="#why-the-softmax-is-folded-in" id="toc-why-the-softmax-is-folded-in" class="nav-link" data-scroll-target="#why-the-softmax-is-folded-in">Why the softmax is folded in</a></li>
  </ul></li>
  <li><a href="#the-first-training-loop" id="toc-the-first-training-loop" class="nav-link" data-scroll-target="#the-first-training-loop">The first training loop</a>
  <ul class="collapse">
  <li><a href="#the-five-lines" id="toc-the-five-lines" class="nav-link" data-scroll-target="#the-five-lines">The five lines</a></li>
  <li><a href="#lab-2s-network-trained-with-autograd" id="toc-lab-2s-network-trained-with-autograd" class="nav-link" data-scroll-target="#lab-2s-network-trained-with-autograd">Lab 2’s network, trained with autograd</a></li>
  <li><a href="#what-is-left-to-get-wrong" id="toc-what-is-left-to-get-wrong" class="nav-link" data-scroll-target="#what-is-left-to-get-wrong">What is left to get wrong</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#full-batch-mini-batch-stochastic" id="toc-full-batch-mini-batch-stochastic" class="nav-link" data-scroll-target="#full-batch-mini-batch-stochastic">Full batch, mini-batch, stochastic</a></li>
  <li><a href="#batch-size-and-gradient-noise-measured" id="toc-batch-size-and-gradient-noise-measured" class="nav-link" data-scroll-target="#batch-size-and-gradient-noise-measured">Batch size and gradient noise, measured</a></li>
  <li><a href="#what-the-1sqrtb-curve-means-in-practice" id="toc-what-the-1sqrtb-curve-means-in-practice" class="nav-link" data-scroll-target="#what-the-1sqrtb-curve-means-in-practice">What the <span class="math inline">1/\sqrt{B}</span> curve means in practice</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset"><code>Dataset</code></a></li>
  <li><a href="#dataloader" id="toc-dataloader" class="nav-link" data-scroll-target="#dataloader"><code>DataLoader</code></a></li>
  <li><a href="#dataloader-settings-that-matter" id="toc-dataloader-settings-that-matter" class="nav-link" data-scroll-target="#dataloader-settings-that-matter"><code>DataLoader</code> settings that matter</a></li>
  <li><a href="#recognizing-a-data-bound-training-run" id="toc-recognizing-a-data-bound-training-run" class="nav-link" data-scroll-target="#recognizing-a-data-bound-training-run">Recognizing a data-bound training run</a></li>
  <li><a href="#the-loop-with-batches" id="toc-the-loop-with-batches" class="nav-link" data-scroll-target="#the-loop-with-batches">The loop, with batches</a></li>
  <li><a href="#training-validation-and-test" id="toc-training-validation-and-test" class="nav-link" data-scroll-target="#training-validation-and-test">Training, validation, and test</a></li>
  <li><a href="#leakage" id="toc-leakage" class="nav-link" data-scroll-target="#leakage">Leakage</a></li>
  </ul></li>
  <li><a href="#optimizers" id="toc-optimizers" class="nav-link" data-scroll-target="#optimizers">Optimizers</a>
  <ul class="collapse">
  <li><a href="#the-problem-with-one-learning-rate" id="toc-the-problem-with-one-learning-rate" class="nav-link" data-scroll-target="#the-problem-with-one-learning-rate">The problem with one learning rate</a></li>
  <li><a href="#momentum" id="toc-momentum" class="nav-link" data-scroll-target="#momentum">Momentum</a></li>
  <li><a href="#momentum-measured" id="toc-momentum-measured" class="nav-link" data-scroll-target="#momentum-measured">Momentum, measured</a></li>
  <li><a href="#why-the-momentum-gap-has-that-size" id="toc-why-the-momentum-gap-has-that-size" class="nav-link" data-scroll-target="#why-the-momentum-gap-has-that-size">Why the momentum gap has that size</a></li>
  <li><a href="#rmsprop-and-adam" id="toc-rmsprop-and-adam" class="nav-link" data-scroll-target="#rmsprop-and-adam">RMSProp and Adam</a></li>
  <li><a href="#four-optimizers-on-the-same-problem" id="toc-four-optimizers-on-the-same-problem" class="nav-link" data-scroll-target="#four-optimizers-on-the-same-problem">Four optimizers on the same problem</a></li>
  <li><a href="#optimizers-in-pytorch" id="toc-optimizers-in-pytorch" class="nav-link" data-scroll-target="#optimizers-in-pytorch">Optimizers in PyTorch</a></li>
  <li><a href="#choosing-an-optimizer" id="toc-choosing-an-optimizer" class="nav-link" data-scroll-target="#choosing-an-optimizer">Choosing an optimizer</a></li>
  </ul></li>
  <li><a href="#learning-rate-schedules" id="toc-learning-rate-schedules" class="nav-link" data-scroll-target="#learning-rate-schedules">Learning-rate schedules</a>
  <ul class="collapse">
  <li><a href="#why-the-rate-should-change" id="toc-why-the-rate-should-change" class="nav-link" data-scroll-target="#why-the-rate-should-change">Why the rate should change</a></li>
  <li><a href="#five-schedules" id="toc-five-schedules" class="nav-link" data-scroll-target="#five-schedules">Five schedules</a></li>
  <li><a href="#warmup" id="toc-warmup" class="nav-link" data-scroll-target="#warmup">Warmup</a></li>
  <li><a href="#gradient-clipping" id="toc-gradient-clipping" class="nav-link" data-scroll-target="#gradient-clipping">Gradient clipping</a></li>
  <li><a href="#gradient-clipping-in-the-training-loop" id="toc-gradient-clipping-in-the-training-loop" class="nav-link" data-scroll-target="#gradient-clipping-in-the-training-loop">Gradient clipping in the training loop</a></li>
  <li><a href="#schedules-in-pytorch" id="toc-schedules-in-pytorch" class="nav-link" data-scroll-target="#schedules-in-pytorch">Schedules in PyTorch</a></li>
  </ul></li>
  <li><a href="#initialization" id="toc-initialization" class="nav-link" data-scroll-target="#initialization">Initialization</a>
  <ul class="collapse">
  <li><a href="#why-initialization-decides-whether-training-starts" id="toc-why-initialization-decides-whether-training-starts" class="nav-link" data-scroll-target="#why-initialization-decides-whether-training-starts">Why initialization decides whether training starts</a></li>
  <li><a href="#initialization-measured" id="toc-initialization-measured" class="nav-link" data-scroll-target="#initialization-measured">Initialization, measured</a></li>
  <li><a href="#why-the-two-naive-initializations-fail" id="toc-why-the-two-naive-initializations-fail" class="nav-link" data-scroll-target="#why-the-two-naive-initializations-fail">Why the two naive initializations fail</a></li>
  <li><a href="#why-xavier-and-he-both-work" id="toc-why-xavier-and-he-both-work" class="nav-link" data-scroll-target="#why-xavier-and-he-both-work">Why Xavier and He both work</a></li>
  <li><a href="#xavier-and-he" id="toc-xavier-and-he" class="nav-link" data-scroll-target="#xavier-and-he">Xavier and He</a></li>
  </ul></li>
  <li><a href="#regularization" id="toc-regularization" class="nav-link" data-scroll-target="#regularization">Regularization</a>
  <ul class="collapse">
  <li><a href="#overfitting-measured" id="toc-overfitting-measured" class="nav-link" data-scroll-target="#overfitting-measured">Overfitting, measured</a></li>
  <li><a href="#reading-the-gap" id="toc-reading-the-gap" class="nav-link" data-scroll-target="#reading-the-gap">Reading the gap</a></li>
  <li><a href="#early-stopping" id="toc-early-stopping" class="nav-link" data-scroll-target="#early-stopping">Early stopping</a></li>
  <li><a href="#weight-decay" id="toc-weight-decay" class="nav-link" data-scroll-target="#weight-decay">Weight decay</a></li>
  <li><a href="#dropout" id="toc-dropout" class="nav-link" data-scroll-target="#dropout">Dropout</a></li>
  <li><a href="#dropout-in-practice" id="toc-dropout-in-practice" class="nav-link" data-scroll-target="#dropout-in-practice">Dropout in practice</a></li>
  <li><a href="#batch-and-layer-normalization" id="toc-batch-and-layer-normalization" class="nav-link" data-scroll-target="#batch-and-layer-normalization">Batch and layer normalization</a></li>
  <li><a href="#what-to-reach-for-in-order" id="toc-what-to-reach-for-in-order" class="nav-link" data-scroll-target="#what-to-reach-for-in-order">What to reach for, in order</a></li>
  </ul></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together">Putting it all together</a>
  <ul class="collapse">
  <li><a href="#the-full-loop" id="toc-the-full-loop" class="nav-link" data-scroll-target="#the-full-loop">The full loop</a></li>
  <li><a href="#saving-a-model" id="toc-saving-a-model" class="nav-link" data-scroll-target="#saving-a-model">Saving a model</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#when-a-model-will-not-learn" id="toc-when-a-model-will-not-learn" class="nav-link" data-scroll-target="#when-a-model-will-not-learn">When a model will not learn</a></li>
  </ul></li>
  <li><a href="#closing" id="toc-closing" class="nav-link" data-scroll-target="#closing">Closing</a>
  <ul class="collapse">
  <li><a href="#labs-and-quizzes" id="toc-labs-and-quizzes" class="nav-link" data-scroll-target="#labs-and-quizzes">Labs and quizzes</a></li>
  <li><a href="#supplemental-content" id="toc-supplemental-content" class="nav-link" data-scroll-target="#supplemental-content">Supplemental content</a></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a></li>
  <li><a href="#quiz-4" id="toc-quiz-4" class="nav-link" data-scroll-target="#quiz-4">Quiz 4</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="presentation.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DSAN 6600: PyTorch and Training</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Ben Houghton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="2df121c6" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6600</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"torch </span><span class="sc">{</span>torch<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">   cuda available: </span><span class="sc">{</span>torch<span class="sc">.</span>cuda<span class="sc">.</span>is_available()<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>torch 2.7.1+cu126   cuda available: True</code></pre>
</div>
</div>
<section id="pytorch-and-training" class="level1">
<h1>PyTorch and Training</h1>
<ul>
<li>Thursdays, 3:30-6:00 PM · ICC 103</li>
<li>Weeks 5 and 6 of 14 · Sep 24 and Oct 1</li>
<li><strong>Quiz 4 is at the end of class today</strong>, covering Week 4 and Lab 3</li>
</ul>
<section id="agenda" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="agenda">Agenda</h2>
<p>Backpropagation is finished, apart from the vanishing-gradient cures we listed but did not work through. Those are item 7. Everything else is the tooling that makes backprop usable:</p>
<ol type="1">
<li><strong>Tensors</strong>: what PyTorch adds to a NumPy array</li>
<li><strong>Autograd</strong>: <code>.backward()</code>, <code>.grad</code>, and why gradients accumulate</li>
<li><strong>Models</strong>: <code>nn.Linear</code>, <code>nn.Module</code>, and which loss goes with which task</li>
<li><strong>The first training loop</strong>: Lab 2’s network, one backward pass per step</li>
<li><strong>Data</strong>: <code>Dataset</code>, <code>DataLoader</code>, and what batch size actually costs you</li>
<li><strong>Optimizers</strong>: momentum, RMSProp, Adam</li>
<li><strong>Schedules, initialization, regularization</strong></li>
<li><strong>A complete training script</strong></li>
</ol>
<p>Spotlights first. Quiz 4 in the last 20 minutes.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pace
</div>
</div>
<div class="callout-body-container callout-body">
<p>Items 1 through 4 are the core and come first. Items 5 onward are the decisions that surround training, and they are written to be readable on your own if we run short.</p>
</div>
</div>
</section>
<section id="where-backpropagation-left-us" class="level2">
<h2 class="anchored" data-anchor-id="where-backpropagation-left-us">Where backpropagation left us</h2>
<p>Three weeks of work to arrive at one fact: <strong>the gradient is cheap now.</strong></p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Lab 2</th>
<th>After backpropagation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gradient from</td>
<td>finite differences</td>
<td>reverse-mode autodiff</td>
</tr>
<tr class="even">
<td>Work per step</td>
<td>50 forward passes</td>
<td>1 forward + 1 backward</td>
</tr>
<tr class="odd">
<td>400 steps</td>
<td>20,001 forward passes</td>
<td>401 forward passes</td>
</tr>
<tr class="even">
<td>Exact?</td>
<td>no, <span class="math inline">O(\varepsilon)</span> error</td>
<td>yes, to floating point</td>
</tr>
</tbody>
</table>
<p>That ratio was 50 for a 49-parameter network. For a 25-million-parameter network it is 25 million.</p>
<p>Everything that can still go wrong is now about the <strong>optimizer</strong>, the <strong>data</strong>, the <strong>initialization</strong>, and the <strong>loss surface</strong>. That list is the rest of this deck.</p>
</section>
<section id="cures-for-vanishing-and-exploding-gradients" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="cures-for-vanishing-and-exploding-gradients">Cures for vanishing and exploding gradients</h2>
<p>We ended last week on the problem and <strong>named</strong> the cures without working through any of them. Each one lands somewhere today:</p>
<table class="table">
<thead>
<tr class="header">
<th>Cure</th>
<th>Where it is in this deck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Weight initialization</strong></td>
<td>Initialization: Xavier and He</td>
</tr>
<tr class="even">
<td><strong>Gradient clipping</strong></td>
<td>Learning-rate schedules</td>
</tr>
<tr class="odd">
<td><strong>Batch normalization</strong></td>
<td>Regularization</td>
</tr>
<tr class="even">
<td><strong>Better activations</strong>, ReLU over sigmoid</td>
<td>Week 2, already yours</td>
</tr>
<tr class="odd">
<td><strong>Skip connections</strong></td>
<td>With CNNs, next week</td>
</tr>
</tbody>
</table>
<p>They come after the PyTorch foundation rather than before it, and that ordering is deliberate: every one of them is a line of PyTorch you cannot read yet. <code>nn.init.kaiming_normal_</code> means nothing until <code>nn.Linear</code> does.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Initialization is the one to remember
</div>
</div>
<div class="callout-body-container callout-body">
<p>Initialization is the cure that decides whether a deep network trains <strong>at all</strong>, and the measured version of that claim is later in this deck.</p>
</div>
</div>
</section>
<section id="what-changes-and-what-does-not" class="level2">
<h2 class="anchored" data-anchor-id="what-changes-and-what-does-not">What changes, and what does not</h2>
<p>You have written a backward pass by hand, in Lab 3. Nothing in PyTorch is doing anything you have not done.</p>
<div class="columns contrast">
<div class="column col-yes" style="width:48%;">
<section id="already-yours" class="level3">
<h3 class="anchored" data-anchor-id="already-yours">Already yours</h3>
<ul>
<li>The chain rule on a graph</li>
<li>Local derivatives at a node</li>
<li>Adding gradients where paths meet</li>
<li>Reverse topological order</li>
<li>The three layer gradients</li>
</ul>
</section>
</div><div class="column col-no" style="width:48%;">
<section id="what-pytorch-adds" class="level3">
<h3 class="anchored" data-anchor-id="what-pytorch-adds">What PyTorch adds</h3>
<ul>
<li>It records the graph for you</li>
<li>It runs on a GPU</li>
<li>It has the layers already written</li>
<li>It has the optimizers already written</li>
<li>It is fast enough to be useful</li>
</ul>
</section>
</div>
</div>
<p>The point of Lab 3 was that <code>.backward()</code> should be <strong>boring</strong> by the time you first call it.</p>
</section>
</section>
<section id="tensors" class="level1">
<h1>Tensors</h1>
<ul>
<li>A tensor is an array that can also record how it was computed</li>
<li>Most first-week PyTorch errors are <code>dtype</code> or <code>device</code></li>
</ul>
<section id="rank-shape-and-what-a-tensor-is" class="level2">
<h2 class="anchored" data-anchor-id="rank-shape-and-what-a-tensor-is">Rank, shape, and what a tensor is</h2>
<p>A <strong>tensor</strong> is an <span class="math inline">n</span>-dimensional array. <strong>Rank</strong>, or <code>ndim</code>, is the number of axes, meaning the number of indices needed to reach one element.</p>
<table class="table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Shape</th>
<th>What it holds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><code>[]</code></td>
<td>a scalar, such as a cost</td>
</tr>
<tr class="even">
<td>1</td>
<td><code>[d]</code></td>
<td>one feature vector</td>
</tr>
<tr class="odd">
<td>2</td>
<td><code>[N, d]</code></td>
<td>a batch of feature vectors</td>
</tr>
<tr class="even">
<td>3</td>
<td><code>[N, T, d]</code></td>
<td>a batch of sequences</td>
</tr>
<tr class="odd">
<td>4</td>
<td><code>[N, C, H, W]</code></td>
<td>a batch of images</td>
</tr>
</tbody>
</table>
<p>A PyTorch tensor is a NumPy array plus three things Lab 2 did not have:</p>
<ul>
<li>A <strong>device</strong>, CPU or CUDA or MPS</li>
<li>A <strong><code>requires_grad</code></strong> flag</li>
<li>A recorded <strong>graph</strong>, so it knows which operation produced it</li>
</ul>
</section>
<section id="tensors-and-numpy-arrays" class="level2">
<h2 class="anchored" data-anchor-id="tensors-and-numpy-arrays">Tensors and NumPy arrays</h2>
<p>The arithmetic is the same. <code>torch.from_numpy</code> even shares memory on CPU, so writing through one view changes the other.</p>
<div id="e00cf6ba" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>A_np <span class="op">=</span> np.arange(<span class="dv">6</span>).reshape(<span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> torch.from_numpy(A_np)          <span class="co"># shares storage with A_np on CPU</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"numpy  </span><span class="sc">{</span>A_np<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">  torch  </span><span class="sc">{</span><span class="bu">tuple</span>(A.shape)<span class="sc">}</span><span class="ss">  ndim </span><span class="sc">{</span>A<span class="sc">.</span>ndim<span class="sc">}</span><span class="ss">  "</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"numel </span><span class="sc">{</span>A<span class="sc">.</span>numel()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>A_np[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">=</span> <span class="dv">99</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"wrote through the numpy view; torch sees </span><span class="sc">{</span>A[<span class="dv">0</span>, <span class="dv">0</span>]<span class="sc">.</span>item()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([[<span class="fl">0.7</span>, <span class="op">-</span><span class="fl">1.2</span>]])                  <span class="co"># one batched example, (1, 2)</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> torch.randn(<span class="dv">3</span>, <span class="dv">2</span>, requires_grad<span class="op">=</span><span class="va">True</span>)        <span class="co"># (units, inputs), as in Lab 2</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> torch.zeros(<span class="dv">3</span>, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> x <span class="op">@</span> W.T <span class="op">+</span> b                                  <span class="co"># the batched layer from Lab 2</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">x </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss"> @ W.T </span><span class="sc">{</span><span class="bu">tuple</span>(W.T.shape)<span class="sc">}</span><span class="ss"> + b </span><span class="sc">{</span><span class="bu">tuple</span>(b.shape)<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"-&gt; z </span><span class="sc">{</span><span class="bu">tuple</span>(z.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z was produced by </span><span class="sc">{</span><span class="bu">type</span>(z.grad_fn)<span class="sc">.</span><span class="va">__name__</span><span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"which is the graph autograd recorded"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>numpy  (2, 3)  torch  (2, 3)  ndim 2  numel 6
wrote through the numpy view; torch sees 99

x (1, 2) @ W.T (2, 3) + b (3,) -&gt; z (1, 3)
z was produced by AddBackward0, which is the graph autograd recorded</code></pre>
</div>
</div>
</section>
<section id="dtype-and-device" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="dtype-and-device">dtype and device</h2>
<p>Two attributes that cause most first-week PyTorch errors.</p>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>dtype.</strong> Memory is <code>numel</code> times bytes per element.</p>
<table class="table">
<thead>
<tr class="header">
<th>dtype</th>
<th>Bytes</th>
<th>Used for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>float32</code></td>
<td>4</td>
<td>the default for training</td>
</tr>
<tr class="even">
<td><code>float64</code></td>
<td>8</td>
<td>precision, and slower</td>
</tr>
<tr class="odd">
<td><code>float16</code></td>
<td>2</td>
<td>fast GPU training</td>
</tr>
<tr class="even">
<td><code>bfloat16</code></td>
<td>2</td>
<td>wider exponent, stabler</td>
</tr>
<tr class="odd">
<td><code>int64</code></td>
<td>8</td>
<td>indices, class labels</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:48%;">
<p><strong>device.</strong> Tensors must be on the same device to interact.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>torch.cuda.is_available()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> x.to(<span class="st">"cuda"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>RuntimeError: Expected all tensors to be on the same device</code> is the error you will hit first. The fix is always to move one of them.</p>
<p><code>nn.CrossEntropyLoss</code> wants labels as <code>int64</code>. That is the other one.</p>
</div>
</div>
</section>
<section id="shape-discipline" class="level2">
<h2 class="anchored" data-anchor-id="shape-discipline">Shape discipline</h2>
<p>The habit that saves the most debugging time is simple. <strong>Print shapes, not values.</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(x.shape, W.shape, z.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>These two problems look the same from the outside but are not. A network that trains badly is a research problem. A network with the wrong shapes is a bug, and usually a quiet one: broadcasting will turn a <code>(32, 1)</code> against a <code>(32,)</code> into a <code>(32, 32)</code> without complaining, and hand you a cost that is arithmetically correct and completely meaningless.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The most common shape bug
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>criterion(pred, y)</code> where <code>pred</code> is <code>(N, 1)</code> and <code>y</code> is <code>(N,)</code>. This broadcasts into an <span class="math inline">N \times N</span> matrix of differences, the cost comes out plausible, and the model never learns. Use <code>y.unsqueeze(1)</code> or <code>pred.squeeze(1)</code> and make the shapes match deliberately.</p>
</div>
</div>
</section>
<section id="broadcasting-drawn" class="level2">
<h2 class="anchored" data-anchor-id="broadcasting-drawn">Broadcasting, drawn</h2>
<p><a href="images/fig-broadcasting.png" class="zoom" target="_blank"><img src="images/fig-broadcasting.png" class="dw92 img-fluid" width="1000"></a></p>
<p>Broadcasting stretches a size-1 or missing dimension to match the other operand. All three of these are the <strong>same rule</strong>. Two of them are the reason the rule exists. The third is a <span class="math inline">(4,1)</span> minus a <span class="math inline">(4,)</span>: the batch dimension lines up against the feature dimension, every prediction gets compared against every label, and you get a <span class="math inline">4 \times 4</span> where you wanted a <span class="math inline">4 \times 1</span>.</p>
</section>
<section id="reading-the-shape-bug" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="reading-the-shape-bug">Reading the shape bug</h2>
<p>Nothing raises. The cost comes out <span class="math inline">9.7\times</span> too large and still looks exactly like a cost.</p>
<div id="c996a840" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> torch.tensor([[<span class="fl">0.9</span>], [<span class="fl">0.2</span>], [<span class="fl">0.7</span>], [<span class="fl">0.1</span>]])   <span class="co"># (4, 1)  model output</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>y    <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">0.0</span>])           <span class="co"># (4,)    labels</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> pred <span class="op">-</span> y                       <span class="co"># no warning, no error, wrong shape</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"(4, 1) - (4,)   -&gt;   </span><span class="sc">{</span><span class="bu">tuple</span>(diff.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  broadcast  MSE  </span><span class="sc">{</span>(diff <span class="op">**</span> <span class="dv">2</span>)<span class="sc">.</span>mean()<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  correct    MSE  </span><span class="sc">{</span>((pred <span class="op">-</span> y.unsqueeze(<span class="dv">1</span>)) <span class="op">**</span> <span class="dv">2</span>)<span class="sc">.</span>mean()<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(4, 1) - (4,)   -&gt;   (4, 4)

  broadcast  MSE  0.3625
  correct    MSE  0.0375</code></pre>
</div>
</div>
<p><code>nn.MSELoss</code> does print a <code>UserWarning</code> for this exact mismatch, which is a real safety net. But the subtraction one line earlier was already silent, so any loss you write yourself gets no such warning, and a warning that scrolls past in cell 40 of a notebook is not a warning anyone reads.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check the shapes
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>assert pred.shape == y.shape</code> on the line before the loss. It costs nothing and it closes this off permanently.</p>
</div>
</div>
</section>
</section>
<section id="autograd" class="level1">
<h1>Autograd</h1>
<ul>
<li>The backward pass you wrote in Lab 3, with a bigger graph and a GPU</li>
<li>Three rules that explain most of autograd, and one common mistake</li>
</ul>
<section id="requires_grad-and-the-recorded-graph" class="level2">
<h2 class="anchored" data-anchor-id="requires_grad-and-the-recorded-graph"><code>requires_grad</code> and the recorded graph</h2>
<p>Three rules that explain most of autograd’s behaviour:</p>
<ol type="1">
<li>An operation is recorded if <strong>any</strong> input has <code>requires_grad=True</code></li>
<li><code>.backward()</code> is called on a <strong>scalar</strong>, and it fills <code>.grad</code> on every leaf tensor that requested gradients</li>
<li>Intermediate results do <strong>not</strong> keep their gradient unless you ask, with <code>retain_grad()</code></li>
</ol>
<p>Rule 2 is the reason reverse mode is the right choice, restated as an API constraint: the thing you differentiate has to be one number.</p>
<p>To stop recording, either wrap the block in <code>torch.no_grad()</code> or call <code>.detach()</code>. Do this for evaluation and inference: it is faster, and it does not build a graph you are about to throw away.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    val_cost <span class="op">=</span> criterion(model(x_val), y_val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="reading-gradients-out-of-.grad" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="reading-gradients-out-of-.grad">Reading gradients out of <code>.grad</code></h2>
<p>The graph from <strong>Lab 3, part 2c</strong>, handed to autograd instead of to your <code>Value</code> class. Same three inputs, same expected answers.</p>
<div id="2b6def96" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> torch.tensor([<span class="fl">3.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> torch.tensor([<span class="fl">5.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>C <span class="op">=</span> A <span class="op">*</span> B<span class="op">;</span>   C.retain_grad()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>F <span class="op">=</span> D <span class="op">+</span> C<span class="op">;</span>   F.retain_grad()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> F <span class="op">+</span> A<span class="op">;</span>   G.retain_grad()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>H <span class="op">=</span> G <span class="op">*</span> B</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>H.backward()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"forward   C=</span><span class="sc">{</span>C<span class="sc">.</span>item()<span class="sc">:4.0f}</span><span class="ss">  F=</span><span class="sc">{</span>F<span class="sc">.</span>item()<span class="sc">:4.0f}</span><span class="ss">  "</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"G=</span><span class="sc">{</span>G<span class="sc">.</span>item()<span class="sc">:4.0f}</span><span class="ss">  H=</span><span class="sc">{</span>H<span class="sc">.</span>item()<span class="sc">:4.0f}</span><span class="ss">"</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, t <span class="kw">in</span> [(<span class="st">"G"</span>, G), (<span class="st">"F"</span>, F), (<span class="st">"C"</span>, C), (<span class="st">"D"</span>, D), (<span class="st">"B"</span>, B), (<span class="st">"A"</span>, A)]:</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  dH/d</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">  </span><span class="sc">{</span>t<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;6.0f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>forward   C=   6  F=  11  G=  13  H=  39

  dH/dG       3
  dH/dF       3
  dH/dC       3
  dH/dD       3
  dH/dB      19
  dH/dA      12</code></pre>
</div>
</div>
<p>Three lines of bookkeeping replaced the whole engine you wrote. Look at the answer for <span class="math inline">A</span>: <strong>12</strong>, not 3 and not 9. <span class="math inline">A</span> reaches <span class="math inline">H</span> along two paths, and autograd <strong>added</strong> the two contributions, which is the same rule your <code>backward</code> had to implement by hand.</p>
</section>
<section id="gradient-accumulation-into-.grad" class="level2">
<h2 class="anchored" data-anchor-id="gradient-accumulation-into-.grad">Gradient accumulation into <code>.grad</code></h2>
<p><code>.grad</code> is a <strong>running sum</strong>, for exactly the reason we saw at the fork in the graph: a node may be reached along more than one path, so the backward pass adds rather than overwrites.</p>
<p>Here is the failure mode rather than a warning about it.</p>
<div id="610e1e9b" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x, y <span class="op">=</span> torch.tensor([<span class="fl">3.0</span>]), torch.tensor([<span class="fl">12.0</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> call <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> (w <span class="op">*</span> x <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    loss.backward()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"backward call </span><span class="sc">{</span>call<span class="sc">}</span><span class="ss">:  w.grad = </span><span class="sc">{</span>w<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.1f}</span><span class="ss">"</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"   (</span><span class="sc">{</span>call<span class="sc">}</span><span class="ss">x the true gradient)"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>w.grad.zero_()</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> (w <span class="op">*</span> x <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>loss.backward()</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">after zero_():   w.grad = </span><span class="sc">{</span>w<span class="sc">.</span>grad<span class="sc">.</span>item()<span class="sc">:&gt;7.1f}</span><span class="ss">   (correct again)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>backward call 1:  w.grad =   -36.0   (1x the true gradient)
backward call 2:  w.grad =   -72.0   (2x the true gradient)
backward call 3:  w.grad =  -108.0   (3x the true gradient)

after zero_():   w.grad =   -36.0   (correct again)</code></pre>
</div>
</div>
</section>
<section id="zero_grad-in-the-training-loop" class="level2">
<h2 class="anchored" data-anchor-id="zero_grad-in-the-training-loop"><code>zero_grad</code> in the training loop</h2>
<p>Every training step is these four lines, and the order matters:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>optimizer.zero_grad()    <span class="co"># clear the running sum from last step</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> criterion(model(x), y)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>loss.backward()          <span class="co"># write .grad on every parameter</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>optimizer.step()         <span class="co"># theta &lt;- theta - lr * theta.grad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Forget <code>zero_grad()</code> and step 3 adds to whatever was already there. You are not descending on the current gradient; you are descending on the sum of every gradient since the model was built. The cost usually diverges, and <strong>it looks exactly like a learning rate that is too high.</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The accumulation is a feature too
</div>
</div>
<div class="callout-body-container callout-body">
<p>Deliberately skipping <code>zero_grad()</code> for a few mini-batches simulates a larger batch than fits in memory. That is <strong>gradient accumulation</strong>, and it is a real technique used to train large models on small hardware. It is only a bug when it is an accident.</p>
</div>
</div>
</section>
</section>
<section id="models" class="level1">
<h1>Models</h1>
<ul>
<li><code>nn.Linear</code> is Lab 2’s layer</li>
<li><code>nn.Module</code> is a forward pass with parameters attached</li>
</ul>
<section id="nn.linear-and-the-shape-convention" class="level2">
<h2 class="anchored" data-anchor-id="nn.linear-and-the-shape-convention"><code>nn.Linear</code> and the shape convention</h2>
<p><code>nn.Linear(in_features, out_features)</code> stores <span class="math inline">\mathbf{W}</span> as <code>(out_features, in_features)</code> and <span class="math inline">\mathbf{b}</span> as <code>(out_features,)</code>. That is the <code>(units, inputs)</code> convention from Week 2, unchanged, which is why the batched form carries a transpose.</p>
<div id="e37c2d40" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">6600</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>layer <span class="op">=</span> nn.Linear(<span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.randn(<span class="dv">5</span>, <span class="dv">2</span>)                       <span class="co"># five examples, two features</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"layer.weight </span><span class="sc">{</span><span class="bu">tuple</span>(layer.weight.shape)<span class="sc">}</span><span class="ss">   "</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"layer.bias </span><span class="sc">{</span><span class="bu">tuple</span>(layer.bias.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"x </span><span class="sc">{</span><span class="bu">tuple</span>(x.shape)<span class="sc">}</span><span class="ss">  -&gt;  layer(x) </span><span class="sc">{</span><span class="bu">tuple</span>(layer(x).shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># the same arithmetic, written out</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>by_hand <span class="op">=</span> x <span class="op">@</span> layer.weight.T <span class="op">+</span> layer.bias</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">max |layer(x) - (x @ W.T + b)| = "</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>(layer(x) <span class="op">-</span> by_hand)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"nn.Linear is that line, plus the gradient tape"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>layer.weight (3, 2)   layer.bias (3,)
x (5, 2)  -&gt;  layer(x) (5, 3)

max |layer(x) - (x @ W.T + b)| = 0.00e+00
nn.Linear is that line, plus the gradient tape</code></pre>
</div>
</div>
</section>
<section id="nn.module" class="level2">
<h2 class="anchored" data-anchor-id="nn.module"><code>nn.Module</code></h2>
<p>A model is a class with two jobs: declare the layers in <code>__init__</code>, and write the forward pass in <code>forward</code>. Subclassing <code>nn.Module</code> is what <strong>registers</strong> the parameters, so the optimizer, <code>.to(device)</code> and saving all find them.</p>
<div id="033869f5" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MLP(nn.Module):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, hidden<span class="op">=</span><span class="dv">16</span>):</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden <span class="op">=</span> nn.Linear(<span class="dv">1</span>, hidden)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(hidden, <span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(torch.tanh(<span class="va">self</span>.hidden(x)))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> MLP()</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, p <span class="kw">in</span> model.named_parameters():</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">:&lt;14}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">str</span>(<span class="bu">tuple</span>(p.shape))<span class="sc">:&gt;10}</span><span class="ss">  </span><span class="sc">{</span>p<span class="sc">.</span>numel()<span class="sc">:&gt;3}</span><span class="ss"> "</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"parameter</span><span class="sc">{</span><span class="st">'s'</span> <span class="cf">if</span> p<span class="sc">.</span>numel() <span class="op">!=</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">''</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">total: </span><span class="sc">{</span><span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> model.parameters())<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(Lab 2's network, exactly)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>MLP(
  (hidden): Linear(in_features=1, out_features=16, bias=True)
  (out): Linear(in_features=16, out_features=1, bias=True)
)

  hidden.weight     (16, 1)   16 parameters
  hidden.bias         (16,)   16 parameters
  out.weight        (1, 16)   16 parameters
  out.bias             (1,)    1 parameter

total: 49 (Lab 2's network, exactly)</code></pre>
</div>
</div>
</section>
<section id="calling-a-model-and-train-and-eval-mode" class="level2">
<h2 class="anchored" data-anchor-id="calling-a-model-and-train-and-eval-mode">Calling a model, and train and eval mode</h2>
<p>Call <code>model(x)</code>, never <code>model.forward(x)</code>. The first runs registered hooks and respects train and eval mode; the second skips them.</p>
<ul>
<li><strong><code>nn.Sequential</code></strong> is the same thing when the graph is a straight line</li>
<li><strong><code>model.train()</code></strong> and <strong><code>model.eval()</code></strong> change the behaviour of dropout and batch normalization. Neither is in this model yet, so neither matters yet, and both will bite you later in this deck</li>
<li><strong><code>model.parameters()</code></strong> is what you hand the optimizer</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span><span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Forgetting <code>model.eval()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Your validation cost will be computed with dropout still switched on and batch norm still updating its running statistics. The number will be worse than the truth, noisier than the truth, and it will change if you evaluate twice.</p>
</div>
</div>
</section>
<section id="losses-and-what-goes-in-the-final-layer" class="level2">
<h2 class="anchored" data-anchor-id="losses-and-what-goes-in-the-final-layer">Losses, and what goes in the final layer</h2>
<table class="table">
<thead>
<tr class="header">
<th>Task</th>
<th>Final layer</th>
<th>PyTorch loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>linear, 1 unit</td>
<td><code>nn.MSELoss</code></td>
</tr>
<tr class="even">
<td>Binary classification</td>
<td>linear, 1 unit</td>
<td><code>nn.BCEWithLogitsLoss</code></td>
</tr>
<tr class="odd">
<td>Multi-class, <span class="math inline">C</span> classes</td>
<td>linear, <span class="math inline">C</span> units</td>
<td><code>nn.CrossEntropyLoss</code></td>
</tr>
</tbody>
</table>
<p>Note what is <strong>not</strong> in that middle column: no sigmoid, and no softmax.</p>
<p><code>nn.BCELoss</code> exists and takes probabilities, so it needs a sigmoid in the model. Prefer <strong><code>BCEWithLogitsLoss</code></strong>, which folds the sigmoid in and is numerically stabler for exactly the cancellation reason from Week 4: computing <span class="math inline">\hat{y} - y</span> directly avoids ever forming <span class="math inline">\log \hat{p}</span> when <span class="math inline">\hat{p}</span> is near zero.</p>
</section>
<section id="logits-and-crossentropyloss" class="level2">
<h2 class="anchored" data-anchor-id="logits-and-crossentropyloss">Logits and <code>CrossEntropyLoss</code></h2>
<p>In Keras you apply softmax in the model. <strong>In PyTorch you do not.</strong> <code>nn.CrossEntropyLoss</code> applies <span class="math inline">\log\mathrm{softmax}</span> internally and then takes the negative log-likelihood:</p>
<p><span class="math display">\mathcal{L}(z, y) = -\log \frac{e^{z_y}}{\sum_j e^{z_j}}
  \;=\; -z_y + \log \sum_j e^{z_j}</span></p>
<p>So classification models in this course return <strong>logits</strong>, raw scores of shape <code>(N, C)</code>, and the targets are <strong>integer class labels</strong> of shape <code>(N,)</code> with dtype <code>int64</code>. Not one-hot.</p>
<p>Apply softmax in the model as well and you have applied it twice: the gradients degrade and the numerics get worse. It is a quiet bug, because the model still trains, just badly.</p>
</section>
<section id="why-the-softmax-is-folded-in" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-the-softmax-is-folded-in">Why the softmax is folded in</h2>
<p>Two reasons to keep the two steps together instead of computing a probability and then taking its log.</p>
<p><strong>Numerics.</strong> Written separately, a confident wrong prediction puts <span class="math inline">\hat{p}_y \approx 10^{-40}</span> into a <code>log</code>, and in float32 that underflows to zero and the loss returns <code>inf</code>. Written as <span class="math inline">-z_y + \log\sum_j e^{z_j}</span>, the sum can be rescaled by its own largest term before exponentiating, so nothing ever overflows or underflows.</p>
<p><strong>The gradient collapses.</strong> Compose the two and almost everything cancels:</p>
<p><span class="math display">\frac{\partial \mathcal{L}}{\partial z_i} = p_i - y_i,
  \qquad p = \mathrm{softmax}(z), \quad y \text{ one-hot}</span></p>
<p>Predicted minus actual. No softmax Jacobian, no division, no chain of intermediate terms to lose precision through. It is the multi-class version of the sigmoid-plus-BCE cancellation from Week 4, and it is the reason these loss-and-activation pairings are not arbitrary.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Read the gradient
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the true class has <span class="math inline">p_y = 0.7</span>, its logit gets <span class="math inline">0.7 - 1 = -0.3</span>: push it up. Every other class gets <span class="math inline">+p_i</span>: push it down, in proportion to how much probability it stole.</p>
</div>
</div>
</section>
</section>
<section id="the-first-training-loop" class="level1">
<h1>The first training loop</h1>
<ul>
<li>Lab 2’s network, Lab 2’s data, Lab 2’s initialization</li>
<li>One backward pass per step instead of fifty forward passes</li>
</ul>
<section id="the-five-lines" class="level2">
<h2 class="anchored" data-anchor-id="the-five-lines">The five lines</h2>
<p>These will not change for the rest of the semester:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(STEPS):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()               <span class="co"># clear the running sum</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> criterion(model(x), y)       <span class="co"># forward, and record</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    loss.backward()                     <span class="co"># backward, fill every .grad</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    optimizer.step()                    <span class="co"># theta &lt;- theta - lr * grad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Everything else is which model, which loss, which optimizer, and what data comes in. The optimizer is plain <strong>SGD</strong> here, the same update rule from Week 1:</p>
<p><span class="math display">\theta^{(t+1)} = \theta^{(t)} - \eta\, \nabla_{\theta} \mathcal{L}\big(\theta^{(t)}\big)</span></p>
<p>Momentum, Adam and schedules are later in this deck. Right now we only want the gradient to be correct and cheap.</p>
</section>
<section id="lab-2s-network-trained-with-autograd" class="level2 codetight">
<h2 class="codetight anchored" data-anchor-id="lab-2s-network-trained-with-autograd">Lab 2’s network, trained with autograd</h2>
<p>Same seed, same weights, same 400 steps, same learning rate. Source code for your reference. The printed costs should match Lab 2 to four decimals; the work per step should not.</p>
<div id="ba70fc45" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>SEED, HIDDEN, STEPS, LR <span class="op">=</span> <span class="dv">6600</span>, <span class="dv">16</span>, <span class="dv">400</span>, <span class="fl">0.1</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>SHAPES <span class="op">=</span> [(<span class="st">"W"</span>, (HIDDEN, <span class="dv">1</span>)), (<span class="st">"b"</span>, (HIDDEN,)), (<span class="st">"W"</span>, (<span class="dv">1</span>, HIDDEN)), (<span class="st">"b"</span>, (<span class="dv">1</span>,))]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Lab 2's data and initialization, reproduced exactly: two generators, both</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># seeded with SEED, so neither advances the other's stream.</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>rng_data, rng_init <span class="op">=</span> np.random.default_rng(SEED), np.random.default_rng(SEED)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>x_np <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">200</span>).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>y_np <span class="op">=</span> np.sin(<span class="fl">3.0</span> <span class="op">*</span> x_np.ravel()) <span class="op">+</span> rng_data.normal(<span class="dv">0</span>, <span class="fl">0.10</span>, <span class="dv">200</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>theta, i <span class="op">=</span> np.zeros(<span class="bu">sum</span>(<span class="bu">int</span>(np.prod(s)) <span class="cf">for</span> _, s <span class="kw">in</span> SHAPES)), <span class="dv">0</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> kind, shape <span class="kw">in</span> SHAPES:</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">int</span>(np.prod(shape))</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    theta[i:i <span class="op">+</span> n] <span class="op">=</span> (rng_init.normal(<span class="dv">0</span>, <span class="dv">1</span> <span class="op">/</span> np.sqrt(shape[<span class="dv">1</span>]), n)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>                      <span class="cf">if</span> kind <span class="op">==</span> <span class="st">"W"</span> <span class="cf">else</span> <span class="fl">0.0</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> n</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> nn.Sequential(nn.Linear(<span class="dv">1</span>, HIDDEN), nn.Tanh(),</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>                      nn.Linear(HIDDEN, <span class="dv">1</span>)).double()</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">0</span>].weight.copy_(torch.from_numpy(theta[:HIDDEN].reshape(HIDDEN, <span class="dv">1</span>)))</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">0</span>].bias.copy_(torch.from_numpy(theta[HIDDEN:<span class="dv">2</span> <span class="op">*</span> HIDDEN]))</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">2</span>].weight.copy_(torch.from_numpy(</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>        theta[<span class="dv">2</span> <span class="op">*</span> HIDDEN:<span class="dv">3</span> <span class="op">*</span> HIDDEN].reshape(<span class="dv">1</span>, HIDDEN)))</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    model[<span class="dv">2</span>].bias.copy_(torch.from_numpy(theta[<span class="op">-</span><span class="dv">1</span>:]))</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.from_numpy(x_np)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> torch.from_numpy(y_np).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span>LR)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.MSELoss()</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="bu">float</span>(criterion(model(x), y))</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(STEPS):</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> criterion(model(x), y)</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>    loss.backward()</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>    optimizer.step()</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>elapsed <span class="op">=</span> time.perf_counter() <span class="op">-</span> t0</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> <span class="bu">float</span>(criterion(model(x), y))</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>n_params <span class="op">=</span> <span class="bu">sum</span>(p.numel() <span class="cf">for</span> p <span class="kw">in</span> model.parameters())</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parameters      </span><span class="sc">{</span>n_params<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cost at start   </span><span class="sc">{</span>start<span class="sc">:.4f}</span><span class="ss">      (Lab 2: 1.3256)"</span>)</span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cost at end     </span><span class="sc">{</span>end<span class="sc">:.4f}</span><span class="ss">      (Lab 2: 0.0190)"</span>)</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"wall time       </span><span class="sc">{</span>elapsed<span class="sc">:.2f}</span><span class="ss"> s for </span><span class="sc">{</span>STEPS<span class="sc">}</span><span class="ss"> steps"</span>)</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"work per step   1 forward + 1 backward, not </span><span class="sc">{</span>n_params <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> forwards"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>parameters      49
cost at start   1.3256      (Lab 2: 1.3256)
cost at end     0.0190      (Lab 2: 0.0190)
wall time       0.18 s for 400 steps
work per step   1 forward + 1 backward, not 50 forwards</code></pre>
</div>
</div>
</section>
<section id="what-is-left-to-get-wrong" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-is-left-to-get-wrong">What is left to get wrong</h2>
<p>The gradient is solved. Everything in the rest of this deck is a way for a <strong>correct</strong> gradient to still produce a bad model.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The optimizer</strong></p>
<ul>
<li>One learning rate for differently curved directions</li>
<li>Local minima, saddle points, plateaus</li>
<li>A rate that was right at step 1 and wrong at step 10,000</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Everything else</strong></p>
<ul>
<li>Initialization that kills the gradient before training starts</li>
<li>Batches too small to point the right way</li>
<li>A model that fits the noise instead of the signal</li>
</ul>
</div>
</div>
<p>That demo was 49 parameters on 200 clean points with one optimizer and no regularization. Every one of those choices was made for you.</p>
</section>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<ul>
<li>Why anyone uses batches</li>
<li><code>Dataset</code>, <code>DataLoader</code>, and the splits</li>
</ul>
<section id="full-batch-mini-batch-stochastic" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="full-batch-mini-batch-stochastic">Full batch, mini-batch, stochastic</h2>
<p>One <strong>optimizer step</strong> is one parameter update. How much data goes into it has a name. For <span class="math inline">N = 100</span> training examples:</p>
<table class="table">
<thead>
<tr class="header">
<th>Paradigm</th>
<th>Batch size</th>
<th>Updates per epoch</th>
<th>Gradient noise</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full batch</td>
<td>100</td>
<td>1</td>
<td>none</td>
</tr>
<tr class="even">
<td>Stochastic</td>
<td>1</td>
<td>100</td>
<td>very high</td>
</tr>
<tr class="odd">
<td>Mini-batch</td>
<td>25</td>
<td>4</td>
<td>moderate</td>
</tr>
</tbody>
</table>
<p>An <strong>epoch</strong> is one pass through the whole training set, which is <span class="math inline">\lceil N/B \rceil</span> iterations.</p>
<p>The demo above was <strong>full batch</strong> on 200 points, so there was one update per epoch and the cost curve came out smooth. That is not what anyone does, for two reasons: the whole dataset usually does not fit in memory, and the noise turns out to be <strong>useful</strong> rather than merely tolerable.</p>
</section>
<section id="batch-size-and-gradient-noise-measured" class="level2">
<h2 class="anchored" data-anchor-id="batch-size-and-gradient-noise-measured">Batch size and gradient noise, measured</h2>
<p><a href="images/fig-batch-noise.png" class="zoom" target="_blank"><img src="images/fig-batch-noise.png" class="dw89 img-fluid" width="1000"></a></p>
<p>A mini-batch gradient is an <strong>unbiased but noisy</strong> estimate of the full-batch gradient. Measured on a real network: the relative error is <span class="math inline">3.24</span> at <span class="math inline">B = 1</span>, <span class="math inline">0.60</span> at <span class="math inline">B = 32</span>, <span class="math inline">0.21</span> at <span class="math inline">B = 256</span>, and <span class="math inline">0.11</span> at <span class="math inline">B = 1024</span>, tracking <span class="math inline">1/\sqrt{B}</span> almost exactly.</p>
</section>
<section id="what-the-1sqrtb-curve-means-in-practice" class="level2">
<h2 class="anchored" data-anchor-id="what-the-1sqrtb-curve-means-in-practice">What the <span class="math inline">1/\sqrt{B}</span> curve means in practice</h2>
<p>Doubling the batch <strong>doubles the work per step</strong> and reduces the gradient error by a factor of only <span class="math inline">\sqrt{2}</span>, about 29%. Four times the compute buys you half the noise.</p>
<p>Two consequences:</p>
<ol type="1">
<li><strong>Big batches have diminishing returns.</strong> Going from 32 to 1024 is 32 times the compute per step for a 5.5-fold noise reduction</li>
<li><strong>Small batches are not just tolerable, they help.</strong> The noise lets the optimizer rattle out of sharp local minima and saddle points. A full-batch run gets stuck in places a mini-batch run walks straight past</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to pick a batch size
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pick the largest batch that fits comfortably in memory, then tune the learning rate for it. Batch sizes are powers of two out of habit and memory alignment, not mathematics.</p>
</div>
</div>
</section>
<section id="dataset" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="dataset"><code>Dataset</code></h2>
<p>A <code>Dataset</code> is a class you write with three methods.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>__init__</code></td>
<td>set up once: file paths, a dataframe, the transform list</td>
</tr>
<tr class="even">
<td><code>__len__</code></td>
<td>return how many examples there are</td>
</tr>
<tr class="odd">
<td><code>__getitem__(i)</code></td>
<td><strong>produce example <code>i</code></strong> and return it as tensors</td>
</tr>
</tbody>
</table>
<p><code>__getitem__</code> is the important one, and it is not a lookup. It is the recipe for turning example <span class="math inline">i</span> into tensors, and it runs <strong>every time that example is used</strong>. For a real dataset that means: open the file on disk, decode the JPEG or parse the audio, apply the crop and flip, convert to a tensor, return it.</p>
<p>Below, the data is small enough to sit in memory, so <code>__getitem__</code> really is just an index. That is the exception, not the rule.</p>
<div id="250ea72f" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.utils.data <span class="im">import</span> DataLoader, Dataset, random_split</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SineData(Dataset):</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, n<span class="op">=</span><span class="dv">200</span>, seed<span class="op">=</span><span class="dv">6600</span>):</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>        rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, n, dtype<span class="op">=</span>np.float32).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.y <span class="op">=</span> (np.sin(<span class="fl">3.0</span> <span class="op">*</span> <span class="va">self</span>.x.ravel())</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                  <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="fl">0.10</span>, n)).astype(np.float32).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__len__</span>(<span class="va">self</span>):</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">len</span>(<span class="va">self</span>.x)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__getitem__</span>(<span class="va">self</span>, i):</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.from_numpy(<span class="va">self</span>.x[i]), torch.from_numpy(<span class="va">self</span>.y[i])</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> SineData()</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>xi, yi <span class="op">=</span> data[<span class="dv">7</span>]</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"len(data)     </span><span class="sc">{</span><span class="bu">len</span>(data)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"data[7]       x </span><span class="sc">{</span><span class="bu">tuple</span>(xi.shape)<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>xi<span class="sc">.</span>item()<span class="sc">:+.4f}</span><span class="ss">   "</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"y </span><span class="sc">{</span><span class="bu">tuple</span>(yi.shape)<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>yi<span class="sc">.</span>item()<span class="sc">:+.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>len(data)     200
data[7]       x (1,) -0.9296   y (1,) -0.4883</code></pre>
</div>
</div>
</section>
<section id="dataloader" class="level2">
<h2 class="anchored" data-anchor-id="dataloader"><code>DataLoader</code></h2>
<p>A <code>DataLoader</code> wraps a <code>Dataset</code> and hands you batches. Shuffling and the short final batch are the easy part. The reason the class exists is <strong>speed</strong>.</p>
<p>One training step on a GPU takes a few milliseconds. Reading and decoding one JPEG takes around ten. Do both in one process and the GPU sits idle most of the run, waiting for the CPU to feed it. <strong>Most slow training runs in practice are slow for this reason</strong>, not because the model is large.</p>
<p>A <code>DataLoader</code> avoids that by building the next batch <strong>while the GPU is still working on the current one</strong>, in several processes at once.</p>
<div id="102221c0" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>loader <span class="op">=</span> DataLoader(data, batch_size<span class="op">=</span><span class="dv">32</span>, shuffle<span class="op">=</span><span class="va">True</span>, drop_last<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(data)<span class="sc">}</span><span class="ss"> examples, batch_size 32  -&gt;  </span><span class="sc">{</span><span class="bu">len</span>(loader)<span class="sc">}</span><span class="ss"> batches"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, (xb, yb) <span class="kw">in</span> <span class="bu">enumerate</span>(loader):</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  batch </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">: x </span><span class="sc">{</span><span class="bu">tuple</span>(xb.shape)<span class="sc">}</span><span class="ss">  y </span><span class="sc">{</span><span class="bu">tuple</span>(yb.shape)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">the last batch holds 8, because 200 is not a multiple of 32"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>200 examples, batch_size 32  -&gt;  7 batches
  batch 0: x (32, 1)  y (32, 1)
  batch 1: x (32, 1)  y (32, 1)
  batch 2: x (32, 1)  y (32, 1)
  batch 3: x (32, 1)  y (32, 1)
  batch 4: x (32, 1)  y (32, 1)
  batch 5: x (32, 1)  y (32, 1)
  batch 6: x (8, 1)  y (8, 1)

the last batch holds 8, because 200 is not a multiple of 32</code></pre>
</div>
</div>
</section>
<section id="dataloader-settings-that-matter" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="dataloader-settings-that-matter"><code>DataLoader</code> settings that matter</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Argument</th>
<th>What it does</th>
<th>What to set</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>num_workers</code></td>
<td>subprocesses that run <code>__getitem__</code> in parallel</td>
<td><strong>the one that matters.</strong> Start at 4, raise while it still helps</td>
</tr>
<tr class="even">
<td><code>pin_memory</code></td>
<td>stages batches in page-locked memory, so the copy to the GPU is faster and can overlap with compute</td>
<td><code>True</code> whenever you train on a GPU</td>
</tr>
<tr class="odd">
<td><code>persistent_workers</code></td>
<td>keeps workers alive between epochs instead of respawning them</td>
<td><code>True</code> when <code>num_workers &gt; 0</code></td>
</tr>
<tr class="even">
<td><code>prefetch_factor</code></td>
<td>batches each worker prepares ahead of time</td>
<td>leave at 2 until profiling says otherwise</td>
</tr>
<tr class="odd">
<td><code>shuffle</code></td>
<td>reshuffles the order every epoch</td>
<td><code>True</code> for training, <code>False</code> for validation and test</td>
</tr>
<tr class="even">
<td><code>drop_last</code></td>
<td>discards the short final batch</td>
<td><code>True</code> if you use batch norm, so you never get a batch of 1</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>train_loader <span class="op">=</span> DataLoader(train, batch_size<span class="op">=</span><span class="dv">64</span>, shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                          num_workers<span class="op">=</span><span class="dv">4</span>, pin_memory<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                          persistent_workers<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="recognizing-a-data-bound-training-run" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="recognizing-a-data-bound-training-run">Recognizing a data-bound training run</h2>
<p>Run <code>nvidia-smi</code> while training. If GPU utilization keeps falling to 0% and spiking back, the GPU is <strong>waiting on data</strong>. Raising <code>num_workers</code> will then speed up the run far more than any change you make to the model.</p>
<p>Three things worth knowing before you hit them:</p>
<ul>
<li>On Windows and macOS, <code>num_workers &gt; 0</code> starts workers by <strong>spawning</strong> new interpreters, which re-imports your script. Training code must sit behind <code>if __name__ == "__main__":</code> or it will spawn forever</li>
<li>More workers is not always better. Each one holds its own copy of the dataset object, and past the number of CPU cores they compete rather than help</li>
<li>If your examples have different lengths, batching them needs a <code>collate_fn</code>. The default one calls <code>torch.stack</code>, which requires identical shapes</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Where to put the data on the GPU
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>xb.to(device, non_blocking=True)</code> only overlaps the transfer with compute if the loader used <code>pin_memory=True</code>. The two settings are meant to be used together.</p>
</div>
</div>
</section>
<section id="the-loop-with-batches" class="level2">
<h2 class="anchored" data-anchor-id="the-loop-with-batches">The loop, with batches</h2>
<p>The five lines are unchanged. They now sit inside a second loop.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(EPOCHS):</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    model.train()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> xb, yb <span class="kw">in</span> train_loader:          <span class="co"># one iteration per batch</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> criterion(model(xb), yb)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()                          <span class="co"># dropout off, batch norm frozen</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():                 <span class="co"># no graph, since we will not</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>        val <span class="op">=</span> <span class="bu">sum</span>(criterion(model(xb), yb).item()  <span class="co">#  differentiate this</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>                  <span class="cf">for</span> xb, yb <span class="kw">in</span> val_loader) <span class="op">/</span> <span class="bu">len</span>(val_loader)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note which things moved. <code>zero_grad</code> is <strong>per batch</strong>, not per epoch. <code>model.train()</code> and <code>model.eval()</code> are <strong>per phase</strong>. The <code>no_grad</code> block wraps evaluation only.</p>
</section>
<section id="training-validation-and-test" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="training-validation-and-test">Training, validation, and test</h2>
<p>Three splits, three different jobs, and they are not interchangeable.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Split</th>
<th>Used for</th>
<th>How often you look</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Training</strong></td>
<td>computing gradients</td>
<td>every step</td>
</tr>
<tr class="even">
<td><strong>Validation</strong></td>
<td>choosing hyperparameters, early stopping</td>
<td>every epoch</td>
</tr>
<tr class="odd">
<td><strong>Test</strong></td>
<td>the one honest number</td>
<td><strong>once</strong>, at the end</td>
</tr>
</tbody>
</table>
<p>The validation set is not a held-out set once you have used it to pick a learning rate, a width, a dropout rate and a stopping epoch. You have fitted to it, with you as the optimizer. That is why the test set exists and why it gets looked at once.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>train, val <span class="op">=</span> random_split(data, [<span class="fl">0.8</span>, <span class="fl">0.2</span>],</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                          generator<span class="op">=</span>torch.Generator().manual_seed(<span class="dv">6600</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="leakage" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="leakage">Leakage</h2>
<p>Leakage is when information that should only be in the training set finds its way into training anyway. The validation score then measures memorization rather than generalization, so it looks excellent and the model is useless on new data.</p>
<p>Four common ways it happens:</p>
<ul>
<li><strong>Normalizing before splitting.</strong> The mean and standard deviation you subtracted contain the validation set. Fit the scaler on <strong>train</strong> and apply it to the others</li>
<li><strong>Splitting randomly when the data is grouped.</strong> Multiple rows per patient, per user or per document put the same entity on both sides</li>
<li><strong>Splitting randomly when the data is a time series.</strong> In production you only ever have the past, so training on future rows and testing on earlier ones measures something you will never be able to do. Split by time</li>
<li><strong>Duplicates.</strong> Near-identical rows on both sides are memorization dressed up as generalization</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to spot leakage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Validation cost that is suspiciously close to training cost, or a jump in performance right after you added a preprocessing step. Both are worth an hour of checking.</p>
</div>
</div>
</section>
</section>
<section id="optimizers" class="level1">
<h1>Optimizers</h1>
<ul>
<li>Why one learning rate is not enough for every parameter</li>
<li>Momentum, RMSProp, Adam</li>
</ul>
<section id="the-problem-with-one-learning-rate" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-problem-with-one-learning-rate">The problem with one learning rate</h2>
<p>Plain SGD applies <strong>one</strong> step size to every parameter:</p>
<p><span class="math display">\theta \leftarrow \theta - \eta \nabla_{\theta} \mathcal{L}</span></p>
<p>The problem is that the cost surface is much steeper in some directions than in others. A steep direction needs small steps, because a large one overshoots and the cost goes up. A shallow direction needs large steps, because small ones barely move. One value of <span class="math inline">\eta</span> has to work for both, so you are forced to pick a value small enough for the steepest direction, and every shallow direction then crawls.</p>
<p>The ratio of the steepest curvature to the shallowest is called the <strong>condition number</strong>. The larger it is, the worse this mismatch gets, and real networks have very large condition numbers.</p>
<p>Two independent fixes, and they compose:</p>
<ul>
<li><strong>Momentum</strong>: accumulate a velocity, so consistent directions build speed</li>
<li><strong>Adaptive rates</strong>: give every parameter its own step size, from its own gradient history</li>
</ul>
</section>
<section id="momentum" class="level2">
<h2 class="anchored" data-anchor-id="momentum">Momentum</h2>
<p>Keep a running velocity instead of stepping on the raw gradient:</p>
<p><span class="math display">\mathbf{v} \leftarrow \beta \mathbf{v} + \nabla_{\theta}\mathcal{L}
\qquad
\theta \leftarrow \theta - \eta \mathbf{v}</span></p>
<p><span class="math inline">\beta</span> is typically <span class="math inline">0.9</span>. Two things happen at once:</p>
<ul>
<li>In a direction where the gradient keeps <strong>pointing the same way</strong>, the velocity accumulates and the effective step grows, up to <span class="math inline">1/(1-\beta)</span> times the plain step. At <span class="math inline">\beta = 0.9</span> that is a factor of 10</li>
<li>In a direction where the gradient keeps <strong>flipping sign</strong>, successive terms cancel and the oscillation is damped</li>
</ul>
<p>That is exactly the combination an ill-conditioned surface needs: speed along the valley, calm across it.</p>
</section>
<section id="momentum-measured" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="momentum-measured">Momentum, measured</h2>
<p><a href="images/fig-momentum.gif" class="zoom" target="_blank"><img src="images/fig-momentum.gif" class="dw92 img-fluid" width="1000"></a></p>
<p>Both runs use the <strong>same learning rate</strong>, <span class="math inline">0.005</span>, for 25 steps. SGD settles into the floor of the valley almost immediately and then inches along it. Momentum overshoots across the valley again and again, and that does not matter, because the direction that counts is the shallow one and there it keeps building speed.</p>
<p>After 25 steps SGD has covered <span class="math inline">1.06</span> along the shallow axis and momentum has covered <span class="math inline">5.94</span>, which is <strong>5.6 times as far</strong>. The right panel is the part a still picture cannot show you: SGD’s line is straight, momentum’s bends upward.</p>
</section>
<section id="why-the-momentum-gap-has-that-size" class="level2">
<h2 class="anchored" data-anchor-id="why-the-momentum-gap-has-that-size">Why the momentum gap has that size</h2>
<p>For a quadratic with curvatures <span class="math inline">m</span> and <span class="math inline">L</span>, both optimal rates are known in closed form, so the figure is not a tuning accident. Write <span class="math inline">\kappa = L/m</span> for the condition number:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Best rate</th>
<th>Cost falls per step by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Plain SGD</td>
<td><span class="math inline">\eta = 2/(L+m)</span></td>
<td><span class="math inline">\dfrac{\kappa - 1}{\kappa + 1}</span></td>
</tr>
<tr class="even">
<td>Momentum</td>
<td><span class="math inline">\eta = 4/(\sqrt{L}+\sqrt{m})^2</span></td>
<td><span class="math inline">\dfrac{\sqrt{\kappa} - 1}{\sqrt{\kappa} + 1}</span></td>
</tr>
</tbody>
</table>
<p>Momentum replaces <span class="math inline">\kappa</span> with <span class="math inline">\sqrt{\kappa}</span>. At <span class="math inline">\kappa = 100</span> that is <span class="math inline">0.980</span> per step against <span class="math inline">0.818</span> per step, which over 80 steps is the difference between <span class="math inline">0.2</span> and <span class="math inline">10^{-7}</span>.</p>
<p>That square root is the entire theoretical benefit of momentum, and the figure is simply that formula playing out.</p>
</section>
<section id="rmsprop-and-adam" class="level2">
<h2 class="anchored" data-anchor-id="rmsprop-and-adam">RMSProp and Adam</h2>
<p><strong>RMSProp</strong> divides each parameter’s step by the running root-mean-square of its own recent gradients:</p>
<p><span class="math display">s \leftarrow \rho s + (1-\rho)g^2
\qquad
\theta \leftarrow \theta - \frac{\eta}{\sqrt{s} + \epsilon}\, g</span></p>
<p>A parameter with consistently large gradients gets a smaller step; one with tiny gradients gets a larger step. The learning rate becomes <strong>per parameter</strong> without you choosing millions of them.</p>
<p><strong>Adam</strong> is momentum and RMSProp at the same time, plus a correction for the fact that both running averages start at zero:</p>
<p><span class="math display">m \leftarrow \beta_1 m + (1-\beta_1) g
\qquad
v \leftarrow \beta_2 v + (1-\beta_2) g^2</span></p>
<p><span class="math display">\hat{m} = \frac{m}{1-\beta_1^t}, \quad \hat{v} = \frac{v}{1-\beta_2^t}
\qquad
\theta \leftarrow \theta - \frac{\eta}{\sqrt{\hat{v}} + \epsilon}\hat{m}</span></p>
<p>Defaults <span class="math inline">\beta_1 = 0.9</span>, <span class="math inline">\beta_2 = 0.999</span>, <span class="math inline">\epsilon = 10^{-8}</span> are almost never worth changing.</p>
</section>
<section id="four-optimizers-on-the-same-problem" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="four-optimizers-on-the-same-problem">Four optimizers on the same problem</h2>
<p><a href="images/fig-optimizers.png" class="zoom" target="_blank"><img src="images/fig-optimizers.png" class="dw92 img-fluid" width="1000"></a></p>
<p>The same quadratic, condition number 100, 80 steps, and <strong>each method running at its own best learning rate</strong>, so none of them is handicapped to make a point. SGD never gets within <span class="math inline">0.05</span> of the minimum and ends at cost <span class="math inline">4.59</span>. Momentum arrives at <strong>step 39</strong> and ends at <span class="math inline">1.8 \times 10^{-8}</span>. RMSProp arrives at step 55, Adam at step 78.</p>
<p>Do not read too much into that ordering. This is a clean quadratic and real loss surfaces are not. What Adam actually buys you is not the best final number, it is getting close to the answer <strong>without you having to find the best learning rate first</strong>, which is exactly the position you are in when you start.</p>
</section>
<section id="optimizers-in-pytorch" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="optimizers-in-pytorch">Optimizers in PyTorch</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Optimizer</th>
<th>Starting rate</th>
<th>When you would choose it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>SGD(lr=0.1)</code></td>
<td><span class="math inline">10^{-1}</span></td>
<td>Almost never on its own. It is the baseline everything else is compared against</td>
</tr>
<tr class="even">
<td><code>SGD(lr=0.1, momentum=0.9)</code></td>
<td><span class="math inline">10^{-1}</span></td>
<td>Image models, once you are willing to tune a learning-rate schedule. Often reaches the best final accuracy</td>
</tr>
<tr class="odd">
<td><code>RMSprop(lr=1e-3)</code></td>
<td><span class="math inline">10^{-3}</span></td>
<td>You will meet it in older recurrent-network code. Adam has replaced it for new work</td>
</tr>
<tr class="even">
<td><code>Adam(lr=1e-3)</code></td>
<td><span class="math inline">10^{-3}</span></td>
<td><strong>Start here.</strong> It works without tuning, which is what you want before you trust your code</td>
</tr>
<tr class="odd">
<td><code>AdamW(lr=1e-3)</code></td>
<td><span class="math inline">10^{-3}</span></td>
<td>Start here instead whenever you want weight decay. Same as Adam, with the decay implemented correctly</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>, weight_decay<span class="op">=</span><span class="fl">1e-2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note the rates differ by <strong>two orders of magnitude</strong> between SGD and Adam. A learning rate copied from an SGD recipe into Adam destabilizes training: on the Lab 4 network, Adam at <span class="math inline">0.1</span> instead of <span class="math inline">10^{-3}</span> drops validation accuracy from <span class="math inline">0.85</span> to <span class="math inline">0.62</span>. Nothing raises, which is what makes this one of the most common ways a working script stops working.</p>
</section>
<section id="choosing-an-optimizer" class="level2">
<h2 class="anchored" data-anchor-id="choosing-an-optimizer">Choosing an optimizer</h2>
<p>The honest summary:</p>
<ol type="1">
<li><strong>Start with Adam or AdamW at <span class="math inline">10^{-3}</span>.</strong> It is the least sensitive to a bad learning rate, which is what you want when you do not yet know whether your model is even wired up correctly</li>
<li><strong>If you are reproducing a paper, use what the paper used.</strong> This is not deference, it is that the learning rate and schedule were tuned together</li>
<li><strong>Well-tuned SGD with momentum often generalizes slightly better</strong> than Adam on vision tasks. It also takes much more tuning to get there</li>
<li><strong>The optimizer is rarely your problem.</strong> If the model is not learning, the cause is far more often the data, the shapes, the learning rate or the initialization</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What to change first
</div>
</div>
<div class="callout-body-container callout-body">
<p>Learning rate, by factors of ten, before anything else. It is the single most important hyperparameter, and it is not close.</p>
</div>
</div>
</section>
</section>
<section id="learning-rate-schedules" class="level1">
<h1>Learning-rate schedules</h1>
<ul>
<li>The right rate at step 1 is the wrong rate at step 10,000</li>
<li>Warmup, decay, and clipping</li>
</ul>
<section id="why-the-rate-should-change" class="level2">
<h2 class="anchored" data-anchor-id="why-the-rate-should-change">Why the rate should change</h2>
<p>Early in training you are far from any minimum and want to cover ground. Late in training you are near one and want to stop overshooting it. A <strong>schedule</strong> is a rule for lowering <span class="math inline">\eta</span> over time.</p>
<p>You can recognize a rate that should have been lowered. The cost falls for a while, then flattens into a noisy band and stops improving. What is happening is that the optimizer is stepping over the minimum and back again. Cut the rate and the cost drops visibly within a few epochs, which is why loss curves under a step schedule have that staircase shape.</p>
</section>
<section id="five-schedules" class="level2">
<h2 class="anchored" data-anchor-id="five-schedules">Five schedules</h2>
<p><a href="images/fig-lr-schedules.png" class="zoom" target="_blank"><img src="images/fig-lr-schedules.png" class="dw89 img-fluid" width="1000"></a></p>
<p>All five start at <span class="math inline">\eta = 0.1</span>. At epoch 50, step decay is at <span class="math inline">0.0100</span>, exponential is at <span class="math inline">0.0077</span>, and cosine is at <span class="math inline">0.0500</span>.</p>
<p><strong>Cosine annealing</strong> is the common default: smooth, no cliff edges, and it ends near zero without you choosing when.</p>
</section>
<section id="warmup" class="level2">
<h2 class="anchored" data-anchor-id="warmup">Warmup</h2>
<p>The first few hundred steps are the most dangerous in a training run. The weights are random, so the gradients are large and unrepresentative, and Adam’s variance estimate <span class="math inline">\hat{v}</span> is built from almost no data.</p>
<p><strong>Warmup</strong> ramps the rate linearly from near zero to the target over a few hundred steps or a few epochs, then hands over to the main schedule.</p>
<ul>
<li>Essential for transformers, where training without it frequently diverges in the first thousand steps</li>
<li>Cheap insurance everywhere else</li>
<li>Shows up in the figure as the green line climbing before it anneals</li>
</ul>
<p>Usually a few percent of total training. Longer does no harm.</p>
</section>
<section id="gradient-clipping" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="gradient-clipping">Gradient clipping</h2>
<p>Clipping puts a ceiling on how large one update can be. If a single batch produces an enormous gradient, one step can destroy a model that took hours to train.</p>
<p><a href="images/fig-grad-clipping.png" class="zoom" target="_blank"><img src="images/fig-grad-clipping.png" class="dw85 img-fluid" width="1000"></a></p>
<p><strong>Left.</strong> A gradient already below the threshold <span class="math inline">C</span> passes through untouched. Anything above <span class="math inline">C</span> is scaled down to exactly <span class="math inline">C</span>.</p>
<p><strong>Middle.</strong> Two versions, and they are not the same operation. <code>clip_grad_norm_</code> rescales the whole vector and the direction does not change. <code>clip_grad_value_</code> clamps each component on its own, moving this gradient 14 degrees. Use the norm version.</p>
<p><strong>Right.</strong> The same run twice, with one corrupted batch at step 14. Unclipped, that step travels 24 units, lands at <span class="math inline">(21, -5)</span> and takes the cost from <span class="math inline">2.3</span> to <span class="math inline">443</span>. Clipped, it heads the same way and travels <span class="math inline">1.3</span>, and the run ends at <span class="math inline">0.12</span>.</p>
</section>
<section id="gradient-clipping-in-the-training-loop" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="gradient-clipping-in-the-training-loop">Gradient clipping in the training loop</h2>
<p>Every parameter gradient in the model is treated as <strong>one long vector</strong> <span class="math inline">\mathbf{g}</span>. The norm is taken across the whole model, not per layer. Then:</p>
<p><span class="math display">\mathbf{g} \leftarrow C \cdot \frac{\mathbf{g}}{\|\mathbf{g}\|}
\qquad \text{whenever} \qquad \|\mathbf{g}\| &gt; C</span></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>loss.backward()                                    <span class="co"># gradients now exist</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>optimizer.step()                                   <span class="co"># and are used here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Those three lines have to be in that order. Clipping needs the gradients to exist, so it goes after <code>backward()</code>, and it has to act before <code>step()</code> reads them.</p>
<ul>
<li><span class="math inline">C</span> is usually between <strong>1 and 10</strong>. Start at <span class="math inline">1.0</span></li>
<li>It is standard practice for recurrent networks and transformers. Everywhere else it costs almost nothing and occasionally saves a run</li>
<li>If clipping fires on most steps, <span class="math inline">C</span> is too low. At that point you are ignoring the size of the gradient entirely and following only its direction</li>
</ul>
</section>
<section id="schedules-in-pytorch" class="level2">
<h2 class="anchored" data-anchor-id="schedules-in-pytorch">Schedules in PyTorch</h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>scheduler <span class="op">=</span> torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max<span class="op">=</span>EPOCHS)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(EPOCHS):</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> xb, yb <span class="kw">in</span> train_loader:</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>        criterion(model(xb), yb).backward()</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    scheduler.step()                     <span class="co"># once per epoch, not per batch</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>scheduler.step()</code> goes <strong>outside</strong> the batch loop for epoch-based schedules and inside it for step-based ones. Putting an epoch-based scheduler inside the batch loop decays the rate <span class="math inline">\lceil N/B \rceil</span> times too fast, which looks like a model that learns for one epoch and then stops.</p>
<p>Worth printing: <code>optimizer.param_groups[0]["lr"]</code>.</p>
</section>
</section>
<section id="initialization" class="level1">
<h1>Initialization</h1>
<ul>
<li>Initialization decides whether a deep network trains at all</li>
<li>Xavier and He</li>
</ul>
<section id="why-initialization-decides-whether-training-starts" class="level2">
<h2 class="anchored" data-anchor-id="why-initialization-decides-whether-training-starts">Why initialization decides whether training starts</h2>
<p>In Week 2 we set the weights randomly and moved on. At two layers it did not matter. At twenty layers it decides whether the run does anything at all.</p>
<p>The forward pass multiplies by a weight matrix at every layer, and the backward pass multiplies by its transpose. Both are products of many factors:</p>
<ul>
<li>If the factors are <strong>slightly above 1</strong>, twenty of them multiply to something enormous</li>
<li>If they are <strong>slightly below 1</strong>, twenty of them multiply to nothing</li>
<li>Only a narrow band keeps the signal roughly the same size all the way through</li>
</ul>
<p>Zero initialization is worse still: every unit in a layer computes the same thing, receives the same gradient, and updates identically forever. A 512-unit layer does the work of one unit. <strong>Randomness is what breaks that symmetry.</strong></p>
</section>
<section id="initialization-measured" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="initialization-measured">Initialization, measured</h2>
<p><a href="images/fig-init-variance.png" class="zoom" target="_blank"><img src="images/fig-init-variance.png" class="dw92 img-fluid" width="1000"></a></p>
<p>Twelve tanh layers, 256 wide. <strong>Only the initialization differs</strong>, and the two panels disagree about who is in trouble.</p>
<p><strong>Left</strong>: <span class="math inline">\mathcal{N}(0,1)</span> looks fine, holding an activation spread near <span class="math inline">1.0</span> the whole way down. <strong>Right</strong>: it is the worst of the four. Gradient norms run from <span class="math inline">9.9 \times 10^{2}</span> at layer 1 to <span class="math inline">7.2 \times 10^{-3}</span> at layer 12, five orders of magnitude apart.</p>
</section>
<section id="why-the-two-naive-initializations-fail" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-the-two-naive-initializations-fail">Why the two naive initializations fail</h2>
<p><strong><span class="math inline">\mathcal{N}(0,1)</span>, the red line.</strong> With 256 inputs, the pre-activations have a standard deviation near 16, so tanh is pinned against <span class="math inline">\pm 1</span>: <strong>86.6%</strong> of units in the last layer are saturated. The activations look healthy precisely <em>because</em> they are clipped. A saturated tanh has derivative <span class="math inline">1 - a^2 \approx 0</span>, but the weights are large enough that the backward multiplication more than makes up for it, so the gradient <strong>explodes</strong> as it travels back toward the input.</p>
<p><strong><span class="math inline">\mathcal{N}(0, 0.01)</span>, the blue line.</strong> The signal is gone by layer 2, and the gradient is around <span class="math inline">10^{-19}</span> at every layer. Nothing will ever update.</p>
<p>One is far too large and one is far too small, and the forward pass tells you this about neither of them.</p>
</section>
<section id="why-xavier-and-he-both-work" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-xavier-and-he-both-work">Why Xavier and He both work</h2>
<p><strong>Xavier, the green line.</strong> Activation spread settles near <span class="math inline">0.21</span>, and the gradient norm is <span class="math inline">1.3 \times 10^{-2}</span> at layer 1 against <span class="math inline">1.7 \times 10^{-2}</span> at layer 12. That is flat, and flat is what you want.</p>
<p><strong>He, the orange line.</strong> Also flat: <span class="math inline">3.6 \times 10^{-2}</span> at layer 1 against <span class="math inline">4.4 \times 10^{-2}</span> at layer 12. He uses a larger variance than Xavier, <span class="math inline">2/n_{\text{in}}</span> rather than <span class="math inline">2/(n_{\text{in}} + n_{\text{out}})</span>, so its activations sit higher, near <span class="math inline">0.56</span> instead of <span class="math inline">0.21</span>, and <span class="math inline">0.1\%</span> of units saturate rather than none. That is slightly more than a tanh network needs, and it trains perfectly well anyway.</p>
<p><strong>Both principled schemes work and both naive ones fail</strong>, and the gap between those two groups is twenty orders of magnitude. Matching the scheme to the activation function is a refinement. Using one at all is not.</p>
<p>When you are debugging, remember that <strong>a forward pass that looks reasonable proves nothing.</strong> Check the gradients.</p>
</section>
<section id="xavier-and-he" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="xavier-and-he">Xavier and He</h2>
<p>Both pick the variance of <span class="math inline">\mathbf{W}</span> so that the signal keeps its size as it passes through a layer. They differ in which activation they assume.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Variance</th>
<th>For</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Xavier / Glorot</strong></td>
<td><span class="math inline">\dfrac{2}{n_{\text{in}} + n_{\text{out}}}</span></td>
<td>tanh, sigmoid</td>
</tr>
<tr class="even">
<td><strong>He / Kaiming</strong></td>
<td><span class="math inline">\dfrac{2}{n_{\text{in}}}</span></td>
<td>ReLU and its relatives</td>
</tr>
</tbody>
</table>
<p>He carries the extra factor of 2 because ReLU zeroes half its inputs, so half the variance is lost and has to be put back.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> m <span class="kw">in</span> model.modules():</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(m, nn.Linear):</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>        nn.init.kaiming_normal_(m.weight, nonlinearity<span class="op">=</span><span class="st">"relu"</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>        nn.init.zeros_(m.bias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Biases start at zero.</strong> The weights already break the symmetry, so there is nothing left for a random bias to fix.</p>
<p><code>nn.Linear</code> already defaults to a Kaiming-uniform variant, which is why the small models in this course train without you touching any of this. Past about ten layers it stops being automatic.</p>
</section>
</section>
<section id="regularization" class="level1">
<h1>Regularization</h1>
<ul>
<li>Fitting the noise, and four ways to stop</li>
</ul>
<section id="overfitting-measured" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="overfitting-measured">Overfitting, measured</h2>
<p><a href="images/fig-overfitting.png" class="zoom" target="_blank"><img src="images/fig-overfitting.png" class="dw92 img-fluid" width="1000"></a></p>
<p>Forty noisy points, a 33,000-parameter network, 3000 epochs of Adam. The dotted line is the <strong>noise floor</strong>, <span class="math inline">0.22^2 = 0.048</span>: no honest model can score below it, because that much of the target is noise.</p>
<p><strong>Left</strong>: training cost goes <strong>through</strong> the floor to <span class="math inline">0.015</span>, which is the definition of fitting the noise. Validation bottoms out at epoch <strong>104</strong> and then gets <span class="math inline">1.81</span> times worse.</p>
</section>
<section id="reading-the-gap" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-gap">Reading the gap</h2>
<p>The two curves separating is the entire diagnosis. Training cost falling while validation cost rises means the model is learning things that are true of <strong>these 40 points</strong> and false of everything else.</p>
<p>Three numbers from that run worth carrying:</p>
<ul>
<li>Validation was at its best after <strong>104 of 3000 epochs</strong>. The remaining 97% of the compute made the model worse</li>
<li>Training cost ended at <span class="math inline">0.015</span>, <strong>below</strong> the <span class="math inline">0.048</span> noise floor. A model that beats the noise floor on training data has memorized the noise</li>
<li>With dropout <span class="math inline">0.1</span> and weight decay <span class="math inline">10^{-3}</span>, the final model is <strong>1.77 times better</strong> on validation, and the validation curve never turns around</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why a noise floor is worth computing
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you know roughly how noisy your labels are, you know what a good cost looks like. A training cost far below that is not a triumph.</p>
</div>
</div>
</section>
<section id="early-stopping" class="level2">
<h2 class="anchored" data-anchor-id="early-stopping">Early stopping</h2>
<p>The cheapest regularizer, and the one you should always have on. Evaluate on validation every epoch, keep the best weights, and stop when they stop improving.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>best, best_state, patience, waited <span class="op">=</span> <span class="bu">float</span>(<span class="st">"inf"</span>), <span class="va">None</span>, <span class="dv">20</span>, <span class="dv">0</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(EPOCHS):</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    train_one_epoch()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    val <span class="op">=</span> evaluate()</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> val <span class="op">&lt;</span> best:</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>        best, best_state, waited <span class="op">=</span> val, copy.deepcopy(model.state_dict()), <span class="dv">0</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>        waited <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> waited <span class="op">&gt;=</span> patience:</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>model.load_state_dict(best_state)         <span class="co"># the point of the whole exercise</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Two details people skip. <strong>Patience</strong>, so one noisy epoch does not stop the run. And <strong>restoring the best weights</strong>, without which you have carefully identified the best epoch and then shipped a later one.</p>
</section>
<section id="weight-decay" class="level2">
<h2 class="anchored" data-anchor-id="weight-decay">Weight decay</h2>
<p>Add a penalty on the size of the weights to the cost:</p>
<p><span class="math display">\mathcal{L}_{\text{total}} = \mathcal{L} + \lambda \sum_j w_j^2</span></p>
<p>The gradient of the penalty is <span class="math inline">2\lambda w</span>, so every step pulls every weight a little toward zero. Large weights have to <strong>earn</strong> their size by reducing the data term more than the penalty costs.</p>
<p>This is ridge, or <span class="math inline">L_2</span>, regularization, arriving in a new setting. <span class="math inline">L_1</span> penalties, <span class="math inline">\lambda \sum_j |w_j|</span>, drive weights to exactly zero instead and are used when sparsity is the goal.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>, weight_decay<span class="op">=</span><span class="fl">1e-2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<code>Adam(weight_decay=...)</code> is not <code>AdamW</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>In plain <code>Adam</code> the penalty goes through the adaptive rescaling, so parameters with small gradients get decayed harder. <code>AdamW</code> applies the decay separately, which is what the maths above describes. <strong>Use <code>AdamW</code>.</strong></p>
</div>
</div>
</section>
<section id="dropout" class="level2">
<h2 class="anchored" data-anchor-id="dropout">Dropout</h2>
<p><a href="images/fig-dropout.png" class="zoom" target="_blank"><img src="images/fig-dropout.png" class="dw89 img-fluid" width="960"></a></p>
<p>At every training step, switch off each hidden unit independently with probability <span class="math inline">p</span>. A different subnetwork is trained each step, and no unit can rely on any particular other unit being present.</p>
<p>At evaluation, all units are active and the activations are rescaled so the expected value matches training.</p>
</section>
<section id="dropout-in-practice" class="level2">
<h2 class="anchored" data-anchor-id="dropout-in-practice">Dropout in practice</h2>
<div class="sourceCode" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="va">self</span>.net <span class="op">=</span> nn.Sequential(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    nn.Linear(<span class="dv">256</span>, <span class="dv">256</span>), nn.ReLU(), nn.Dropout(<span class="fl">0.2</span>),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    nn.Linear(<span class="dv">256</span>, <span class="dv">256</span>), nn.ReLU(), nn.Dropout(<span class="fl">0.2</span>),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    nn.Linear(<span class="dv">256</span>, <span class="dv">10</span>),                      <span class="co"># never after the output layer</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><span class="math inline">p</span> between <span class="math inline">0.1</span> and <span class="math inline">0.5</span>. Start at <span class="math inline">0.2</span></li>
<li><strong>After</strong> the activation, not before</li>
<li><strong>Not</strong> after the final layer. You would be randomly deleting predictions</li>
<li><code>model.eval()</code> is what switches it off. This is the reason that call exists, and forgetting it makes your validation number both worse and unrepeatable</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why dropout works
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dropout is an ensemble argument. You are training exponentially many subnetworks that share weights, and evaluating something close to their average. It also acts like noise injection, which discourages the model from depending on any single feature.</p>
</div>
</div>
</section>
<section id="batch-and-layer-normalization" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="batch-and-layer-normalization">Batch and layer normalization</h2>
<p>Standardize the activations <strong>inside</strong> the network, not just the inputs.</p>
<p><strong>Batch norm</strong> normalizes each feature across the batch, then applies a learned scale and shift:</p>
<p><span class="math display">\hat{z} = \frac{z - \mu_{\text{batch}}}{\sqrt{\sigma^2_{\text{batch}} + \epsilon}},
\qquad y = \gamma \hat{z} + \beta</span></p>
<p>It lets you use larger learning rates, reduces sensitivity to initialization, and regularizes slightly as a side effect of the batch noise.</p>
<p><strong>The catch</strong> is that it behaves differently in training and evaluation. In training it uses this batch’s statistics; in evaluation it uses a running average collected during training. That is the other half of why <code>model.eval()</code> exists, and why batch norm is unreliable at very small batch sizes.</p>
<p><strong>Layer norm</strong> normalizes across the features of each example instead, so it does not depend on the batch at all. That is why transformers use it.</p>
</section>
<section id="what-to-reach-for-in-order" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-to-reach-for-in-order">What to reach for, in order</h2>
<p>Overfitting is not one problem with one fix. In rough order of what to try:</p>
<ol type="1">
<li><strong>More data.</strong> Nothing else comes close. Augmentation counts</li>
<li><strong>Early stopping.</strong> Free, and you should already have it</li>
<li><strong>Weight decay.</strong> One number, usually <span class="math inline">10^{-4}</span> to <span class="math inline">10^{-2}</span></li>
<li><strong>Dropout.</strong> Start at <span class="math inline">0.2</span> in the wide layers</li>
<li><strong>A smaller model.</strong> Effective, and the last resort, because capacity you remove is capacity you cannot get back by tuning</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Diagnose before you treat
</div>
</div>
<div class="callout-body-container callout-body">
<p>Training cost <strong>and</strong> validation cost both high is <strong>underfitting</strong>. More regularization will make it worse. Train longer, use a bigger model, or check that your learning rate is not wrong.</p>
<p>Regularization is for the case where training cost is low and validation cost is not.</p>
</div>
</div>
</section>
</section>
<section id="putting-it-all-together" class="level1">
<h1>Putting it all together</h1>
<ul>
<li>Everything in this deck, in one script</li>
</ul>
<section id="the-full-loop" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-full-loop">The full loop</h2>
<p>Every line here has appeared somewhere above. This is the shape of every training script for the rest of the semester.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> MLP().to(device)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.AdamW(model.parameters(), lr<span class="op">=</span><span class="fl">1e-3</span>, weight_decay<span class="op">=</span><span class="fl">1e-2</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>scheduler <span class="op">=</span> torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max<span class="op">=</span>EPOCHS)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.MSELoss()</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(EPOCHS):</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    model.train()                                  <span class="co"># dropout on</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> xb, yb <span class="kw">in</span> train_loader:</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>        xb, yb <span class="op">=</span> xb.to(device), yb.to(device)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()                      <span class="co"># clear the running sum</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> criterion(model(xb), yb)            <span class="co"># forward</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>        loss.backward()                            <span class="co"># backward</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>        torch.nn.utils.clip_grad_norm_(model.parameters(), <span class="fl">1.0</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>        optimizer.step()                           <span class="co"># update</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    scheduler.step()                               <span class="co"># once per epoch</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()                                   <span class="co"># dropout off</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():                          <span class="co"># no graph</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>        val <span class="op">=</span> mean(criterion(model(xb.to(device)), yb.to(device)).item()</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>                   <span class="cf">for</span> xb, yb <span class="kw">in</span> val_loader)</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> val <span class="op">&lt;</span> best:</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>        best, best_state, waited <span class="op">=</span> val, deepcopy(model.state_dict()), <span class="dv">0</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>        waited <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> waited <span class="op">&gt;=</span> PATIENCE:</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>model.load_state_dict(best_state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="saving-a-model" class="level2">
<h2 class="anchored" data-anchor-id="saving-a-model">Saving a model</h2>
<p>Save the <strong><code>state_dict</code></strong>, not the model object.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>torch.save({<span class="st">"model"</span>: model.state_dict(),</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>            <span class="st">"optimizer"</span>: optimizer.state_dict(),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"epoch"</span>: epoch}, <span class="st">"checkpoint.pt"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>ckpt <span class="op">=</span> torch.load(<span class="st">"checkpoint.pt"</span>, map_location<span class="op">=</span>device)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>model.load_state_dict(ckpt[<span class="st">"model"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>torch.save(model)</code> pickles your class definition along with the weights, so the file breaks when you rename or move the class. A <code>state_dict</code> is just a dictionary of tensors and will still load in a year.</p>
<p>Save the <strong>optimizer</strong> state too if you intend to resume. Adam’s <span class="math inline">m</span> and <span class="math inline">v</span> took the whole run to build, and restarting without them gives you a visible bump in the cost curve.</p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(SEED)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>np.random.seed(SEED)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>generator <span class="op">=</span> torch.Generator().manual_seed(SEED)       <span class="co"># for DataLoader shuffling</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>loader <span class="op">=</span> DataLoader(data, batch_size<span class="op">=</span><span class="dv">32</span>, shuffle<span class="op">=</span><span class="va">True</span>, generator<span class="op">=</span>generator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Seeding <code>torch</code> alone is not enough: the <code>DataLoader</code>’s shuffling, any augmentation, and dropout masks all draw from streams you have to seed explicitly.</p>
<p>Even then, bit-exact reproducibility across <strong>different GPUs</strong> or different library versions is not something to expect. What you should expect is that the same script on the same machine gives the same curve, and that is enough to tell a real improvement from noise.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why seeding matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>Without a seed you cannot tell whether your change helped or whether you got a better draw. Run the baseline twice before believing any small improvement.</p>
</div>
</div>
</section>
<section id="when-a-model-will-not-learn" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="when-a-model-will-not-learn">When a model will not learn</h2>
<p>In the order that finds the problem fastest:</p>
<ol type="1">
<li><strong>Can it overfit 10 examples?</strong> Take a tiny subset, turn off regularization, and drive the training cost to near zero. If it cannot, the bug is in the code, not the hyperparameters. This is the highest-value test in the list</li>
<li><strong>Print shapes.</strong> Especially <code>pred.shape</code> against <code>y.shape</code></li>
<li><strong>Is the cost even changing?</strong> If not: missing <code>optimizer.step()</code>, a learning rate of zero, parameters not registered, or <code>requires_grad</code> off</li>
<li><strong>Is the cost <code>nan</code>?</strong> Learning rate too high, a <span class="math inline">\log</span> of zero, or a division by a near-zero. Clip, and lower the rate</li>
<li><strong>Learning rate, by factors of ten.</strong> Both directions</li>
<li><strong>Are <code>zero_grad</code> and <code>train</code>/<code>eval</code> in the right places?</strong></li>
<li><strong>Look at the data.</strong> Plot a batch. Check the labels line up with the inputs. Check the scaling</li>
<li><strong>Only then</strong> change the architecture</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Overfit a tiny subset first
</div>
</div>
<div class="callout-body-container callout-body">
<p>Overfit a tiny subset <strong>first</strong>, every time, before any real run. It separates “my code is wrong” from “my model is wrong,” and those have completely different fixes.</p>
</div>
</div>
</section>
</section>
<section id="closing" class="level1">
<h1>Closing</h1>
<ul>
<li>Assessment</li>
<li>Supplemental content</li>
<li>Quiz 4, right now</li>
</ul>
<section id="labs-and-quizzes" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="labs-and-quizzes">Labs and quizzes</h2>
<p><strong>Lab 3 was due yesterday</strong>, Wednesday Sep 23. It was the backpropagation lab: the <code>Value</code> class, the matrix backward pass, and the forward-pass count.</p>
<p><strong>Quiz 4 is today</strong>, at the end of class. It covers <strong>last week’s backpropagation material plus Lab 3</strong>: the worked backward pass, summing over paths, topological order, reverse against forward mode, the sigmoid and cross-entropy cancellation, the three layer gradients, and vanishing gradients. <strong>Nothing from this deck is on it.</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
When this deck becomes quizzable
</div>
</div>
<div class="callout-body-container callout-body">
<p>Quiz 5, next week. PyTorch, the training loop, optimizers, schedules, initialization and regularization. Everything from today, plus Lab 4.</p>
<p><strong>The format changes for this one</strong>, because the material is code. Instead of the multiple-answer and short-answer parts you have seen, there is a fill-in-the-blank part where you compute a number, and a part where you are given a training script that runs fine and trains badly, and you find three things wrong with it. The study guide goes through all of it.</p>
</div>
</div>
</section>
<section id="supplemental-content" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="supplemental-content">Supplemental content</h2>
<p>These are <strong>optional</strong>. No graded work assumes you read them. They go deeper than we have time for, and the PyTorch pages are the source material this deck was built from.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>PyTorch</strong></p>
<ul>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-tensors/notes.html">Tensors</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-models/torch-models.html">Models</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/pytorch/torch-data/torch-data.html">Data</a></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Optimization and training</strong></p>
<ul>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/fundamentals/gradient-descent/notes.html">Gradient descent</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/mathematics/solvers-and-optimization/numerical-methods/numerical-optimization/notes.html">Numerical optimization</a></li>
<li><a href="https://jfh.georgetown.domains/centralized-lecture-content/content/machine-learning/deep-learning/backprop/automatic-differentiation/automatic-differentiation.html">Automatic differentiation</a></li>
</ul>
</div>
</div>
<p><sup>All of these live on the <a href="https://jfh.georgetown.domains/centralized-lecture-content/">centralized lecture content</a> site. The Data page covers <code>Dataset</code> and <code>DataLoader</code> in more detail than this deck does, including the multiprocessing options we skipped, and is the one to read before the next lab.</sup></p>
</section>
<section id="wrap-up" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>The gradient stopped being the hard part three weeks ago. What is left:</p>
<ul>
<li>A <strong>tensor</strong> is an array that records the operations producing it, which is what makes <code>.backward()</code> possible</li>
<li><strong><code>.grad</code> accumulates</strong>, so <code>zero_grad()</code> is not optional, and the reason is the fork in the graph from Week 4</li>
<li><strong><code>nn.Module</code></strong> registers parameters; <strong><code>model.eval()</code></strong> switches dropout off and freezes batch norm, and forgetting it corrupts your validation number</li>
<li><strong>Mini-batch noise</strong> falls like <span class="math inline">1/\sqrt{B}</span>, and it is useful rather than merely tolerable</li>
<li><strong>Momentum</strong> turns <span class="math inline">\kappa</span> into <span class="math inline">\sqrt{\kappa}</span>; <strong>Adam</strong> gives every parameter its own rate and is the right first choice</li>
<li><strong>Initialization</strong> decides whether a deep network trains at all, and a healthy forward pass proves nothing about the backward pass</li>
<li><strong>Regularization</strong> is for low training cost with high validation cost, and for nothing else</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Next
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Convolutional networks.</strong> Everything here still applies; what changes is the layer. Weight sharing, locality, and why a fully connected layer is the wrong tool for an image.</p>
</div>
</div>
</section>
<section id="quiz-4" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="quiz-4">Quiz 4</h2>
<p>Closed-book, no notes. A formula sheet comes with it.</p>
<p>Covers <strong>the second half of backpropagation</strong>, picking up where Quiz 3 stopped:</p>
<ul>
<li>Local derivatives at a node: add, multiply, ReLU</li>
<li>Working a backward pass through a graph and reading off the numbers</li>
<li>Adding gradients where two paths meet</li>
<li>Topological order, and what breaks without it</li>
<li>Reverse mode against forward mode, and why a scalar cost decides it</li>
<li>The sigmoid and cross-entropy cancellation</li>
<li>The three gradients a layer owes, and why nobody forms a Jacobian</li>
<li>Exploding and vanishing gradients</li>
</ul>
<p><strong>Plus Lab 3</strong>: why <code>Value</code> accumulates with <code>+=</code>, why the backward pass needs a seed of <span class="math inline">1.0</span>, and what 20,001 against 401 showed.</p>
<p>Twenty-five points, about fifteen minutes. Nothing from today’s deck.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>